### ISSUE TITLE
Just want to says: I like this project

### ISSUE THREAD

**Issue by andytruong** [opendevshop/devshop#1]
Thank you soon much!

**Comment by mrsinguyen** [comment]
Yup, Like this, thanks so much.

**Comment by ocditimban** [comment]
:) thanks

**Comment by jonpugh** [comment]
Wow, thanks! 

It's really nice to hear from people using the project.  I really do appreciate your feedback!

**Comment by niccolox** [comment]
I am using it now for a project and GODDAMN ! good job

**Comment by llwp** [comment]
+1 @niccolox

**Comment by jonpugh** [comment]
Hey @andytruong would you mind getting in touch? I have a question for you!

jon@thinkdrop.net
