### ISSUE TITLE
Docker dev script doesn't set permissions for non root aegir user on drush/commands or profiles/hostmaster

### ISSUE THREAD

**Issue by arosboro** [opendevshop/devshop#108]
The docker dev script mounts volumes for local development, but the aegir user cannot access write permissions for the directories as they are mounted owned by user 1000:1000

**Comment by jonpugh** [comment]
@arosboro check out the new `Robofile.php` system.  The 'robo up' command will automatically detect your UID and create a new container with the Aegir user set to use your UID.
