### ISSUE TITLE
Support letsencrypt out of the box

### ISSUE THREAD

**Issue by lsolesen** [opendevshop/devshop#112]
I have no idea whether it is possible to support letsencrypt out of the box, but that would be pretty neat.

**Comment by jonpugh** [comment]
The Aegir team was just talking about this...

I think I over heard that we need to make some changes to how the SSL setup works .

Was it @gboudrias that was talking about it?

**Comment by gboudrias** [comment]
Yeah I talked about it with @ergonlogic but it seems the API changes for a general solution would prohibit this from being in 3.x.

Funnily enough, @omega8cc was just tweeting me about using letsencrypt.sh to make their LE work: https://twitter.com/omega8cc/status/731321340364460032

Seems like they forked awforce_ssl (the module I wrote) into https://github.com/omega8cc/hosting_le

Maybe it should go onto drupal.org at this point? It's still a quick hack ¯\_(ツ)_/¯

**Comment by omega8cc** [comment]
Yes, we have forked and renamed the module to make it work with BOA, and while it is still a quick hack, it is clever hack, because it works! Thanks again!

Now we need to make `hosting_le` Aegir-fork-agnostic, so it will work out of the box with vanilla Aegir (still Nginx only, though). It should download `letsencrypt.sh` for you, set all required dirs and permissions etc, so all you will need to do is to enable `hosting_le` -- maybe it should even switch `server_master` from `nginx` to `nginx_ssl` and reverify it automatically? We are doing this in BOA outside of this extension, but it could be implemented directly in the `hosting_le` code.

**Comment by ergonlogic** [comment]
While the "correct" fix for this requires some API changes, and thus an Aegir 4.x release, I'd be fine with including a contrib extension into golden contrib to handle it in the 3.x branch. We'd want it to at least support both Apache and Nginx though.

**Comment by jonpugh** [comment]
@gboudrias @ergonlogic do you have a link to any issue or discussion about this?

I'm curious about what changes would be needed...

**Comment by omega8cc** [comment]
Not sure about Apache, but for Nginx the only changes we have introduced in Aegir, are listed below:

https://github.com/omega8cc/provision/commit/70896df743ba045d2e432d0712646098dfebd6b0
https://github.com/omega8cc/provision/commit/36ce31f91d4d4068c7603604f5cfe252a158806e
https://github.com/omega8cc/provision/commit/120d54f89e3280fbd99c741b37571c90079bb033

https://github.com/omega8cc/hosting/commit/15192e4ec9e7d0f4480a0434ab4ec8250944eccb
https://github.com/omega8cc/hosting/commit/8ce9922c7f4156556399f52327c629cfc5b48291

https://github.com/omega8cc/eldir/commit/293fc395757e93c0c6366fc929846c1d2687e974

Some of them need only simple adjustments to make them work with vanilla Aegir.

**Comment by omega8cc** [comment]
@ergonlogic The `hosting_le` should probably have two submodules, each with server specific dependencies, like we have `hosting_nginx` within `web_server`, but the code will have no changes. I will work on this at https://github.com/omega8cc/hosting_le for now.

**Comment by jonpugh** [comment]
As of opendevshop/devmaster#67, DevShop now includes Aegir HTTPS with LetsEncrypt support!

Install 1.x version of devshop to use. Release coming soon.
