### ISSUE TITLE
Build based on make-file repos

### ISSUE THREAD

**Issue by lsolesen** [opendevshop/devshop#113]
I cannot find any docs on building off a repo based on make-files instead of the entire Drupal installation. 

Usually I've been building manually from repos like this: https://github.com/motionsplan/motionsplan.dk

Where can I find docs on a workflow with devshop?

**Comment by jonpugh** [comment]
We need help building a tool for handing this. It's probably been the #1 support request from the beginning, it's just a big, nuanced technical challenge to do it "right".

DevShop currently only deploys git repos with full drupal stacks in them.  My view is that there are benefits to having all of your source code in a  single git repository (even if it is a second repo, built from the makefile version) for a few reasons: You can tell if any files were modified, you can run tests guaranteeing exact versions of your dependencies, you can do code review with a full diff of the entire stack, not just of your makefiles.

There are many, many people that need this exact workflow: basically anybody with a distribution. Specifically I've worked with @acouch, @dafeder, and @drkloc on https://github.com/nucivic/dkan, and @bleen and the team at NBCU are also wrestling with this problem, but I don't know if it's ever been elegantly solved for all use cases.

So, I think the solution here is a simple makefile > git repo build tool. This could be built into aegir itself, and combined with a special webhook, builds could be triggered automatically upon pushes to the "makefile repo".

Here's the steps we would need for something like this.

1. Developer `git push` to "project-makefile" repo.
2. "project-makefile" repo sends a webook to aegir.
3. Aegir runs a "build platform in git" task, which would run the drush make over an existing clone of the "project-build" repo.
4. Upon completion, `git add -A`, `git commit`, push to the "project-build" repo
5. "project-build" repo sends a webhook to aegir/devshop which would deploy to the right environment.

I'm thinking we could build this right into the "hosting_git" modules perhaps? leverage Platforms and Platform tasks for this?

As you can see from this, it's not simple, but perhaps we can get the ball rolling?

**Comment by arttus** [comment]
Pretty sure BOA does it out of the box, maybe there is some code to leverage there.

**Comment by jonpugh** [comment]
@arttus That's true, but BOA does not automate deploying new platforms.

We've made massive progress in the `makefiles` branch.  On new git commit detection, we build an entirely new platform and attempt to run a Migrate task to it, fully automated.

Tests locally pass, but there is a very strange anomaly preventing them from passing in Travis.ci:  the makefile property is missing on platform contexts.

Stand by, I hope to have this feature completed by DrupalGovCon July 31st.

**Comment by jonpugh** [comment]
Here's the PR: devmaster/pull/70

**Comment by jonpugh** [comment]
The branch in that PR is epic.
I'm postponing this to at least RC2. It's just to big a lift to get exactly right. It depends on Migrate tasks. Which will fail and rollback, and we don't yet know how to override that and allow it to fail and remain on the new platform.

We will revisit this, but most of the work will likely go in hosting_git.

**Comment by jonpugh** [comment]
No more makefiles, really.

Too much work.
