### ISSUE TITLE
ERROR! the role 'opendevshop.aegir-user'  was not found.

### ISSUE THREAD

**Issue by discipolo** [opendevshop/devshop#114]
to get the local development setup working I had to run following command before vagrant up

ansible-galaxy install -r roles.yml -p roles

should this go into the docu or should this be run during vagrant provisioning somewhere?

**Comment by jonpugh** [comment]
Ahh, good catch... 

Yes,  I'd prefer to add to the Vagrantfile so users don't have to think about it.

**Comment by jonpugh** [comment]
Ok, we should add this to `vagrant-prepare-guest.sh`, because that's the point of the file ;)

**Comment by jonpugh** [comment]
@discipolo got pull and try again?

**Comment by discipolo** [comment]
on cloning provision it complains about no matching key exchange method found. Their offer: diffie-hellman-group1-sha1

then  after Please make sure you have the correct access rights
and the repository exists.
 [ERROR]: Unable to open roles.yml: [Errno 2] No such file or directory:
'roles.yml'


Then however it continues cloning opendevshop.aegir-user and other roles.. and fails

will verify on second machine

**Comment by discipolo** [comment]
i assume the problem may be the leftover solr submodule?

**Comment by jonpugh** [comment]
Arggg yes you are right, @discipolo ...
