### ISSUE TITLE
Error when running install script

### ISSUE THREAD

**Issue by magick93** [opendevshop/devshop#118]
Hi

I am trying to install on Ubuntu 16.04, but am getting the following error.

```
TASK [opendevshop.aegir-apache : Install Apache2 PHP Mod.] *********************
fatal: [Charles]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'libapache2-mod-php5' is available"}

RUNNING HANDLER [geerlingguy.apache : restart apache] **************************

PLAY RECAP *********************************************************************
Charles                    : ok=33   changed=10   unreachable=0    failed=1   

-su: devshop: command not found
The command 'devshop status' had an error. Check the logs and try again.
```

This lib does not seem to be available in apt-get.

Any help is appreciated.

**Comment by jonpugh** [comment]
If you are missing libapache2-mod-php5 I have a feeling you are using Ubuntu 16?

Please use Ubuntu 14.04 for now... I will start a PR to add ubuntu 16 testing.

**Comment by magick93** [comment]
Thanks Jon

And I have just upgraded from Ubuntu 14.04.

I think I'll wait for your PR. Will be happy to test it.

BTW - it there were multiple copies of this issue submitted, my apologies.
Github seems to be having some problems currently, and it so I reposted.

**Comment by jonpugh** [comment]
I noticed that!  I was getting 404s when clicking the link to your issue...

**Comment by jonpugh** [comment]
Can you confirm that you were using ubuntu 16?

**Comment by magick93** [comment]
On Mon, May 23, 2016 at 6:17 PM, Jon Pugh <notifications@github.com> wrote:

> Can you confirm that you were using ubuntu 16?
>
Confirmed.

Related: Do you have a docker image of DevShop?

**Comment by jonpugh** [comment]
Please see #120 for Ubuntu 16 support development.

Thanks!

P.S. No docker image yet, @magick93 but we do have some scripts in the repo that build a container. There's a lot of variables the system needs so creating a common image is a challenge. We'll get there!
