### ISSUE TITLE
Vagrant box becomes overwhelmed, stops responding

### ISSUE THREAD

**Issue by aaronbauman** [opendevshop/devshop#12]
After spinning up a new instance of devshop, my VM is more or less locked up.
Here's a sample from `ps`, in which you can see none of the dozen hosting-dispatch tasks has completed:
![devshop_ _vagrant_devshop___var_aegir_devmaster-0_x_sites_devshop_local_ _ssh_ _185x52](https://cloud.githubusercontent.com/assets/508451/7989017/b4a061d0-0ab4-11e5-9f59-aebd2b744c6f.png)

What should i do?

**Comment by jonpugh** [comment]
Not sure what happened to you.  Please try the latest code again.
