### ISSUE TITLE
Fresh installation (1.0.0-beta3) fails on TASK [geerlingguy.mysql : Get list of hosts for the anonymous user.] ***********

### ISSUE THREAD

**Issue by madalinignisca** [opendevshop/devshop#122]
I'm trying a fresh installation of Open DevShop and once it reaches this task
`TASK [geerlingguy.mysql : Get list of hosts for the anonymous user.] ***********`
it fails with the error:
`fatal: [opendevshop.drupalcloud.local]: FAILED! => {"changed": false, "cmd": ["mysql", "-NBe", "SELECT Host FROM mysql.user WHERE User = \"\""], "delta": "0:00:00.005953", "end": "2016-06-02 16:20:45.529707", "failed": true, "rc": 1, "start": "2016-06-02 16:20:45.523754", "stderr": "ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)", "stdout": "", "stdout_lines": [], "warnings": []}`

So I guess it tries to connect to MySQL with user _root_ and no password.

Right before this task I see that it passed the following related:
`TASK [geerlingguy.mysql : Update MySQL root password for localhost root account.] ***`
`TASK [geerlingguy.mysql : Copy .my.cnf file with root password credentials.] ***`

I've been using a fresh vagrant box, `ubuntu/trusty32`.

I found that the installation works only if you are `root`, but as a `sudoer` it fails.

[screenshot](https://drive.google.com/file/d/0B_OYzlm3RXZCX0w1TjBtbEhhQ3M/view?usp=sharing)

It might be simpler in the docs to say **become root** to make sure all goes well out of the box.

**Comment by jonpugh** [comment]
Hmm, the docs actually used to say that. I thought it was working with sudo again.

I'll have to test this out.

**Comment by adrinux** [comment]
I hit this issue to, installing in an ubuntu 14.04 lxc container, just tried with sudo's -H flag and its gone pass this error.
```
sudo -H bash install.sh
```
Of course it may be just as simple to switch to root first with sudo su or whatever.

**Comment by drupalicus** [comment]
Ahhh this is the last error I got when I was trying to install devshop in AWS ubuntu 14.04.
Yeap, if the install.sh is runned in sudo, it will stop right there in the "TASK [geerlingguy.mysql : Get list of hosts for the anonymous user.]"

I runned in root and everything worked nicely. I am happy

**Comment by jonpugh** [comment]
Glad you are happy, @drupalicus :)

We've updated the docs to ensure it is clear:  Run as root!
