### ISSUE TITLE
Fresh installation, new project fails on a successful command

### ISSUE THREAD

**Issue by madalinignisca** [opendevshop/devshop#124]
this command:
`/usr/bin/php /usr/local/share/drush/drush.php --php=/usr/bin/php --backend=2 --root=/var/aegir/projects/d8c/dev/web --uri= provision-save '@platform_d8c_dev' 2>&1`

is interpreted as failing:
`The command could not be executed successfully (returned: Changed permissions of [1;32;40m[1m[success][0m /var/aegir/.drush/platform_d8c_dev.alias.drushrc.php to 640 Generated config in write(): Drush configuration file [1;32;40m[1m[success][0m (/var/aegir/.drush/platform_d8c_dev.alias.drushrc.php) Changed permissions of [1;32;40m[1m[success][0m /var/aegir/.drush/platform_d8c_dev.alias.drushrc.php to 440 , code: 0)`

although it is passing fine

I have a fresh installation on ubuntu 14.04, from commit 3d9b91f

**Comment by jonpugh** [comment]
Not sure what your problem was, but I can't replicate. 
There may have been something bad in your codebase.
Feel free to reopen if you are still having trouble.
