### ISSUE TITLE
sites/default/settings.php not found

### ISSUE THREAD

**Issue by madalinignisca** [opendevshop/devshop#125]
Hi. In the documentation there's the mention that

> Be aware that the sites/default/settings.php file is not used at all.

While if trying to setup a project that doesn't has one the following errors are triggered:

`Could not find a Drupal settings.php file at sites/default/settings.php.`
and
`The drush command 'provision-verfiy' could not be found.  Run`drush cache-clear drush`to clear the commandfile cache if you have installed new extensions.`

So the `drush provision-verify` requires to have to do the verification step for an environment the file present there (not really what it would be desidered).

**Comment by adrinux** [comment]
I just ran into this.
Created a live environment whilst setting up project - worked fine.
Added a stage environment to that project, install failed with the error about sites/default/settings.php.
Added a dev environment to same project, install also failed with same error.

(In retrospect this is probably the wrong approach anyway and I should probably clone or fork the live environment to stage and dev?)

**Comment by adrinux** [comment]
**Note** 
When this occurs and the site install fails the entry for the site name in the hosting_context table is not removed. Later attempts to reuse the same site name then result in a PDO error 'Integrity constraint violation' because of the duplicate key.

**Comment by jonpugh** [comment]
Closing. Please reopen if issue reoccurs.

**Comment by jonpugh** [comment]
This is something I see pop up with Aegir itself. I still don't know where it comes from.

If you are still dealing with this, feel free to re-open if you encounter again.
