### ISSUE TITLE
How can I change the git remote repo for a project?

### ISSUE THREAD

**Issue by madalinignisca** [opendevshop/devshop#126]
I can't find a way in the interface to change the git remote repo. It's not a problem going on the CLI and changing manually for current environments, but it would be a great start to have the option to change the default repo in the interface.

**Comment by jonpugh** [comment]
We can do this now. Devshop now uses Hosting Git to deploy environments.

I'd like to add a setting: "Allow environments to change Git URL."

**Comment by jonpugh** [comment]
This was done some time ago. You can now edit the "Default Git Repository URL" in the Project Settings form.
