### ISSUE TITLE
Github Pull Requests from forked repos fail

### ISSUE THREAD

**Issue by madalinignisca** [opendevshop/devshop#127]
When a user working on a forked repo sends a pull request to the main repo, Devshop gets the expected webhook request, but it can't find the branch in the repo (normally), as it tries that on the main repo.

In the webhook, there is also the uri for the repo that is making the pull request and it should be used to create the new environment.

**Comment by jonpugh** [comment]
Thanks for reporting this.

It shouldn't be too hard to fix now that we're using hosting_git module: we can simply create a platform using the other Git URL.  I'll try to get this in the next release, but it might have to wait until the next one. There's a lot in the backlog.

**Comment by jonpugh** [comment]
This is a serious bug.

Let's fix soon.

**Comment by jonpugh** [comment]
This should be fully fixed in the big PR branch we have going for github queues. Stand by for merge of that. See https://github.com/opendevshop/devshop/pull/384

**Comment by jonpugh** [comment]
An attempt at fixing was made in #a8e38de01a95fba3ea76b7515ad6f4d415b78e07.

I found a typo however! Fixing now.
