### ISSUE TITLE
Cloned environment fails to finish deployment

### ISSUE THREAD

**Issue by madalinignisca** [opendevshop/devshop#130]
Fresh project, first one dev environment. Hitting the clone option, fails on deploy task and shows that the it is not a git repo...

![screen shot 2016-06-10 at 14 07 48](https://cloud.githubusercontent.com/assets/619561/15965315/fff64a0c-2f14-11e6-850a-e48374b70eb5.png)

**Comment by madalinignisca** [comment]
Why do I get using the main admin account Access denied if I try to edit a task (content) to see what is set in it that might trigger failure?

**Comment by jonpugh** [comment]
Tasks are not editable, that is part of hosting_task.module.

The "task arguments" display and the "current working directory" output are telling you some things.

The Current working directory should not be empty.  

Try Editing your project settings form. On save it runs a "verify project" task.  I think that might be the issue.

Please let me know if that works.

**Comment by madalinignisca** [comment]
This happens for a cloned environment.

The project's settings are 100% ok, any new normal environment works well.

This happens on devshop from master.

On Devshop 1.0.3-beta3 works ok. Exact same scenario.

**Comment by jonpugh** [comment]
Cloning has been fully refactored to use the new "install_method" property of Aegir sites.

Can you give the latest 1.x a try and let me know if it works?

Thanks!

**Comment by jonpugh** [comment]
Cloning and Syncing Data have been the thorniest problems in devshop/aegir.  I really should add some behat steps to test cloning a site and syncing a site.
