### ISSUE TITLE
attributes.json

### ISSUE THREAD

**Issue by theodorosploumis** [opendevshop/devshop#14]
What is this file for? In the **Vagrantfile** there is on line 6:

[PATH_TO_ATTRIBUTES = File.dirname(__FILE__) + "/attributes.json](https://github.com/opendevshop/devshop/blob/0.x/Vagrantfile#L6)

but no file exists somewhere or even the documentation about it.

**Comment by jonpugh** [comment]
Hi, @theodorosploumis!

That line can be removed.  We switched to the vars.yml file a ways back and we must have just forgotten to remove that line.

Thanks for the heads up!
