### ISSUE TITLE
Using docker

### ISSUE THREAD

**Issue by magick93** [opendevshop/devshop#142]
Hello

Im trying to using the docker image on https://hub.docker.com/r/devshop/devmaster/ along with docker-compose file.

Question: what is the url I use to access devshop once I have run the docker-compose file? I have added `127.0.0.1	devmaster.local.computer` to my host file. But browsing to this does not bring up anything. Am I doing something wrong?

**Comment by jonpugh** [comment]
Is your docker-machine running at 127.0.0.1?  

It will only be available at that IP if you are using linux with docker installed natively, or if you are using a recent Docker for Mac beta. 

You don't need to edit your hosts file unless it is not available at 127.0.0.1, as local.computer and *.local.computer all resolve to 127.0.0.1

**Comment by jonpugh** [comment]
Please re-open if you have further issues.
