### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in devshop_projects_init() (line 45...

### ISSUE THREAD

**Issue by arttus** [opendevshop/devshop#145]
Noticed this in the logs, fresh install as of last night.

Warning: Invalid argument supplied for foreach() in devshop_projects_init() (line 45 of /var/aegir/devmaster-1.x/profiles/devmaster/modules/devshop/devshop_projects/devshop_projects.module).

**Comment by jonpugh** [comment]
I believe I fixed this in https://github.com/opendevshop/devmaster/commit/5e623ea4e3050589265e8a233bba6f471c7e22a0
