### ISSUE TITLE
Errors when running vagrant

### ISSUE THREAD

**Issue by magick93** [opendevshop/devshop#146]
Hello

I am trying to get devshop running. I was unsuccessful when trying to use vagrant. Below is the output when attempting:

> $ vagrant up
Bringing machine 'devmaster' up with 'virtualbox' provider...
==> devmaster: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    devmaster: Box Provider: virtualbox
    devmaster: Box Version: >= 0
==> devmaster: Loading metadata for box 'ubuntu/trusty64'
    devmaster: URL: https://atlas.hashicorp.com/ubuntu/trusty64
==> devmaster: Adding box 'ubuntu/trusty64' (v20160826.0.1) for provider: virtualbox
    devmaster: Downloading: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20160826.0.1/providers/virtualbox.box
==> devmaster: Successfully added box 'ubuntu/trusty64' (v20160826.0.1) for 'virtualbox'!
==> devmaster: Importing base box 'ubuntu/trusty64'...
==> devmaster: Matching MAC address for NAT networking...
==> devmaster: Checking if box 'ubuntu/trusty64' is up to date...
==> devmaster: Setting the name of the VM: devshop_devmaster_1472981636288_53526
==> devmaster: Clearing any previously set forwarded ports...
==> devmaster: Clearing any previously set network interfaces...
==> devmaster: Preparing network interfaces based on configuration...
    devmaster: Adapter 1: nat
    devmaster: Adapter 2: hostonly
==> devmaster: Forwarding ports...
    devmaster: 22 => 2222 (adapter 1)
==> devmaster: Running 'pre-boot' VM customizations...
==> devmaster: Booting VM...
==> devmaster: Waiting for machine to boot. This may take a few minutes...
    devmaster: SSH address: 127.0.0.1:2222
    devmaster: SSH username: vagrant
    devmaster: SSH auth method: private key
    devmaster: Warning: Connection timeout. Retrying...
    devmaster: Warning: Remote connection disconnect. Retrying...
    devmaster: 
    devmaster: Vagrant insecure key detected. Vagrant will automatically replace
    devmaster: this with a newly generated keypair for better security.
    devmaster: 
    devmaster: Inserting generated public key within guest...
    devmaster: Removing insecure key from the guest if it's present...
    devmaster: Key inserted! Disconnecting and reconnecting using new SSH key...
==> devmaster: Machine booted and ready!
==> devmaster: Checking for guest additions in VM...
    devmaster: The guest additions on this VM do not match the installed version of
    devmaster: VirtualBox! In most cases this is fine, but in rare cases it can
    devmaster: prevent things such as shared folders from working properly. If you see
    devmaster: shared folder errors, please make sure the guest additions within the
    devmaster: virtual machine match the version of VirtualBox you have installed on
    devmaster: your host and reload your VM.
    devmaster: 
    devmaster: Guest Additions Version: 4.3.36
    devmaster: VirtualBox Version: 5.0
==> devmaster: Setting hostname...
==> devmaster: Configuring and enabling network interfaces...
==> devmaster: Mounting shared folders...
    devmaster: /vagrant => /home/anton/git/hughestech/shiftwork/drupal/devshop
==> devmaster: Running provisioner: shell...
    devmaster: Running: /tmp/vagrant-shell20160904-9659-xv1h4c.sh
==> devmaster: stdin: is not a tty
==> devmaster: =============================================
==> devmaster:  Welcome to the DevShop Standalone Installer 
==> devmaster:                    v 1.x        
==> devmaster: =============================================
==> devmaster:  OS: ubuntu
==> devmaster:  Version: 14.04
==> devmaster:  Hostname: local.devshop.site
==> devmaster:  Web Server: nginx
==> devmaster: ---------------------------------------------
==> devmaster:  Installing Ansible...
==> devmaster: deb http://ppa.launchpad.net/nginx/stable/ubuntu trusty main
==> devmaster: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.XkDojszI0d --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com --recv-keys C300EE8C
==> devmaster: gpg: 
==> devmaster: requesting key C300EE8C from hkp server keyserver.ubuntu.com
==> devmaster: gpg: 
==> devmaster: key C300EE8C: public key "Launchpad Stable" imported
==> devmaster: gpg: Total number processed: 1
==> devmaster: gpg:               imported: 1  (RSA: 1)
==> devmaster: gpg: 
==> devmaster: keyring `/tmp/tmpo30tmwdq/secring.gpg' created
==> devmaster: gpg: 
==> devmaster: keyring `/tmp/tmpo30tmwdq/pubring.gpg' created
==> devmaster: gpg: 
==> devmaster: requesting key 7BB9C367 from hkp server keyserver.ubuntu.com
==> devmaster: gpg: 
==> devmaster: /tmp/tmpo30tmwdq/trustdb.gpg: trustdb created
==> devmaster: gpg: 
==> devmaster: key 7BB9C367: public key "Launchpad PPA for Ansible, Inc." imported
==> devmaster: gpg: 
==> devmaster: Total number processed: 1
==> devmaster: gpg:               imported: 1  (RSA: 1)
==> devmaster: OK
==> devmaster: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> devmaster: Selecting previously unselected package python-markupsafe.
==> devmaster: (Reading database ... 62998 files and directories currently installed.)
==> devmaster: Preparing to unpack .../python-markupsafe_0.18-1build2_amd64.deb ...
==> devmaster: Unpacking python-markupsafe (0.18-1build2) ...
==> devmaster: Selecting previously unselected package python-jinja2.
==> devmaster: Preparing to unpack .../python-jinja2_2.7.2-2_all.deb ...
==> devmaster: Unpacking python-jinja2 (2.7.2-2) ...
==> devmaster: Selecting previously unselected package python-paramiko.
==> devmaster: Preparing to unpack .../python-paramiko_1.10.1-1git1build1_all.deb ...
==> devmaster: Unpacking python-paramiko (1.10.1-1git1build1) ...
==> devmaster: Selecting previously unselected package python-setuptools.
==> devmaster: Preparing to unpack .../python-setuptools_3.3-1ubuntu2_all.deb ...
==> devmaster: Unpacking python-setuptools (3.3-1ubuntu2) ...
==> devmaster: Selecting previously unselected package sshpass.
==> devmaster: Preparing to unpack .../sshpass_1.05-1_amd64.deb ...
==> devmaster: Unpacking sshpass (1.05-1) ...
==> devmaster: Selecting previously unselected package ansible.
==> devmaster: Preparing to unpack .../ansible_2.1.1.0-1ppa~trusty_all.deb ...
==> devmaster: Unpacking ansible (2.1.1.0-1ppa~trusty) ...
==> devmaster: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> devmaster: Setting up python-markupsafe (0.18-1build2) ...
==> devmaster: Setting up python-jinja2 (2.7.2-2) ...
==> devmaster: Setting up python-paramiko (1.10.1-1git1build1) ...
==> devmaster: Setting up python-setuptools (3.3-1ubuntu2) ...
==> devmaster: Setting up sshpass (1.05-1) ...
==> devmaster: Setting up ansible (2.1.1.0-1ppa~trusty) ...
==> devmaster: ---------------------------------------------
==> devmaster: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> devmaster: Selecting previously unselected package liberror-perl.
==> devmaster: (Reading database ... 64344 files and directories currently installed.)
==> devmaster: Preparing to unpack .../liberror-perl_0.17-1.1_all.deb ...
==> devmaster: Unpacking liberror-perl (0.17-1.1) ...
==> devmaster: Selecting previously unselected package git-man.
==> devmaster: Preparing to unpack .../git-man_1%3a1.9.1-1ubuntu0.3_all.deb ...
==> devmaster: Unpacking git-man (1:1.9.1-1ubuntu0.3) ...
==> devmaster: Selecting previously unselected package git.
==> devmaster: Preparing to unpack .../git_1%3a1.9.1-1ubuntu0.3_amd64.deb ...
==> devmaster: Unpacking git (1:1.9.1-1ubuntu0.3) ...
==> devmaster: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> devmaster: Setting up liberror-perl (0.17-1.1) ...
==> devmaster: Setting up git-man (1:1.9.1-1ubuntu0.3) ...
==> devmaster: Setting up git (1:1.9.1-1ubuntu0.3) ...
==> devmaster:  Generating new MySQL root password... YZFY-QceLYz9_3zyVOPHwFgUBE0mHaee
==> devmaster: ---------------------------------------------
==> devmaster:  Hostname: local.devshop.site
==> devmaster:  MySQL Root Password: YZFY-QceLYz9_3zyVOPHwFgUBE0mHaee
==> devmaster: ---------------------------------------------
==> devmaster:  Playbook: /vagrant/playbook.yml 
==> devmaster:  Makefile: /usr/share/devshop/build-devmaster.make 
==> devmaster: ---------------------------------------------
==> devmaster: Inventory file found.
==> devmaster:  Installing ansible roles...
==> devmaster: - downloading role 'php', owned by geerlingguy
==> devmaster: - downloading role from https://github.com/geerlingguy/ansible-role-php/archive/2.0.3.tar.gz
==> devmaster: - extracting geerlingguy.php to /etc/ansible/roles/geerlingguy.php
==> devmaster: - geerlingguy.php was installed successfully
==> devmaster: - downloading role 'mysql', owned by geerlingguy
==> devmaster: - downloading role from https://github.com/geerlingguy/ansible-role-mysql/archive/2.3.0.tar.gz
==> devmaster: - extracting geerlingguy.mysql to /etc/ansible/roles/geerlingguy.mysql
==> devmaster: - geerlingguy.mysql was installed successfully
==> devmaster: - downloading role 'php-mysql', owned by geerlingguy
==> devmaster: - downloading role from https://github.com/geerlingguy/ansible-role-php-mysql/archive/1.2.0.tar.gz
==> devmaster: - extracting geerlingguy.php-mysql to /etc/ansible/roles/geerlingguy.php-mysql
==> devmaster: - geerlingguy.php-mysql was installed successfully
==> devmaster: - dependency geerlingguy.php already pending installation.
==> devmaster: - downloading role 'aegir-user', owned by opendevshop
==> devmaster: - downloading role from https://github.com/opendevshop/ansible-role-aegir-user/archive/1.0.0.tar.gz
==> devmaster: - extracting opendevshop.aegir-user to /etc/ansible/roles/opendevshop.aegir-user
==> devmaster: - opendevshop.aegir-user was installed successfully
==> devmaster: - downloading role 'aegir-apache', owned by opendevshop
==> devmaster: - downloading role from https://github.com/opendevshop/ansible-role-aegir-apache/archive/1.0.1.tar.gz
==> devmaster: - extracting opendevshop.aegir-apache to /etc/ansible/roles/opendevshop.aegir-apache
==> devmaster: - opendevshop.aegir-apache was installed successfully
==> devmaster: - dependency opendevshop.aegir-user already pending installation.
==> devmaster: - adding dependency: geerlingguy.git
==> devmaster: - adding dependency: geerlingguy.apache
==> devmaster: - downloading role 'aegir-nginx', owned by opendevshop
==> devmaster: - downloading role from https://github.com/opendevshop/ansible-role-aegir-nginx/archive/1.0.4.tar.gz
==> devmaster: - extracting opendevshop.aegir-nginx to /etc/ansible/roles/opendevshop.aegir-nginx
==> devmaster: - opendevshop.aegir-nginx was installed successfully
==> devmaster: - dependency opendevshop.aegir-user already pending installation.
==> devmaster: - dependency geerlingguy.git already pending installation.
==> devmaster: - adding dependency: geerlingguy.nginx
==> devmaster: - dependency geerlingguy.mysql already pending installation.
==> devmaster: - dependency geerlingguy.php already pending installation.
==> devmaster: - dependency geerlingguy.php-mysql already pending installation.
==> devmaster: - adding dependency: geerlingguy.composer
==> devmaster: - downloading role 'devmaster', owned by opendevshop
==> devmaster: - downloading role from https://github.com/opendevshop/ansible-role-devmaster/archive/1.1.6.tar.gz
==> devmaster: - extracting opendevshop.devmaster to /etc/ansible/roles/opendevshop.devmaster
==> devmaster: - opendevshop.devmaster was installed successfully
==> devmaster: - dependency opendevshop.aegir-user already pending installation.
==> devmaster: - dependency geerlingguy.mysql already pending installation.
==> devmaster: - dependency geerlingguy.git already pending installation.
==> devmaster: - dependency geerlingguy.composer already pending installation.
==> devmaster: - downloading role 'git', owned by geerlingguy
==> devmaster: - downloading role from https://github.com/geerlingguy/ansible-role-git/archive/1.1.1.tar.gz
==> devmaster: - extracting geerlingguy.git to /etc/ansible/roles/geerlingguy.git
==> devmaster: - geerlingguy.git was installed successfully
==> devmaster: - downloading role 'apache', owned by geerlingguy
==> devmaster: - downloading role from https://github.com/geerlingguy/ansible-role-apache/archive/1.7.3.tar.gz
==> devmaster: - extracting geerlingguy.apache to /etc/ansible/roles/geerlingguy.apache
==> devmaster: - geerlingguy.apache was installed successfully
==> devmaster: - downloading role 'nginx', owned by geerlingguy
==> devmaster: - downloading role from https://github.com/geerlingguy/ansible-role-nginx/archive/1.9.3.tar.gz
==> devmaster: - extracting geerlingguy.nginx to /etc/ansible/roles/geerlingguy.nginx
==> devmaster: - geerlingguy.nginx was installed successfully
==> devmaster: - downloading role 'composer', owned by geerlingguy
==> devmaster: - downloading role from https://github.com/geerlingguy/ansible-role-composer/archive/1.4.2.tar.gz
==> devmaster: - extracting geerlingguy.composer to /etc/ansible/roles/geerlingguy.composer
==> devmaster: - geerlingguy.composer was installed successfully
==> devmaster: ---------------------------------------------
==> devmaster:  Installing with Ansible...
==> devmaster: ---------------------------------------------
==> devmaster: 
==> devmaster: PLAY [all] *********************************************************************
==> devmaster: 
==> devmaster: TASK [setup] *******************************************************************
==> devmaster: ok: [devshop.docker]
==> devmaster: 
==> devmaster: TASK [opendevshop.aegir-user : Include OS-specific variables.] *****************
==> devmaster: ok: [devshop.docker]
==> devmaster: 
==> devmaster: TASK [opendevshop.aegir-user : Create Aegir Group (so we can set the GID)] *****
==> devmaster: fatal: [devshop.docker]: FAILED! => {"changed": false, "failed": true, "msg": "groupadd: GID '1000' already exists\n", "name": "aegir"}
==> devmaster: 
==> devmaster: NO MORE HOSTS LEFT *************************************************************
==> devmaster:  [WARNING]: Could not create retry file 'playbook-nginx.retry'.         [Errno
==> devmaster: 2] No such file or directory: ''
==> devmaster: 
==> devmaster: PLAY RECAP *********************************************************************
==> devmaster: devshop.docker             : ok=2    changed=0    unreachable=0    failed=1   
==> devmaster: No passwd entry for user 'aegir'
==> devmaster: The command 'devshop status' had an error. Check the logs and try again.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by jonpugh** [comment]
Hello,
We have deprecated the Vagrant setup, but I have kept it in the repo and tested it to make sure it still works.

Can you test out the branch with the updated vagrant?

```
git clone https://github.com/opendevshop/devshop --branch deprecate-vagrant
cd devshop/vagrant
vagrant up
```

Please let us know if that works, and if so close this issue.

Thanks!

**Comment by jonpugh** [comment]
Please re-open if you have further issues.

**Comment by ryantan** [comment]
For posterity, the message below means a user already existing in your system has the same id aegir is trying to add. 

FAILED! => {"changed": false, "failed": true, "msg": "groupadd: GID '1000' already exists\n", "name": "aegir"}

One solution is to change that user's and group's id by doing:

sudo usermod -u [new id] [the user name]
sudo groupmod -g [new id] [the group name]

Make sure you know what you're doing too.
