### ISSUE TITLE
Errors when running docker-compose

### ISSUE THREAD

**Issue by magick93** [opendevshop/devshop#147]
Hello

I'm trying to run devshop using docker-compose, but ran into errors. Below is the output:

> $ docker-compose up
Starting devshop_database_1
Starting devshop_devmaster_1
Attaching to devshop_database_1, devshop_devmaster_1
database_1   | WARNING: no logs are available with the 'none' log driver
devmaster_1  | waiting for mysql ...
devmaster_1  | =========================
devmaster_1  | Hostname: devshop.local.computer
devmaster_1  | Makefile: https://raw.githubusercontent.com/opendevshop/devshop/1.x/build-devmaster.make
devmaster_1  | Client Name: admin
devmaster_1  | Client Email: aegir@aegir.docker
devmaster_1  | -------------------------
devmaster_1  | Installing provision...
devmaster_1  | Install location /var/aegir/.drush/provision already exists. Do you want to overwrite it? (y/n): y
devmaster_1  | Project provision (7.x-3.7) downloaded to                              [success]
devmaster_1  | /var/aegir/.drush/provision.
devmaster_1  | Project provision contains 4 modules: bind, bind_slave, dns, provision.
devmaster_1  | 'drush' cache was cleared.                                             [success]
devmaster_1  | -------------------------
devmaster_1  | Running: drush hostmaster-install
devmaster_1  | Aegir docker automated install script
devmaster_1  | ==============================================================================
devmaster_1  | Some settings have not been provided and will now be prompted.
devmaster_1  | Don't worry: you will get to review those settings after the final install
devmaster_1  | 
devmaster_1  | This script will operate the following changes in your system:
devmaster_1  | 
devmaster_1  | 1. Create server-level configuration directories
devmaster_1  | 2. Create the Hostmaster frontend platform
devmaster_1  | 3. Install the frontend site
devmaster_1  | 4. Setup the dispatcher (a user cron job)
devmaster_1  | 
devmaster_1  | We are making the following assumptions:
devmaster_1  |  * you have read and are following the install instructions at:
devmaster_1  |     http://docs.aegirproject.org/en/3.x/install/
devmaster_1  |  * the FQDN of this machine is valid and resolves
devmaster_1  |  * you are executing this script as your "aegir" user
devmaster_1  | 
devmaster_1  | The following settings will be used:
devmaster_1  |  Aegir frontend URL: devshop.local.computer
devmaster_1  |  Master server FQDN: devshop.local.computer
devmaster_1  |  Aegir root: /var/aegir
devmaster_1  |  Aegir user: aegir
devmaster_1  |  Web group: www-data
devmaster_1  |  Web server: apache
devmaster_1  |  Web server port: 80
devmaster_1  |  Aegir DB host: database
devmaster_1  |  Aegir DB user: root
devmaster_1  |  Aegir DB password: <previously set>
devmaster_1  |  Aegir DB port: 3306
devmaster_1  |  Aegir version: docker
devmaster_1  |  Aegir platform path: /var/aegir/devmaster-docker
devmaster_1  |  Admin email: aegir@aegir.docker
devmaster_1  |  Aegir makefile: https://raw.githubusercontent.com/opendevshop/devshop/1.x/build-devmaster.make
devmaster_1  | 
devmaster_1  |  Aegir install profile: devmaster
devmaster_1  | 
devmaster_1  | Do you really want to proceed with the install (y/n): y
devmaster_1  | Changed permissions of                                                 [success]
devmaster_1  | /var/aegir/.drush/server_database.alias.drushrc.php to 640
devmaster_1  | Generated config in write(): Drush configuration file                  [success]
devmaster_1  | (/var/aegir/.drush/server_database.alias.drushrc.php)
devmaster_1  | Changed permissions of                                                 [success]
devmaster_1  | /var/aegir/.drush/server_database.alias.drushrc.php to 440
devmaster_1  | Provision configuration root path /var/aegir/config exists.            [success]
devmaster_1  | Provision configuration root ownership of /var/aegir/config has been   [success]
devmaster_1  | changed to aegir.
devmaster_1  | Provision configuration root permissions of /var/aegir/config have     [success]
devmaster_1  | been changed to 711.
devmaster_1  | Provision configuration root path /var/aegir/config is writable.       [success]
devmaster_1  | Provision configuration path /var/aegir/config/server_database         [success]
devmaster_1  | exists.
devmaster_1  | Provision configuration ownership of                                   [success]
devmaster_1  | /var/aegir/config/server_database has been changed to aegir.
devmaster_1  | Provision configuration permissions of                                 [success]
devmaster_1  | /var/aegir/config/server_database have been changed to 711.
devmaster_1  | Provision configuration path /var/aegir/config/server_database is      [success]
devmaster_1  | writable.
devmaster_1  | Provision client home path /var/aegir/clients exists.                  [success]
devmaster_1  | Provision client home ownership of /var/aegir/clients has been         [success]
devmaster_1  | changed to aegir.
devmaster_1  | Provision client home permissions of /var/aegir/clients have been      [success]
devmaster_1  | changed to 711.
devmaster_1  | Provision client home path /var/aegir/clients is writable.             [success]
devmaster_1  | Changed permissions of                                                 [success]
devmaster_1  | /var/aegir/.drush/server_database.alias.drushrc.php to 640
devmaster_1  | Generated config in write(): Drush configuration file                  [success]
devmaster_1  | (/var/aegir/.drush/server_database.alias.drushrc.php)
devmaster_1  | Changed permissions of                                                 [success]
devmaster_1  | /var/aegir/.drush/server_database.alias.drushrc.php to 440
devmaster_1  | Provision can create new databases.                                    [success]
devmaster_1  | Provision can grant privileges on database users.                      [success]
devmaster_1  | Multi-byte UTF-8 for Drupal 7 is not supported on your system. See     [warning]
devmaster_1  | the <a href="https://www.drupal.org/node/2754539">documentation on
devmaster_1  | adding 4 byte UTF-8 support</a> for more information.
devmaster_1  | Changed permissions of                                                 [success]
devmaster_1  | /var/aegir/.drush/server_master.alias.drushrc.php to 640
devmaster_1  | Generated config in write(): Drush configuration file                  [success]
devmaster_1  | (/var/aegir/.drush/server_master.alias.drushrc.php)
devmaster_1  | Changed permissions of                                                 [success]
devmaster_1  | /var/aegir/.drush/server_master.alias.drushrc.php to 440
devmaster_1  | Provision configuration root path /var/aegir/config exists.            [success]
devmaster_1  | Provision configuration root ownership of /var/aegir/config has been   [success]
devmaster_1  | changed to aegir.
devmaster_1  | Provision configuration root permissions of /var/aegir/config have     [success]
devmaster_1  | been changed to 711.
devmaster_1  | Provision configuration root path /var/aegir/config is writable.       [success]
devmaster_1  | Provision configuration path /var/aegir/config/server_master exists.   [success]
devmaster_1  | Provision configuration ownership of /var/aegir/config/server_master   [success]
devmaster_1  | has been changed to aegir.
devmaster_1  | Provision configuration permissions of                                 [success]
devmaster_1  | /var/aegir/config/server_master have been changed to 711.
devmaster_1  | Provision configuration path /var/aegir/config/server_master is        [success]
devmaster_1  | writable.
devmaster_1  | Provision client home path /var/aegir/clients exists.                  [success]
devmaster_1  | Provision client home ownership of /var/aegir/clients has been         [success]
devmaster_1  | changed to aegir.
devmaster_1  | Provision client home permissions of /var/aegir/clients have been      [success]
devmaster_1  | changed to 711.
devmaster_1  | Provision client home path /var/aegir/clients is writable.             [success]
devmaster_1  | Backup path /var/aegir/backups exists.                                 [success]
devmaster_1  | Backup ownership of /var/aegir/backups has been changed to aegir.      [success]
devmaster_1  | Backup permissions of /var/aegir/backups have been changed to 700.     [success]
devmaster_1  | Backup path /var/aegir/backups is writable.                            [success]
devmaster_1  | Provision PHP configuration path /var/aegir/config/includes exists.    [success]
devmaster_1  | Provision PHP configuration ownership of /var/aegir/config/includes    [success]
devmaster_1  | has been changed to aegir.
devmaster_1  | Provision PHP configuration permissions of /var/aegir/config/includes  [success]
devmaster_1  | have been changed to 711.
devmaster_1  | Provision PHP configuration path /var/aegir/config/includes is         [success]
devmaster_1  | writable.
devmaster_1  | Global configuration file exists                                       [success]
devmaster_1  | Changed permissions of                                                 [success]
devmaster_1  | /var/aegir/.drush/server_master.alias.drushrc.php to 640
devmaster_1  | Generated config in write(): Drush configuration file                  [success]
devmaster_1  | (/var/aegir/.drush/server_master.alias.drushrc.php)
devmaster_1  | Changed permissions of                                                 [success]
devmaster_1  | /var/aegir/.drush/server_master.alias.drushrc.php to 440
devmaster_1  | Webserver custom pre-configuration path                                [success]
devmaster_1  | /var/aegir/config/server_master/apache exists.
devmaster_1  | Webserver custom pre-configuration ownership of                        [success]
devmaster_1  | /var/aegir/config/server_master/apache has been changed to aegir.
devmaster_1  | Webserver custom pre-configuration permissions of                      [success]
devmaster_1  | /var/aegir/config/server_master/apache have been changed to 711.
devmaster_1  | Webserver custom pre-configuration path                                [success]
devmaster_1  | /var/aegir/config/server_master/apache is writable.
devmaster_1  | Webserver custom pre-configuration path                                [success]
devmaster_1  | /var/aegir/config/server_master/apache/pre.d exists.
devmaster_1  | Webserver custom pre-configuration ownership of                        [success]
devmaster_1  | /var/aegir/config/server_master/apache/pre.d has been changed to
devmaster_1  | aegir.
devmaster_1  | Webserver custom pre-configuration permissions of                      [success]
devmaster_1  | /var/aegir/config/server_master/apache/pre.d have been changed to
devmaster_1  | 700.
devmaster_1  | Webserver custom pre-configuration path                                [success]
devmaster_1  | /var/aegir/config/server_master/apache/pre.d is writable.
devmaster_1  | Webserver custom post-configuration path                               [success]
devmaster_1  | /var/aegir/config/server_master/apache/post.d exists.
devmaster_1  | Webserver custom post-configuration ownership of                       [success]
devmaster_1  | /var/aegir/config/server_master/apache/post.d has been changed to
devmaster_1  | aegir.
devmaster_1  | Webserver custom post-configuration permissions of                     [success]
devmaster_1  | /var/aegir/config/server_master/apache/post.d have been changed to
devmaster_1  | 700.
devmaster_1  | Webserver custom post-configuration path                               [success]
devmaster_1  | /var/aegir/config/server_master/apache/post.d is writable.
devmaster_1  | Webserver platform configuration path                                  [success]
devmaster_1  | /var/aegir/config/server_master/apache/platform.d exists.
devmaster_1  | Webserver platform configuration ownership of                          [success]
devmaster_1  | /var/aegir/config/server_master/apache/platform.d has been changed to
devmaster_1  | aegir.
devmaster_1  | Webserver platform configuration permissions of                        [success]
devmaster_1  | /var/aegir/config/server_master/apache/platform.d have been changed
devmaster_1  | to 700.
devmaster_1  | Webserver platform configuration path                                  [success]
devmaster_1  | /var/aegir/config/server_master/apache/platform.d is writable.
devmaster_1  | Webserver virtual host configuration path                              [success]
devmaster_1  | /var/aegir/config/server_master/apache/vhost.d exists.
devmaster_1  | Webserver virtual host configuration ownership of                      [success]
devmaster_1  | /var/aegir/config/server_master/apache/vhost.d has been changed to
devmaster_1  | aegir.
devmaster_1  | Webserver virtual host configuration permissions of                    [success]
devmaster_1  | /var/aegir/config/server_master/apache/vhost.d have been changed to
devmaster_1  | 700.
devmaster_1  | Webserver virtual host configuration path                              [success]
devmaster_1  | /var/aegir/config/server_master/apache/vhost.d is writable.
devmaster_1  | Webserver subdir configuration path                                    [success]
devmaster_1  | /var/aegir/config/server_master/apache/subdir.d exists.
devmaster_1  | Webserver subdir configuration ownership of                            [success]
devmaster_1  | /var/aegir/config/server_master/apache/subdir.d has been changed to
devmaster_1  | aegir.
devmaster_1  | Webserver subdir configuration permissions of                          [success]
devmaster_1  | /var/aegir/config/server_master/apache/subdir.d have been changed to
devmaster_1  | 700.
devmaster_1  | Webserver subdir configuration path                                    [success]
devmaster_1  | /var/aegir/config/server_master/apache/subdir.d is writable.
devmaster_1  | Generated config in write(): web server configuration file             [success]
devmaster_1  | (/var/aegir/config/server_master/apache.conf)
devmaster_1  | apache on devshop.local.computer could not be restarted. Changes       [warning]
devmaster_1  | might not be available until this has been done. (error: apache2:
devmaster_1  | Syntax error on line 216 of /etc/apache2/apache2.conf: Syntax error
devmaster_1  | on line 25 of /etc/apache2/conf-enabled/aegir.conf: Syntax error on
devmaster_1  | line 16 of
devmaster_1  | /var/aegir/config/server_master/apache/platform.d/platform_hostmaster.conf:
devmaster_1  | Could not open configuration file
devmaster_1  | /var/aegir/devmaster-docker/.htaccess: No such file or directory
devmaster_1  | Action 'graceful' failed.
devmaster_1  | The Apache error log may have more information.)
devmaster_1  | Changed permissions of                                                 [success]
devmaster_1  | /var/aegir/.drush/platform_hostmaster.alias.drushrc.php to 640
devmaster_1  | Generated config in write(): Drush configuration file                  [success]
devmaster_1  | (/var/aegir/.drush/platform_hostmaster.alias.drushrc.php)
devmaster_1  | Changed permissions of                                                 [success]
devmaster_1  | /var/aegir/.drush/platform_hostmaster.alias.drushrc.php to 440
devmaster_1  | We could not find an applicable site for that command.                   [error]
devmaster_1  | Drush could not bootstrap this platform. Please check the platform       [error]
devmaster_1  | directory exists and is readable.
devshop_devmaster_1 exited with code 1

**Comment by jonpugh** [comment]
The docker-compose.yml and development-* scripts have been updated significantly.

I'm sure this works now. If you still have problems, please re-open.

See https://github.com/opendevshop/devshop/blob/1.x/development-prepare.sh and https://github.com/opendevshop/devshop/blob/1.x/development-launch.sh
