### ISSUE TITLE
Docker / Make / Build!

### ISSUE THREAD

**Issue by llwp** [opendevshop/devshop#149]
It would be great to solve a number of known items that have been discussed in this project - including but not limited to:
(1) integrating use of docker into the devshop platform
(2) fixing that pesky make file / drupal profile process as covered very well in #113 
(3) permitting the hosting/management of alternate aegir-platform web stacks ie, wordpress, html, joomla, etc.

... or at least laying the groundwork for these things to be accomplished.

If we define a "build" process that allows us to set an environment within a project as 'built in docker' then this takes us in the right direction.  Project settings (or environment specific settings) could be enforced or configurable in a similar way to how Deployment Hooks are handled now.

Part of this will of course mean identifying what I've come to think of as a "devshop build".

Essentially, I am suggesting we create an aegir_devshop_build module (name subject to change) that handles the core components that support the above listed items under a build process that encapsulates them such that using Docker along side Aegir is handled readily.

And here is the thing;
I've started this work for my own uses.
Just wanted to let others know before I went too far down that road.

Let me know what *you* think. ;)

AJ

**Comment by jonpugh** [comment]
None of this is possible until we address the issues in core Aegir  laid out at https://www.drupal.org/node/2309547

The problems are so deep in Provision that there is no way for us to just override it with a module. Core Aegir needs major overhauls to make this possible.
