### ISSUE TITLE
Until user first logs in

### ISSUE THREAD

**Issue by llwp** [opendevshop/devshop#151]
Until user 1 logs in, new DevShop instance setup is incomplete and may pose a security risk.  This should be classified as a bug.

Once first login occurs, the login page displays as expected.

Yes, in the screenshot the URL has "install.php" - this is because all visitors to the site are redirected to the install page.

![devshop-new-install](https://cloud.githubusercontent.com/assets/9566542/19126096/90aa749e-8b07-11e6-8584-b89ca3458c1e.png)

**Comment by jonpugh** [comment]
This is not normal. All aegir sites must go through automated install. Something else must have interrupted or mis-configured your setup.

**Comment by llwp** [comment]
Thanks, Jon.
