### ISSUE TITLE
Suggested Git Ignore Documentation

### ISSUE THREAD

**Issue by act2281** [opendevshop/devshop#152]
If you can provide a git ignore file that would be great, otherwise we should provided a suggested git ignore to exlucde the ageir files.

What I use:

    * # Ignore configuration files that may contain sensitive information.
    * sites/*/settings*.php
    * # Ignore paths that contain user-generated content.
    * sites/*
    * sites/*/files
    * sites/*/private
    * !sites/all
    * !sites/default
    * !sites/drush
    * 
    * error_log
    * .htaccess
    * .htpasswd
    * */error_log
    * */.htaccess
    * sites/all/modules/*/error_log
    * 
    * sites/all/themes/Centric/.sass-cache
    * blog
    * */.sass-cache

**Comment by jonpugh** [comment]
Thanks! 

We do offer a suggested git ignore but it is very hard to find. We should offer a way to automatically add it.  

In the meantime, we should add that to documentation as well. Hopefully I can get to it after this month, if you wish you can submit a PR on the documentation to add a page .

**Comment by jonpugh** [comment]
:point_down:

**Comment by jonpugh** [comment]
Close enough to a duplicate to close: See #291
