### ISSUE TITLE
Remote Aliases for Rsync Fail

### ISSUE THREAD

**Issue by act2281** [opendevshop/devshop#153]
If you try to do a file sync to a remote alias, it fails because the path structure changes vs a local alias.

**Comment by jonpugh** [comment]
Can you try to set the %files path in your alias? 

See the project "drush aliases" popup for an example: 

```php
<?php
$aliases['dfgh'] = array(
  'root' => '/var/aegir/projects/make/dfgh/buildit',
  'uri' => 'make.dfgh.devshop.local.computer',
  'remote-user' => 'aegir',
  'remote-host' => 'devshop.local.computer',
  'path-aliases' => array(
    '%files' => 'sites/make.dfgh.devshop.local.computer/files',
  ),
);
```

**Comment by jonpugh** [comment]
Oh, are you talking about the Project "Remote Aliases" feature? 

Yes, we need to add a "path to files" field, I think.

**Comment by jonpugh** [comment]
I'm not sure I want to support this feature anymore. Having your dev server reach into a production server isn't secure. The dev server is expected to allow developers into it. 

The "install method" feature is a better solution: Once the site is created, it can be "reinstalled" using the original data source.

I want to deprecate the entire idea of "sync data". Environments should just be installed, and reinstalled.
