### ISSUE TITLE
Allow setting a default HTAccess Password for all environments

### ISSUE THREAD

**Issue by act2281** [opendevshop/devshop#156]
* Default Password / htaccess on environments  (for new environments as made) so that we can ensure the dev environments all secured.

**Comment by jonpugh** [comment]
Great idea, I've wanted this for a while. 

It's not that hard, either. Just use form_alter to change project node edit form and add your element to $form['project']['settings']  and it will get serialized automatically.

Then we just need to form_alter the site node form to lookup the project and default the password form elements....

**Comment by jonpugh** [comment]
i have wanted this for SO LONG! :older_man:

**Comment by jonpugh** [comment]
Tracking in #349
