### ISSUE TITLE
Pre Import Health Check

### ISSUE THREAD

**Issue by act2281** [opendevshop/devshop#157]
I've had many sites fail on import because of something wrong on the site, then it gits stuck part way through and doesn't want to delete or import. Perhaps a pre import health check?

- Errors on update page
- Permissions file errors (I've had sites not get the proper permissons set when being made)
- Git sub modules cause the import to fail

I have a few more I will need to watch for an note that could be picked up to make it more clear what needs to be done.

**Comment by act2281** [comment]
I had several instances where I tried to import something and it failed, but it was part way through building it, and it didn't role it back properly. This caused sites to get stuck and do several odd things:

* Aegir config file didn’t build properly telling my site to use a HTACCESS file so it was ignored.
* Clean URL’s failing on site (causes AJAX & pages to not save)

**Comment by jonpugh** [comment]
This is definitely an issue with Aegir.  
It was originally designed to just launch multisites from an install profile. No unique sites.  
We should add things like this as Aegir patches. It's challenging.

**Comment by act2281** [comment]
Yeah,I think this one was my biggest issue and is the reason I’m not using it. Everything was failing and crashing on import because none of my sites were setup properly or had small errors on import that made it to hard for me to manage in my dev environment.

**Comment by jonpugh** [comment]
This will all go away with Provision4
