### ISSUE TITLE
Remote Alias Title Doesn't Allow Spaces & Special Characters

### ISSUE THREAD

**Issue by act2281** [opendevshop/devshop#158]
It should be obvious but I keep putting spaces and special characters in, then find my alias won't work and have to do it again.

**Comment by jonpugh** [comment]
Oops looks like this was fixed!

https://github.com/opendevshop/devmaster/commit/f9671af43a786fc4fd11e1d906f9ab6370254ce5

**Comment by jonpugh** [comment]
You are talking about remote aliases, right>

This issue was posted way after this was fixed.

@act2281 Please re-open if you are still having trouble.
