### ISSUE TITLE
Multi-byte UTF-8 support

### ISSUE THREAD

**Issue by arttus** [opendevshop/devshop#160]
# Pull Request

#164 

With 7.50 in some cases Devshop is now issuing warnings about Multi-byte UTF-8 support when syncing data to new environments. Is there any reason that Multi-byte UTF-8 should not be Devshops default out of the box? 

More info here
https://www.drupal.org/node/2754539

There is the issue of upgrading pre 7.50 sites, but of course there's a module (actually it's not a module) for that... https://www.drupal.org/project/utf8mb4_convert

**Comment by jonpugh** [comment]
No reason at all! It's just not in the default mysql config.

The settings are listed in our docker-compose.yml file, we just need to figure out if we need an ansible variable for geerlingguy/ansible-playbook-mysql or a patch to his template or what.

**Comment by arttus** [comment]
OK great, I will also follow up over on the geerlingguy/ansible-role-mysql issue queue.

**Comment by jonpugh** [comment]
I think it might just be a version thing, check our roles.yml file against the latest release of the Ansible role. Would be an easy PR!

**Comment by arttus** [comment]
done.
