### ISSUE TITLE
The platform at path still has [error] sites present. Please delete them first.

### ISSUE THREAD

**Issue by arttus** [opendevshop/devshop#167]
I'm running into this as well. Adrianux first documented here, https://github.com/opendevshop/devshop/issues/159 and since that issue is closed I'm adding this here.

<pre>
Run the command: drush @hostmaster platform-delete /var/aegir/devmaster-1.x -y (y/N) y
[DEVSHOP] Looking up platform at                                     [ok]
/var/aegir/devmaster-1.x
[DEVSHOP] Found platform 391                                         [ok]
The platform at path /var/aegir/devmaster-1.x still has [error]
sites present. Please delete them first.
</pre>

**Comment by adrinux** [comment]
arttus I get that following the ansible fail during upgrade I document in #165, so I think this issue is essentially a dupe.

**Comment by arttus** [comment]
@adrinux, it also happens on Apache, which is why i thought you were documenting a different issue. If you actually think it's a dup, probably should rename the issue, and close this one.

**Comment by adrinux** [comment]
You need to look further up in the upgrade output, you should see Ansible failing whilst running the geerlingguy.mysql role. If you see that it's likely the same issue, even if the specifics related to Apache are different. Have you looked at the Apache error.log?

**Comment by arttus** [comment]
You're right it's not specific to one server or the other. Just ran the upgrade and watched the apache error.log, no errors. I'm going to just close this as a dup.

**Comment by adrinux** [comment]
@arttus I made progress in #165 and this problem _still_ occurs. This is looking like a separate issue so please reopen it. Sorry.

**Comment by adrinux** [comment]
- Running the failing drush command manually as aegir user fails identically.
- Running it with the --debug flag doesn't show any other errors
- The drushrc for the platform has an empty sites array. ( /var/aegir/devmaster-1.0.0-beta10/sites/all/drush/drushrc.php )
- Workaround: You can visit hosting/platforms in the frontend and execute a delete task on the troublesome platform (which will show as having 0 sites) and it will delete (both in frontend and in the filesystem).

**Comment by jonpugh** [comment]
Thanks for triaging this.

This is the final step in the upgrade, and isn't actually required. As @adrinux said, you can delete the orphan platform manually.  

This is a special drush command we created just to delete a platform by path, located at https://github.com/opendevshop/devmaster/blob/1.x/modules/devshop/devshop_hosting.drush.inc

I'll try to get to this before then next release, but if anyone else wants to give it a go, there's the code.

**Comment by adrinux** [comment]
Well, that finds the old platform nid ok, it even prints it to console. And if I manually run the query using that nid and 1 for enabled sites:
```
SELECT nid FROM hosting_site WHERE platform = 7 AND status = 1;
Empty set (0.00 sec)
```
So why it returns that I error I don't see...does $site_nid need to be explicitly set empty before that query runs? I'm not sure what db_query returns is mysql reports 'empty set'.
(Out of time for today)

**Comment by adrinux** [comment]
The result returned from that query will never '!empty' to php, working on a fix, will hopefully have a PR before the end of the day.

**Comment by adrinux** [comment]
FIrst pass fix: https://github.com/opendevshop/devmaster/pull/45

**Comment by jonpugh** [comment]
PR was merged!

thanks @adrinux
