### ISSUE TITLE
Git Webhooks 500 error code

### ISSUE THREAD

**Issue by arttus** [opendevshop/devshop#168]
On recent builds of devshop Git Webhooks fails to connect and is returning 500 error code. I tried this on two different recent builds and ran into the issue on both servers.

On the devmaster front-end, because it's not connecting we get the standard Setup Webhook.
Last Commit  Not Received   Setup Webhook

If we look at the payload URL basically it's returning the standard drupal error page.

Error
The website encountered an unexpected error. Please try again later.

**Comment by arttus** [comment]
https://github.com/opendevshop/devmaster/pull/46 ready for review.

**Comment by jonpugh** [comment]
Merged on Dec 7, 2016
