### ISSUE TITLE
Adding new domain aliases no longer works.

### ISSUE THREAD

**Issue by arttus** [opendevshop/devshop#170]
Click [Add an alias] 
Ajax indicator spins nothing happens.
here are the three watchdog messages created

Location	http://dev.mysite/system/ajax
Referrer	http://dev.mysite/node/436/edit/env/develop
Message	Warning: Invalid argument supplied for foreach() in menu_parent_options() (line 376 of /var/aegir/devmaster-1.x-2016-11-21-1/modules/menu/menu.module).
Severity	warning

Location	http://dev.mysite/system/ajax
Referrer	http://dev.mysite/node/436/edit/env/develop
Message	Notice: Undefined index: acquia_hooks in devshop_environment_deploy_hooks_form() (line 861 of /var/aegir/devmaster-1.x-2016-11-21-1/profiles/devmaster/modules/devshop/devshop_projects/inc/forms.inc).
Severity	notice

Location	http://dev.mysite/system/ajax
Referrer	http://dev.mysite/node/436/edit/env/develop
Message	Notice: Undefined index: acquia_hooks in devshop_environment_deploy_hooks_form() (line 855 of /var/aegir/devmaster-1.x-2016-11-21-1/profiles/devmaster/modules/devshop/devshop_projects/inc/forms.inc).
Severity	notice

**Comment by arttus** [comment]
Haven't quite figured out the issue but it seems to have something to do with the alias_wrapper group overwriting AJAX calls  in function boots_form_site_node_form_alter  in /var/aegir/devmaster-1.x/profiles/devmaster/themes/boots/template.php

if i comment out

  //$form['aliases_wrapper']['#group'] = 'environment_settings';
  //$form['aliases_wrapper']['#title'] = t('Domain Names');
  //$form['aliases_wrapper']['#prefix'] = '';
  //$form['aliases_wrapper']['#suffix'] = '';

 I can at least get the domain aliases working. Obviously just a work around until Jon can have a look.

**Comment by jonpugh** [comment]
Good find @arttus. I'm poking around this one now.

**Comment by jonpugh** [comment]
Figured out a workaround.  Created a second fieldgroup for "Domain Names" and moved "alias_wrapper" into it.

The #ajax replace needed #prefix to work, but if the aliases_wrapper itself is put into the vertical tabs, it confuses the markup because prefix and suffix go around the fieldset.
