### ISSUE TITLE
Importing backups generated by Aegir or Devshop

### ISSUE THREAD

**Issue by adrinux** [opendevshop/devshop#181]
For those of us already using Aegir to host Drupal sites but wishing to bring sites into DevShop this seems a nice easy path.

Works nicely by following these steps:
1. Create a backup in Aegir.
2. Create a copy of the platform code (minus aegir related files) and add it to a git repo for devshop to use.
3. Create a project and environment in devshop specifying the git repo from step 2.
4. Move the Aegir backup archive into eg /var/aegir/imports and check permissions.
5. Run provision-deploy to import the site. Example with project named test, environment named 'live' and domain ods.example.com (this is the drush alias devshop uses for the site):
```
drush @live.test.ods.example.com provision-deploy /var/aegir/imports/site.example.com-20160713.233937.tar.gz
```
6. Run a 'verify site' task from the project view in the devshop front end.

- provision-deploy will change the site name to match (currently buggy, the site name gets repeated several times but is easily corrected by logging into the site and changing the configuration).
- this will also import any sites/sitename/files folders present in the backup with their contents
- I haven't tried this with devshop backups yet...

@jonpugh Mentioned on Gitter:
"We could create an add on module that allows importing an aegir backup."

Since running provision-deploy is the only unique thing in the above list I'd assume adding 'import backup' might be quite simple.

It occurs to me that a general backup import module that also imported devshop site backups might be useful too, especially in the case of disaster recovery.

**Comment by jonpugh** [comment]
I agree with this, but I'm hesitant to lean on drush provision-deploy.

You know, the "remote alias" feature would work for this. It's a little know feature. I want to change that feature to be more for "Remote Sites", where we can add environments that point to externally hosted sites.

**Comment by adrinux** [comment]
Personally I dropped Drupal some time ago. So, closing this.
