### ISSUE TITLE
Error "We could not find an applicable site for that command" when verifying and cloning a Git repo with Drupal path not empty

### ISSUE THREAD

**Issue by moerazem** [opendevshop/devshop#185]
When cloning a new project, Git tries to clone to the Drupal path. Resulting in a an error "We could not find an applicable site for that command. Drush could not bootstrap this platform. Please check the platform directory exists and is readable."

That is because the git clone command will use the platform path as a git clone path. This is wrong, it should clone to the environment path without the Drupal path.

This pull request fixes it: https://github.com/opendevshop/devmaster/pull/55

![screen shot 2017-02-14 at 1 29 29 pm](https://cloud.githubusercontent.com/assets/122433/22927390/a43cd820-f2b9-11e6-82a0-d85408d11de9.png)

**Comment by a-fro** [comment]
@jonpugh I'm running into this issue as well. Thoughts on @moerazem's pull request? 

I'm currently stuck because I'm unable to upgrade devshop 0.8.2, and can't get 1.x to work.

**Comment by moerazem** [comment]
@a-fro a temp solution for you until the Pull-request is merged is to apply a patch.
Use the patch from the pull-request: https://patch-diff.githubusercontent.com/raw/opendevshop/devmaster/pull/55.patch
`cd profiles/devmaster`
`patch -p1 < /path/to/55.patch`

**Comment by jienckebd** [comment]
Worked for me thanks @moerazem !

**Comment by jonpugh** [comment]
Thanks all for your patience, I've tracked down the original cause of the problem. A piece of code was accidentally committed to the 1.x branch.  I'm about to get things back in order. 

Stand by for commits.

**Comment by jonpugh** [comment]
Fixed in https://github.com/opendevshop/devmaster/pull/57

Please test out 1.x, if this issue still arises, please reopen.

**Comment by ichionid** [comment]
Profile installation for the template composer project fails. I yday downloaded 1.1x. Is this related?

![Selection_284](https://user-images.githubusercontent.com/946456/115014863-2b6f9680-9eb3-11eb-997e-9e9ca64f81cc.png)
