### ISSUE TITLE
Please don't Readthedocs?

### ISSUE THREAD

**Issue by arttus** [opendevshop/devshop#186]
Based on the PR of that site it tends to rank rather well when searching devshop documentation. If it's not up-to-date it should be removed from the readthedocs site.

**Comment by jonpugh** [comment]
Thank you for the reminder, @arttus, I'll take care of this today.

**Comment by jonpugh** [comment]
RTD project has been deleted, so old links now break, but the links from getdevshop.com have been changed, so google should be able to re-index soon.
