### ISSUE TITLE
 Access denied for user 'root'@'localhost' - Mysql - On Fresh Install

### ISSUE THREAD

**Issue by jszaszvari** [opendevshop/devshop#187]
On a fresh install (Have tried re-installing the OS multiple times)  I download the install script, Make sure I am root (no su or sudo) run the installer and it fails every time with 

FAILED! => {"changed": false, "cmd": ["mysql", "-NBe", "SELECT Host FROM mysql.user WHERE User = \"\""], "delta": "0:00:00.004466", "end": "2017-02-23 17:02:18.097471", "failed": true, "rc": 1, "start": "2017-02-23 17:02:18.093005", "stderr": "ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)", "stdout": "", "stdout_lines": [], "warnings": []}

What am I doing wrong? 

Ubuntu 14.04 is the OS I am using

**Comment by realitygaps** [comment]
I found copying /root/.my.cnf file to your home directory for the user you are installing as and then rerunning ansible solved this issue for me (I think this only happens if you install with sudo)

**Comment by jonpugh** [comment]
Yes, make sure your current user's home directory it /root.

If you run `sudo -h install.sh` it may not work because the $HOME variable isn't set.

You can run `sudo -h bash install.sh` or switch to root , then just run bash `install.sh`
