### ISSUE TITLE
vagrant install fails There is no '/var/aegir/.drush/hostmaster.alias.drushrc.php' file.

### ISSUE THREAD

**Issue by niccolox** [opendevshop/devshop#19]
I've just rebuilt my laptop with Trusty host and am trying to vagrant up devshop

it fails

==> default: TASK: [Clear the drush cache.] ************************************************ 
==> default: changed: [devshop.local]
==> default: 
==> default: TASK: [debug msg="$ {{ drush_path }} devshop-install {{ server_hostname }} --version={{ devmaster_version }} --aegir_db_pass={{ mysql_root_password }} --aegir_db_user=root --makefile={{ devshop_makefile }} --profile=devmaster --aegir_host={{ server_hostname }} {{ devshop_working_copy }} -y"] *** 
==> default: ok: [devshop.local] => {
==> default:     "msg": "$ /usr/local/bin/drush devshop-install devshop.local --version=0.x --aegir_db_pass=zfEYWqgLRqbxpoqeWNvy-TMm5pC2sfF8 --aegir_db_user=root --makefile=build-devmaster.make --profile=devmaster --aegir_host=devshop.local --working-copy -y"
==> default: }
==> default: 
==> default: TASK: [Install Devmaster] ***************************************************** 
==> default: failed: [devshop.local] => {"changed": true, "cmd": ["/usr/local/bin/drush", "devshop-install", "devshop.local", "--version=0.x", "--aegir_db_pass=zfEYWqgLRqbxpoqeWNvy-TMm5pC2sfF8", "--aegir_db_user=root", "--makefile=build-devmaster.make", "--profile=devmaster", "--aegir_host=devshop.local", "--working-copy", "-y"], "delta": "0:00:00.415160", "end": "2015-07-06 22:05:48.875680", "rc": 1, "start": "2015-07-06 22:05:48.460520", "warnings": []}
==> default: stderr: The drush command 'devshop-install devshop.local' could not be found.    [error]
==> default:  Run `drush cache-clear drush` to clear the commandfile cache if you
==> default: have installed new extensions.
==> default: A Drupal installation directory could not be found                       [error]
==> default: 
==> default: FATAL: all hosts have already failed -- aborting
==> default: 
==> default: PLAY RECAP ******************************************************************** 
==> default:            to retry, use: --limit @/root/playbook.retry
==> default: 
==> default: devshop.local              : ok=36   changed=27   unreachable=0    failed=1   
==> default: Loading composer repositories with package information
==> default: Installing dependencies (including require-dev) from lock file
==> default: Nothing to install or update
==> default: Generating autoload files
==> default: ╔═════════════════════════════════════════════════════════════════════╗
==> default: ║ It appears something failed during installation.                    ║
==> default: ║ There is no '/var/aegir/.drush/hostmaster.alias.drushrc.php' file.  ║

**Comment by niccolox** [comment]
still getting it

=> default: 
==> default: TASK: [Install Devmaster] ***************************************************** 
==> default: failed: [devshop.local] => {"changed": true, "cmd": ["/usr/local/bin/drush", "devshop-install", "devshop.local", "--version=0.x", "--aegir_db_pass=VIc3JSl_n3VQklBCpsfrc2xo1Lc6kG39", "--aegir_db_user=root", "--makefile=build-devmaster.make", "--profile=devmaster", "--aegir_host=devshop.local", "--working-copy", "-y"], "delta": "0:00:00.626147", "end": "2015-07-07 23:08:22.555419", "rc": 1, "start": "2015-07-07 23:08:21.929272", "warnings": []}
==> default: stderr: The drush command 'devshop-install devshop.local' could not be found.    [error]
==> default:  Run `drush cache-clear drush` to clear the commandfile cache if you
==> default: have installed new extensions.
==> default: A Drupal installation directory could not be found                       [error]
==> default: 
==> default: FATAL: all hosts have already failed -- aborting
==> default: 
==> default: PLAY RECAP ******************************************************************** 
==> default:            to retry, use: --limit @/root/playbook.retry
==> default: 
==> default: devshop.local              : ok=36   changed=27   unreachable=0    failed=1   
==> default: Loading composer repositories with package information
==> default: Installing dependencies (including require-dev) from lock file
==> default: Nothing to install or update
==> default: Generating autoload files
==> default: ╔═════════════════════════════════════════════════════════════════════╗
==> default: ║ It appears something failed during installation.                    ║
==> default: ║ There is no '/var/aegir/.drush/hostmaster.alias.drushrc.php' file.  ║
==> default: ╚═════════════════════════════════════════════════════════════════════╝
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by llwp** [comment]
Try updating hosts and hostname.

Adam John
(914) 623-8433

**Comment by niccolox** [comment]
changed loopback ip to static on host and deleted the entire previous devshop folder and started again

registry_rebuild was not downloaded

Cloning into 'registry_rebuild'...
fatal: Remote branch 6.x-2.x not found in upstream origin
fatal: The remote end hung up unexpectedly

and this warning
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory

but, got these 

==> default: symfony/event-dispatcher suggests installing symfony/dependency-injection ()
==> default: symfony/event-dispatcher suggests installing symfony/http-kernel ()
==> default: guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
==> default: knplabs/github-api suggests installing knplabs/gaufrette (Needed for optional Gaufrette cache)
==> default: symfony/console suggests installing psr/log (For using the console logger)
==> default: Generating autoload files
==> default: ╔═════════════════════════════════════════════════════════════════════╗
==> default: ║ It appears something failed during installation.                    ║
==> default: ║ There is no '/var/aegir/.drush/hostmaster.alias.drushrc.php' file.  ║
==> default: ╚═════════════════════════════════════════════════════════════════════╝

**Comment by niccolox** [comment]
just deleted ~/Sites/drupalvm, deleted git repo, selected hosts and etc/exports

rebooted

git cloned and started again

failed

---
# `vagrant_box` can also be set to geerlingguy/centos6, geerlingguy/centos7,
# geerlingguy/ubuntu1204, parallels/ubuntu-14.04, etc.
vagrant_box: geerlingguy/ubuntu1404
vagrant_user: vagrant

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: drupalvm.dev
vagrant_machine_name: drupalvm
vagrant_ip: 192.168.88.88

# A list of synced folders, with the keys 'local_path', 'destination', 'id', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# https://github.com/geerlingguy/drupal-vm/wiki/Syncing-Folders for more info.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # build_from_makefile is 'true'.
  - local_path: ~/Sites/drupalvm
    destination: /var/www
    id: drupal
    type: 
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 1024
vagrant_cpus: 1

# Set this to false if you are using a different site deployment strategy and
# would like to configure 'vagrant_synced_folders' and 'apache_vhosts' manually.
build_makefile: true
drush_makefile_path: /vagrant/drupal.make.yml

# Set this to false if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
install_site: true

# Settings for building a Drupal site from a makefile (if 'build_from_makefile'
# is 'true').
drupal_major_version: 7
drupal_core_path: "/var/www/drupal"
drupal_domain: "drupalvm.dev"
drupal_site_name: "Drupal"
drupal_install_profile: standard
drupal_enable_modules: [ 'devel' ]
drupal_account_name: admin
drupal_account_pass: admin
drupal_mysql_user: drupal
drupal_mysql_password: drupal
drupal_mysql_database: drupal

# Cron jobs are added to the root user's crontab. Keys include name (required),
# minute, hour, day, weekday, month, job (required), and state.
drupalvm_cron_jobs: []
  # - {
  #   name: "Drupal Cron",
  #   minute: "*/30",
  #   job: "drush -r {{ drupal_core_path }} core-cron"
  # }

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_local_drush_aliases: true

# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
apache_vhosts:
  - {servername: "{{ drupal_domain }}", documentroot: "{{ drupal_core_path }}"}
  - {servername: "xhprof.drupalvm.dev", documentroot: "/usr/share/php/xhprof_html"}
  - {servername: "pimpmylog.drupalvm.dev", documentroot: "/usr/share/php/pimpmylog"}

# MySQL Databases and users. If build_from_makefile is true, first database will
# be used for the makefile-built site.
mysql_databases:
  - name: "{{ drupal_mysql_database }}"
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: "{{ drupal_mysql_user }}"
    host: "%"
    password: "{{ drupal_mysql_password }}"
    priv: "{{ drupal_mysql_database }}.*:ALL"

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, make set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  - mailhog
  - memcached
  - pimpmylog
  - solr
  - varnish
  - xdebug
  - xhprof

# Add any extra packages you'd like to install.
extra_packages: []

# You can configure almost anything else on the server in the rest of this file.
mysql_root_password: root

extra_security_enabled: false

drush_version: master
drush_keep_updated: true

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
firewall_log_dropped_packets: false

# PHP Configuration. Currently-supported versions: 5.5, 5.6, 7.0 (experimental).
php_version: "5.5"
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

# composer_global_packages:
#   - { name: phpunit/phpunit, release: '@stable' }

# MySQL Configuration.
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
adminer_add_apache_config: true

# Varnish Configuration.
varnish_listen_port: "81"
varnish_default_vcl_template_path: templates/drupalvm.vcl.j2
varnish_default_backend_host: "127.0.0.1"
varnish_default_backend_port: "80"

# Pimp my Log settings.
pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true

# Disable main XDebug components unless needed.
php_xdebug_coverage_enable: 0
php_xdebug_default_enable: 0

# Solr Configuration (if enabled above).
solr_version: "4.10.4"
solr_xms: "64M"
solr_xmx: "128M"


and

---
api: 2

# Basic Drush Make file for Drupal. Be sure to update the drupal_major_version
# variable inside config.yml if you change the major version in this file.

# Drupal core (major version, e.g. 6.x, 7.x, 8.x).
core: "7.x"

projects:

  # Core.
  drupal:
    type: "core"
    download:
      # Drupal core branch (e.g. "6.x", "7.x", "8.0.x").
      branch: "7.x"
      working-copy: true

  # Other modules.
  devel: "1.x-dev"

**Comment by niccolox** [comment]
I just tried to install devshop on Vagrant, Proxmox and Digital Ocean and it failed on all

root@devshop:~# wget https://raw.githubusercontent.com/opendevshop/devshop/0.3.1/install.sh                                         
--2015-07-08 23:30:15--  https://raw.githubusercontent.com/opendevshop/devshop/0.3.1/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.46.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.46.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7837 (7.7K) [text/plain]
Saving to: ‘install.sh’

100%[==========================================================================================>] 7,837       --.-K/s   in 0s      

2015-07-08 23:30:15 (1.66 GB/s) - ‘install.sh’ saved [7837/7837]

root@devshop:~# bash install.sh > devshop.txt

**Comment by niccolox** [comment]
actually

I DO it gives errors but installs.. havent got time to back track on Vagrant.... 

HEAD is now at 59ee32d... Bumping version to 0.3.1
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing symfony/event-dispatcher (v2.7.1)
  - Installing knplabs/github-api (1.4.12)
    Downloading: 100%         

  - Installing symfony/console (v2.7.1)
    Downloading: 100%         

  - Installing symfony/filesystem (v2.7.1)
    Downloading: 100%         

  - Installing symfony/finder (v2.7.1)
    Downloading: 100%         

  - Installing symfony/process (v2.7.1)
    Downloading: 100%         

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
knplabs/github-api suggests installing knplabs/gaufrette (Needed for optional Gaufrette cache)
symfony/console suggests installing psr/log (For using the console logger)
Generating autoload files

**Comment by niccolox** [comment]
actually, DO and Proxmox (kvm) install works (but with Guzzle errors)

yep, Vagrant fails .. may be able to try this again Thursday

==> default:
==> default: TASK: [debug msg="$ {{ drush_path }} devshop-install {{ server_hostname }} --version={{ devmaster_version }} --aegir_d$
==> default: ok: [devshop.local] => {
==> default:     "msg": "$ /usr/local/bin/drush devshop-install devshop.local --version=0.x --aegir_db_pass=KCWyd9sLMDmfXjFT_vkozF9$
==> default: }
==> default:
==> default: TASK: [Install Devmaster] *****************************************************
==> default: failed: [devshop.local] => {"changed": true, "cmd": ["/usr/local/bin/drush", "devshop-install", "devshop.local", "--ve$
==> default: stderr: The drush command 'devshop-install devshop.local' could not be found.    [error]
==> default:  Run `drush cache-clear drush` to clear the commandfile cache if you
==> default: have installed new extensions.
==> default: A Drupal installation directory could not be found                       [error]
==> default:
==> default: FATAL: all hosts have already failed -- aborting
==> default:
==> default: PLAY RECAP ********************************************************************
==> default:            to retry, use: --limit @/root/playbook.retry
==> default:
==> default: devshop.local              : ok=36   changed=27   unreachable=0    failed=1
==> default: Loading composer repositories with package information
==> default: Installing dependencies (including require-dev) from lock file
==> default: Nothing to install or update
==> default: Generating autoload files
==> default: ╔═════════════════════════════════════════════════════════════════════╗
==> default: ║ It appears something failed during installation.                    ║
==> default: ║ There is no '/var/aegir/.drush/hostmaster.alias.drushrc.php' file.  ║
==> default: ╚═════════════════════════════════════════════════════════════════════╝

**Comment by niccolox** [comment]
just retried on Vagrant, failed, apache is installed at devshop.local ... but no devmaster ui login (unlike Proxmox and DO)

note, the Proxmox is running on my main home server under Vmware Workstation bridged and has the same network settings as my laptop

obviously, I am not running the Vagrant up on proxmox

so, for me anyways, Vagrant install is broken

  GNU nano 2.2.6                        File: devshop.vagrant.2100.july8.txt                                                        

==> default: ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
==> default:     Downloading: 100%
==> default:   - Installing symfony/process (v2.7.1)
==> default:     Downloading: Connecting...
==> default: ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
==> default:     Downloading: 0%
==> default:
==> default: ^H^H^H^H^H^H^H^H^H^H^H
==> default: ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
==> default:     Downloading: 20%
==> default: ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
==> default:     Downloading: 25%
==> default: ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
==> default:     Downloading: 45%
==> default: ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
==> default:     Downloading: 50%
==> default: ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
==> default:     Downloading: 70%
==> default: ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
==> default:     Downloading: 75%
==> default: ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
==> default:     Downloading: 95%
==> default: ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
==> default:     Downloading: 100%
==> default: symfony/event-dispatcher suggests installing symfony/dependency-injection ()
==> default: symfony/event-dispatcher suggests installing symfony/http-kernel ()
==> default: guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have in$
==> default: knplabs/github-api suggests installing knplabs/gaufrette (Needed for optional Gaufrette cache)
==> default: symfony/console suggests installing psr/log (For using the console logger)
==> default: Generating autoload files
==> default: ╔═════════════════════════════════════════════════════════════════════╗
==> default: ║ It appears something failed during installation.                    ║
==> default: ║ There is no '/var/aegir/.drush/hostmaster.alias.drushrc.php' file.  ║
==> default: ╚═════════════════════════════════════════════════════════════════════╝

**Comment by jonpugh** [comment]
When you've been vagrant upping more than once it can fail if the ~/source/devmaster-0.x/sites/devshop.local folder is present.  

Remove that folder and try again.

Alternatively, set `vagrant_development` to false in vars.yml and it won't mount a host folder at all.

We should figure out how to remove that folder on `vagrant destroy`, or perhaps default `vagrant_development` to false to mitigate this issue...

Sorry for your troubles! 

 Just to confirm, you've gotten it to work everywhere but vagrant?

Thanks.

**Comment by niccolox** [comment]
I realized that nfs server was not starting because I had nothing in exports, but I added a dummy, empty nfs share and started nfs.. and destroyed everything and it still failed

so, I destroyed everything and started again (after clearing out /etc/hosts, /etc/exports) and also turned off vagrant_development and it worked

YAY for that

yes, DO and Proxmox kvm local did install OK.. but did throw a bunch of errors that threw me off

**Comment by niccolox** [comment]
I think I worked it out, haven't tested it yet

I have Squid setup, and bare metal servers (and KVM running on Proxmox locally) seem to handle the proxy seemlessly

Vagrant chokes, as does LXC

I could do this for Vagrant 

https://github.com/tmatilai/vagrant-proxyconf

but, instead I just pressed pause on that Squid proxy

**Comment by niccolox** [comment]
I suspect its this https://github.com/mitchellh/vagrant/issues/3341

drupal-vm now works... havent checked devshop

vagrant plugin install vagrant-vbguest
