### ISSUE TITLE
Project settings edit form validation fails

### ISSUE THREAD

**Issue by a-fro** [opendevshop/devshop#190]
When trying to edit the project settings of an existing project, I get the following errors: 

`
    Another project already has this code path. Code path must be unique.
    Another project already has this base url. Base URL must be unique.
`

This appears to be coming from `devshop_projects_validate`, in the forms.inc file of devshop_projects. The comment before that function states: "This function is no longer used since we have a ctools wizard for project creation."

**Comment by jonpugh** [comment]
We've fixed this up.

Thanks, @a-fro !
