### ISSUE TITLE
Sync data Drupal 8 issues

### ISSUE THREAD

**Issue by arttus** [opendevshop/devshop#191]
On Drupal 8.2.7 ran into the following issues with sync data.

error
Drush command terminated abnormally due to an unrecoverable error.
Error: Call to undefined function cache() in /var/aegir/.drush/commands/registry_rebuild/registry_rebuild.drush.inc, line 146

error
The external command could not be executed due to an application error.
warning
The following module is missing from the file system: standard bootstrap.inc:236

error
`cache-clear all` is deprecated for Drupal 8 and later. Please use the `cache-rebuild` command instead.

error
`cache-clear all` is deprecated for Drupal 8 and later. Please use the `cache-rebuild` command instead.
 Details

**Comment by jonpugh** [comment]
Thanks, will look into this.

**Comment by jonpugh** [comment]
I want to add behat tests for syncing so at least we know it works with drupal core install.

**Comment by jonpugh** [comment]
I am deprecating Sync Data for environment reinstall.

Users that need environment to environment database copies can use drush.
