### ISSUE TITLE
adding a server results in error

### ISSUE THREAD

**Issue by llwp** [opendevshop/devshop#197]
after adding a server in "servers" all sites are showing default Apache:
"Apache2 Ubuntu Default Page"

including all projects and devmaster itself

**Comment by llwp** [comment]
Not ideal; but this works:
```
devshop upgrade
```
from the devmaster directory as (sudo) `root`

**Comment by jonpugh** [comment]
Yeah, I forget exactly how but if your server name returns localhost, it will think it should be server_master and overwrite the symlink from /var/aegir/config/apache.conf to /var/aegir/config/SERVERNAME/apache.conf.

So don't add more than one server node with a title that resolves to 127.0.0.01
