### ISSUE TITLE
Separate, files and DB sync data tasks

### ISSUE THREAD

**Issue by arttus** [opendevshop/devshop#198]
I've ran into a use case where i would like to deploy only the files directory from one environment, to the new environment, but at least from appearances doing so would destroy the targets existing database.

**Comment by llwp** [comment]
👍

**Comment by jonpugh** [comment]
Hmm ok, good point. We'll have to use #states to change how things appear.
Thanks

**Comment by jonpugh** [comment]
This would not be hard for someone that wanted to contribute. 

It's not devshop code: See https://www.drupal.org/project/hosting_tasks_extra

**Comment by jonpugh** [comment]
Deprecating Sync.

Thanks!
