### ISSUE TITLE
PHP OPcode caching

### ISSUE THREAD

**Issue by arttus** [opendevshop/devshop#199]
Should Devshop include OPcode caching out of the box?

As of Drupal 8 enabling PHP OPcode caching is recommended and we even get this warning on the status page.

PHP OPcode caching can improve your site's performance considerably. It is highly recommended to have OPcache installed on your server.

**Comment by jonpugh** [comment]
I suppose testing will be faster? :)

**Comment by jonpugh** [comment]
Nope. Tests run slower, actually!

Are there more vars we need to set here?

Cc: @madalinignisca @geerlingguy @arttus

**Comment by geerlingguy** [comment]
Can you get a phpinfo or do `php -i` in CLI and see if it reports opcache is on?

**Comment by jonpugh** [comment]
Thanks for the reply @geerlingguy !  

I've added the php -i call to the tests. We'll see!

**Comment by jonpugh** [comment]
:point_down:

**Comment by jonpugh** [comment]
I've decided opcode cache should not be on by default. 

We can document how to enable it on a per-server basis using ansible role & variables
