### ISSUE TITLE
Drupal 8 composer install issues.

### ISSUE THREAD

**Issue by arttus** [opendevshop/devshop#200]
This might just be a clarification needed on some of the help text in the UI, but also I think there might be an issue with composer install when it automatically runs.

DevShop version 1.x aef5fa1  self updated yesterday.

projects/add/git_url has the following line of instructions 

'If a composer.json file is found in the root of the project, composer install will be run automatically.'

However if i just hit next from this page, i get the following error

`Drush command terminated abnormally due to an unrecoverable error.
Error: require(): Failed opening required '/var/aegir/projects/d8/live/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/aegir/projects/d8/live/autoload.php, line 14
The external command could not be executed due to an application error.`

If instead, I hit next and go to Deployment hooks and then check

'Run composer install.'

hit next and add an environment and hit next again, composer install runs, but I end up with the following errors.

'Running git status
git status
fatal: Not a git repository (or any of the parent directories): .git
error
Process Failed'

I checked the deployed code, there is still a .git directory, but environment and project creation has not completed.

If instead of allowing devshop to automatically run composer install i create the environment and then run composer install from the CLI, I am left with a working git directory, but again project creation has not fully completed and i'm left with partially working environment but not a working Drupal 8 site.

**Comment by arttus** [comment]
clarification, i just tried checking composer install on a different build of devshop "DevShop version 1.x d87e801" and ran with no "fatal: Not a git repository" issues.

going to check from a fresh install.

**Comment by rogical** [comment]
still same issue

**Comment by rogical** [comment]
![image](https://user-images.githubusercontent.com/1172002/29151317-f7d04c40-7db2-11e7-93ce-e06f22e1a175.png)
works by checkon this

**Comment by jonpugh** [comment]
The latest provision includes automatic `composer install` if a `composer.json` file is found.

That hook option will be removed. After research, we noticed running `composer install` a second time only takes < 1s, so we decided to go ahead and code it to run on every Platform or Site verify task.
