### ISSUE TITLE
Provision install task fails with Github PRs

### ISSUE THREAD

**Issue by a-fro** [opendevshop/devshop#201]
This is on a fresh install of 1.x. The details of the failure show:
`Command provision-install needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.`
`The drush command 'provision-install' could not be executed.`

If I ssh into the server, I see that the git repo was cloned to folder I have set as the Drupal docroot, which is why drush can't find the Drupal root. Looking at the code of `devshop_projects.drush.inc`, it appears that the following loop should have dealt with this: 

```
  $root = $platform->publish_path;
  $git_ref = $platform->environment->git_ref;

  $git_remote = $platform->project->git_url;
  $drupal_path = $platform->project->drupal_path;

  //Remove drupal_path to clone.
  if ($drupal_path) {
    $root = str_replace($drupal_path, '', $root);
  }
```

I can see in the database that the drupal_path is correctly set. Any idea where to look to fix this issue? Is it possibly related to https://github.com/opendevshop/devshop/issues/185?

**Comment by jonpugh** [comment]
Thanks for reporting this, @a-fro ... It is the last remaining bug in the migration to hosting_git.

I will be working on this today.

**Comment by a-fro** [comment]
Thanks @jonpugh. And congrats on the migration! As I mentioned on gitter, the `repo_url` column is blank in the hosting_git table for this branch, which seems likely related. Please let me know if there is anything else you'd like me to do to help.

**Comment by jonpugh** [comment]
This should be all fixed up in 1.x, @a-fro !

Thanks for your patience.

**Comment by a-fro** [comment]
Thanks @jonpugh. I pulled the most recent version (Commit #50261a2f44b14e33b2a348b4dd125a970915c5c4) into devmaster and confirmed the code was there. I then cleared cache from the devshop gui and created a pull request, but I ran into the same issue.  Am I missing something?

**Comment by a-fro** [comment]
@jonpugh ran through a fresh install of devshop last week. This is still an issue, and unfortunately is preventing us from continuing to use devshop. If there is a way to work with you to fix the issue, I'd be happy to. I appreciate everything you've done!

**Comment by jonpugh** [comment]
Happy to help! 

I'll be online a bit this afternoon, can you hang out in https://gitter.im/opendevshop/devshop and I'll ping you when I'm around?

thanks!

**Comment by jonpugh** [comment]
Ok, I think we can FINALLY call this one closed thanks to: https://github.com/opendevshop/devmaster/commit/da9b17710e0f9c738fc13ec2196936962504265f

Thanks a ton for your patience, @a-fro and for pointing this out.
