### ISSUE TITLE
Aegir-generated settings files for new environments using the wrong profile

### ISSUE THREAD

**Issue by a-fro** [opendevshop/devshop#202]
I created a fresh install of devshop using the 1.x branch. I then created a project that tracks a public github repo with a custom install profile. New environments are set to be created as a clone of the live environment, which was installed and is running the custom profile.

However, the automatic PR creation fails (see https://github.com/opendevshop/devshop/issues/201), as does manual environment creation. The error is `WD menu: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbname.rdf_mapping' doesn't exist:...`. 

If I manually change the values in settings.php to my custom install profile, then go into the system table in the database and enable the custom profile, the site works. However, "Retry" does not and devshop reports that the site install failed. How does aegir decide what the install profile value should be? It's set correctly in the project settings.

```
$profile = "standard"; // change to custom profile
$install_profile = "standard"; // change to custom profile
...
$conf['install_profile'] = 'standard'; // change to custom profile

**Comment by jonpugh** [comment]
So sorry for the delay on this, I think we fixed this after talking today?

We fixed manual environment creation some time ago, but clones of a site with a custom profile, just fixed today: https://github.com/opendevshop/devmaster/commit/da9b17710e0f9c738fc13ec2196936962504265f

@a-fro Can you confirm this issue is now resolved?

**Comment by jonpugh** [comment]
Please re-open if you find it is still an issue.

**Comment by a-fro** [comment]
Hey @jonpugh. This is, indeed fixed. I still have to manually update the db to set the profile (cloning from an existing site doesn't work), but I think you're aware of that bug. I created a custom drush command to set the profile correctly and added it as an environment hook.

**Comment by jonpugh** [comment]
ok @a-fro I fixed this one too.

You should now be able to clone environments with custom profile, and the profile gets saved in the new site node.
