### ISSUE TITLE
Allow developers to configure the command to run for "Run Tests" tasks.

### ISSUE THREAD

**Issue by aussielunix** [opendevshop/devshop#203]
Given we are using `devmaster-1.0.0-beta10`
And we have a directory `tests/` in our Drupal 7 repo
And it contains `composer.json`
`composer install` will install everything in `tests/vendor`
This means the PATH to behat is `tests/vendor/bin/behat`
https://github.com/opendevshop/devmaster/blob/1.x/modules/devshop/devshop_projects/drush/test.provision.inc#L82 does not look in the vendor directory.

Locally I have made the following change and my tests now run.
`$full_behat_bin_path = $repo_path . '/' . $behat_folder_path . '/vendor/bin/behat';`

**Comment by jonpugh** [comment]
I think we have fixed this in 1.x, but we should add this use case to our behat tests to ensure behat test running

**Comment by jonpugh** [comment]
Hmm, does that mean we do need a separate option for path to bin/behat? It's always in bin/behat for me, not vendor...

**Comment by aussielunix** [comment]
maybe or just have an array of places to look for behat ?

`['bin/behat', 'vendor/bin/behat'] ?`

**Comment by jonpugh** [comment]
We should handle this smartly, I agree looking for those two files is probably the best route.

**Comment by jonpugh** [comment]
:point_down:

**Comment by jonpugh** [comment]
What is really needed is a way to store the command to use in the app codebase itself.

That way the developers can just push the change and the tests run.

**Comment by jonpugh** [comment]
This is being considered in the modernization I am doing.

Something like

```
commands:
  build: composer install --dev
  install: bin/drush site:install
  test: composer test
  deploy: composer deploy
```

**Comment by jonpugh** [comment]
This is now implemented by the `devshop/deploy` plugin I've developed in #591 .

This is a simple framework for defining standard "stages" of your deployment in your composer.json file.

The purpose of stages is to easily modify what happens on every deploy.

**Comment by jonpugh** [comment]
more coming soon.
