### ISSUE TITLE
New environments are created without group write permission - Release 1.0.0-beta10

### ISSUE THREAD

**Issue by shreddedbacon** [opendevshop/devshop#205]
When creating an environment inside a project, environments are missing g+w.
This prevents running DATA->DEPLOY DATA FROM->other environments from rsyncing correctly and the task fails with:
Could not rsync from /var/aegir/projects/test1/preprod/sites/preprod.test1.devshop.local/files/ to /var/aegir/projects/test1/qa/sites/qa.test1.devshop.local/files/

Manually adding g+w to the destination directory allows the task to succeed:
aegir@devshop ~/projects/test1/qa/sites (qa=) $ ll
total 32
drwxrwxr-x  5 aegir aegir 4096 Jun 14 06:52 ./
drwxrwxr-x 11 aegir aegir 4096 May 30 03:36 ../
drwxrwxr-x  7 aegir aegir 4096 May 16 23:12 all/
drwxrwxr-x  2 aegir aegir 4096 May 15 21:43 default/
-rw-rw-r--  1 aegir aegir 2365 May 15 21:43 example.sites.php
drwxr-xr-x  7 aegir aegir 4096 Jun 14 06:52 qa.test1.devshop.local/ 
-rw-rw-r--  1 aegir aegir  904 May 15 21:43 README.txt
-rw-r--r--  1 aegir aegir 1714 Jun 14 06:52 sites.php
aegir@devshop ~/projects/test1/qa/sites (qa=) $ chmod g+w qa.test1.devshop.local/
aegir@devshop ~/projects/test1/qa/sites (qa=) $ ll
total 32
drwxrwxr-x  5 aegir aegir 4096 Jun 14 06:52 ./
drwxrwxr-x 11 aegir aegir 4096 May 30 03:36 ../
drwxrwxr-x  7 aegir aegir 4096 May 16 23:12 all/
drwxrwxr-x  2 aegir aegir 4096 May 15 21:43 default/
-rw-rw-r--  1 aegir aegir 2365 May 15 21:43 example.sites.php
drwxrwxr-x  7 aegir aegir 4096 Jun 14 06:52 qa.test1.devshop.local/
-rw-rw-r--  1 aegir aegir  904 May 15 21:43 README.txt
-rw-r--r--  1 aegir aegir 1714 Jun 14 06:52 sites.php

**Comment by shreddedbacon** [comment]
Any ideas on how this could be fixed more permanently. New projects/environments are impacted by it.

**Comment by shreddedbacon** [comment]
Turns out this lives in the provision command for drush in this file:
.drush/commands/provision/platform/provision_drupal.drush.inc
http://cgit.drupalcode.org/provision/tree/platform/provision_drupal.drush.inc#n194

Changing it to 0775 fixes.

**Comment by jonpugh** [comment]
Sorry for the late reply.  

You found the issue: this is how Provision itself works. 

I recently tested "Fix Permissions" and "Fix Ownership" modules now included in Aegir core. I recommend you install those and let us know how that works?

See https://github.com/drupalprojects/hosting_tasks_extra/tree/7.x-3.x/fix_ownership

If it works well for you I can include these modules in the next release of devshop.

We should also put these scripts directly in Aegir core, IMHO.

**Comment by jonpugh** [comment]
I'd like to solve this by enabling fix_ownership and fix_permission modules until we get this functionality in provision itself.

However to do that we need to modify the server:

1. [ ] Add to https://github.com/aegir-project/dockerfiles

**Comment by jonpugh** [comment]
@shreddedbacon See PR opendevshop/devmaster/pull/85

**Comment by Pls** [comment]
For those that are having same problem these are steps to fix issue with current DevShop:

1. Enable Fix Permissions, Fix Ownership modules.
2. SSH to your VM as root.
3. Execute `cd /var/aegir/devmaster-1.3.4/profiles/devmaster/modules/aegir/hosting_tasks_extra/fix_ownership' command.
4. Run `sudo bash scripts/install.sh`.
5. Execute `cd /var/aegir/devmaster-1.3.4/profiles/devmaster/modules/aegir/hosting_tasks_extra/fix_permissions' command.
6. Run `sudo bash scripts/install.sh`.

Congrats, you have deployments system to pull DB & files from any environment. Love this feature, BTW! Cheers to @jonpugh, I now more and more Love DevShop as it includes all the Aegir awesomness with beautiful Frontend magic ;)

**Comment by jonpugh** [comment]
Fix Perms and ownership was added.
