### ISSUE TITLE
Can't install on fresh CentOS 7 server

### ISSUE THREAD

**Issue by zietbukuel** [opendevshop/devshop#211]
I tried installing it on a fresh CentOS 7 VPS server, but I got this message:

```
[DEPRECATION WARNING]: Specifying include variables at the top-level of the task is deprecated. Please see:
http://docs.ansible.com/ansible/playbooks_roles.html#task-include-files-
and-encouraging-reuse

 for currently supported syntax regarding included files and variables. This feature will be removed in a future release. Deprecation warnings can be disabled
 by setting deprecation_warnings=False in ansible.cfg.
ERROR! 'check_mode' is not a valid attribute for a Task

The error appears to have been in '/etc/ansible/roles/geerlingguy.apache/tasks/main.yml': line 20, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# Figure out what version of Apache is installed.
- name: Get installed version of Apache.
  ^ here
 Ansible syntax check failed! Check installers/ansible/playbook.yml and try again.
```

Tried again, but same results. Am I missing something maybe?

**Comment by jonpugh** [comment]
Hmm, I suppose we'll have to fix that part of the playbook. In the meantime, you can edit your ansible config as suggested in the error message, it should allow you to proceed?

**Comment by jonpugh** [comment]
I've started getting centOS 7 install script testing going again in https://github.com/opendevshop/devshop/pull/196

**Comment by jonpugh** [comment]
RedHat family testing needs to be re-enabled. Boosting prriority

**Comment by jonpugh** [comment]
However, this issue isn't about that.

It failed because of the syntax error. No way to tell what playbook you had at the time, but this is fixed.

Thanks!

**Comment by jonpugh** [comment]
See #347 for reimplementing redhat family testing
