### ISSUE TITLE
Trigger branch environments to update code from default branch whenever code is merged.

### ISSUE THREAD

**Issue by josebc** [opendevshop/devshop#218]
Im currently facing a scenario in wich devshop is required to pull code on pull request merge, bitbucket is replying with "pullrequest:fulfilled" wich is not handled by the module (API change maybe?)
Will be creating a PR for the option of pull on PR merge on Bitbucket
Please add any comments on a better way to handle it if you have

**Comment by jonpugh** [comment]
When I use GitHub, a merge triggers multiple webhooks, including a "push" action including the branch just merged. This triggers the default "deploy" for any environment on that branch.

Are you saying bitbucket does not send a push notification on PR merge?  If so I guess we need this, but I'd like to confirm to be sure.

**Comment by jonpugh** [comment]
:point_down:

**Comment by jonpugh** [comment]
I am re-imagining how we update code on servers: 

The RemoteReset component will be a small script that watches a git repos upstream for new commits, and triggers commands the moment those commits are available.

This issue gave me an idea: RemoteReset could allow for additional branches to watch and could trigger merges from those branches automatically.
