### ISSUE TITLE
Aegir Hosting Git  module need update

### ISSUE THREAD

**Issue by rogical** [opendevshop/devshop#221]
![image](https://user-images.githubusercontent.com/1172002/28702861-7c64281c-7392-11e7-850d-7366a8e71f5b.png)

**Comment by jonpugh** [comment]
@rogical Actually 3.11 is much older than the installed version... What we need is to make a new release for Hosting Git...

I will do this soon.

**Comment by jonpugh** [comment]
New release of Aegir and DevShop is out.
