### ISSUE TITLE
Installation on Ubuntu 14.04 with option Nginx installes but shows 'Welcome to Nginx!'

### ISSUE THREAD

**Issue by Corvalan** [opendevshop/devshop#227]
After installation using the script on Ubunto with the Nginx option, the url says
Welcome to Nginx!

So apparently this does not work yet.
The login URL generated after installation, gives a page not found error.

Up to now none of the installations have worked on debian, centos or ubuntu using the Nginx option.

**Comment by jonpugh** [comment]
Yup, this is now confirmed in the PR https://github.com/opendevshop/devshop/pull/162

Apache tests pass, NGINX do not.

Prioritizing this for RC1

**Comment by jonpugh** [comment]
We're going to reimplement nginx into the automated tests in #348

**Comment by jonpugh** [comment]
We don't support nginx or ubuntu14 any longer.

Thanks
