### ISSUE TITLE
How to run devshop on docker

### ISSUE THREAD

**Issue by yaazkal** [opendevshop/devshop#229]
Hi, maybe I'm too new in this two worlds: docker and devshop and maybe my question can be pretty silly; but really I can't find documentation about the right way to do it or caveats to have in mind about running devshop using docker. So this issue is about what I found as an extra steps (that are not documented) and is also a question because at the end it didn't worked for me. Maybe is not supported at this time.

I'll try to document here step by step what I'm doing to see what is the wrong thing I'm doing (or the thing I'm missing), or if it is any bug already.

My machine: Windows 10 Pro, Docker 17.06.2-ce-win27 (stable)

I followed the instructions [here](https://hub.docker.com/r/devshop/devmaster/), So I ran:

`docker pull devshop/devmaster`
`docker run --name database -d -e MYSQL_ROOT_PASSWORD=password mariadb`
`docker run --name devshop --hostname devshop.local.computer -e MYSQL_ROOT_PASSWORD=password --link database:mysql -p 80:80 devshop/devmaster`

And it just work, yay! except that if I try to create a project from a private repo I have no ssh public key to add to my account in order to authorize it because the system didn't generate it. So, to get the key:

Login to the container
`docker exec -it devshop bash`
generate the key
`ssh-keygen`
copy the key to devmaster configuration
`drush @hostmaster vset devshop_public_key "$(cat ~/.ssh/id_rsa.pub)" --yes`

I added they key to my Git server account (I tried with GitHub and with Bitbucket) and also it didn't worked.
The platform creation trhow an error. I found it was because the lack of trust between the container and the server, so I enter again the container and run the same command that devmaster was trying to run:
`git ls-remote <repo-url>`
So I answered yes to the question about continuing the connection in order to add the server to the known host file.

I then try to reverify the platform and now there is a new error, searching the issue queue I found #185 and looks weird because seems to be an old issue (closed) but just for curiosity I checked the files and to my surprise there where as described, so I applied the patch, flush caches and try again and the error persist. Tried many things (different repo, D7 repo with a make file, D8 repo with a composer.json file, even creating a .hook file in the repo to run drush make after pull, etc), but nothing.

Now, I tried a bit more an attempted to do it again but starting from zero, except that I was gonna try the `docker-compose` method. I just "translate" what I used in the command line as a `docker-compose.yml` file as is documented [here](https://hub.docker.com/r/devshop/devmaster/) but that ends up being a mess, this time devmaster didn't get installed and I found [this error](https://gist.github.com/yaazkal/2392a7f57fe9d52e8e1f084765858f1b). Even I tried again after a docker reset in order to have no images and no containers and same error.

 So I go the 1.x branch and looked the `docker-compose.yml` file, use it as a template doing the corresponding modifications and same error.

This error disapear and devshop is installed as described below only if I remove `volumes` from the docker-compose file. I check permissions on my system and even I can see that the script creates the files on my folders, I don't know if is a docker bug or maybe files are not getting correct permissions (like execution) maybe because host os is windows, I don't know.

At the end I was able to run OpenDevShop just if I created the containers manually or using the docker-compose file but without volumes in the devshop container. Anyway I was not able to use it (create projects).

Thanks

_Update 09/09/17:_ Fix an error reference and pointed to a gist. Also make a note about that error.

**Comment by yaazkal** [comment]
Maybe I was doing the part of installing platforms from git wrong, I was supossing that with a composer.json file the system will automatically throw `composer install` and also I was supossing the same with make files.

Seems that DevShop don't work the way I was testing, all Drupal files must reside in the repository even if there is a composer.json file: https://github.com/opendevshop/devshop/issues/117#issuecomment-220303168

I test it with a drupal repo and it works.

Anyway, I'll left my step by step post just for the record, maybe someone is trying to install it and is not aware of the extra steps.

**Comment by yaazkal** [comment]
> This error disapear and devshop is installed as described below only if I remove volumes from the docker-compose file. I check permissions on my system and even I can see that the script creates the files on my folders, I don't know if is a docker bug or maybe files are not getting correct permissions (like execution) maybe because host os is windows, I don't know.

Maybe this is a windows docker issue. I tried today using aegir on composer, it stalled everything succesfully and I can log in to the aegir control panel, I use a volume to map the platforms folder and tried to create a platform but it fails.

```
SUCCESS Platforms path /var/aegir/platforms exists. 
ERROR Platforms ownership of /var/aegir/platforms could not be changed to aegir.
SUCCES Platforms permissions of /var/aegir/platforms have been changed to 755.
SUCCES Platforms path /var/aegir/platforms is writable.
```

This is because from the container perspective the platforms folder is owned by root and even if I go to the container and chown it to aegir the owner is still root.
Maybe this is because why the devshop failed to install too.

Not sure if aegir or devshop should ommit that part (check the owner) if the script is runned inside a container (?). Because anyway it can read/write the folder that is in the volume.

**Comment by jonpugh** [comment]
@yaazkal You can resolve your issues by building a container using your host's UID.

If the aegir UID and your host UID match, the files are owned by aegir inside the container .

I haven't tried this yet on windows. You have to know your UID. Are you using the Bash ubuntu system on windows? or docker itself...

You can use this Dockerfile and edit row 20 to be `ENV AEGIR_UID 1000` replacing 1000 with your UID. 
https://github.com/aegir-project/dockerfiles/blob/master/Dockerfile

**Comment by yaazkal** [comment]
@jonpugh I'm using docker itself directly on windows and with powershell, when I use WSL, I just use the docker client trough a port to the windows docker service.

I'll try to use the UID as you said and try again.

Thanks

**Comment by jonpugh** [comment]
@yaazkal I should have noted, this is only really a problem because you are mounting the volume "locally"... if you just ran the container without the volume mappings, it should run fine?

**Comment by yaazkal** [comment]
@jonpugh yes, the container runs fine. Seems to be a well known issue that Docker for Windows volumes is a like a work in progress still.

Just that I wanted, as you said, locally; so I can edit files on my machine code editor directly, but it is a development workflow I was trying because if it is local, I don't get a way to use the git web triggers from github or bitbucket (well, unless I open publicly some ports). Maybe not exactly the way DevShop is designed for, so my fault.

Anyway I'm gonna try later again (with more time) and see if I can change my dev workflow.

As I mentioned before, this issue is more like to document "known issues" if anyone is trying to run devshop on Docker.

>but really I can't find documentation about the right way to do it or caveats to have in mind about running devshop using docker. So this issue is about what I found as an extra steps (that are not documented)
