### ISSUE TITLE
Upgrading devshop when user is not aegir or installed in standard location /var/aegir

### ISSUE THREAD

**Issue by shreddedbacon** [opendevshop/devshop#247]
@jonpugh Is there a way to upgrade devshop/devmaster without using `devshop upgrade`
If devshop has been installed to run under a user that is not aegir, or in the standard /var/aegir directory `devshop upgrade` fails

**Comment by jonpugh** [comment]
devshop upgrade is just a wrapper for `drush hostmaster-migrate` and an ansible run.

You can run `drush @hostmaster hostmaster-migrate` manually to get the same effect.

We should fix the hardcoded path and user in this command before 1.x

**Comment by shreddedbacon** [comment]
Ah cheers! I'll look into hostmaster-migrate.

**Comment by jonpugh** [comment]
On second thought, the upgrade and install should respect Ansible inventory variables. It's possible the devshop:upgrade command doesn't... Would have to look into the CLI code.

If you want to explore, see UpgradeCommand.php

**Comment by shreddedbacon** [comment]
Jon, I've been fiddling around with this and I'm getting stuck on a few things. Since I'm not using the standard deployment or upgrade, using hostmaster-migrate works, but I'm hitting some pain points with hardcoded paths inside certain modules.

I'm not using aegir user, and I'm not using /var/aegir as the path because I am using BOSH as the deployment tool and using it to fit into 

I've resorted to running the following after install/upgrades.
```
# Fix SSH key stuff in devmaster to not use /var/aegir bu /home/vcap
sed -i 's~/var/aegir/.ssh/authorized_keys~/home/vcap/.ssh/authorized_keys~g' /var/vcap/store/aegir/devmaster*/profiles/devmaster/modules/aegir/aegir_ssh/aegir_ssh.drush.inc
# Fix DRUSH alias remote-user
sed -i 's~aegir~vcap~g' /var/vcap/store/aegir/devmaster*/profiles/devmaster/modules/aegir/hosting_tasks_extra/hosting_drush_alias/hosting_drush_alias.module
# Fix backup export location
sed -i 's~/var/aegir/~/var/vcap/store/aegir/~g' /var/vcap/store/aegir/devmaster*/profiles/devmaster/modules/aegir/hosting_site_backup_manager/hosting_site_backup_manager.module
```
Everything runs smooth right up to the end of hostmaster-migrate where this errors, because it is looking for /var/aegir. It doesn't have any issues with the actual upgrade, just the ssh keys don't get fixed up til I run the replace commands to fix the paths and then verify hostmaster again.
```
[aegir_ssh] server verify...                                                                                                                                                                                                       [ok]
[aegir_ssh] 2 ssh keys found                                                                                                                                                                                                       [ok]
file_put_contents(/var/aegir/.ssh/authorized_keys): failed to open stream: No such file or directory aegir_ssh.drush.inc:50                                                                                                        [warning]
[aegir_ssh] COULD NOT write ~/.ssh/authorized_keys!
```
This is fine, but since I can override the installation path when doing a devshop install, I would hope that these things would pick up the paths from somewhere else rather than rely on them being hardcoded.

**Comment by jonpugh** [comment]
I've always hoped to ensure the username is changable, but knew it could be a lot of work.

Still needs to happen at some point.

**Comment by jonpugh** [comment]
Closing this bug report. Work will continue in #525
