### ISSUE TITLE
Problem with PUBKEY

### ISSUE THREAD

**Issue by cnovick** [opendevshop/devshop#248]
Installing on docker using install.sh:

TASK [opendevshop.aegir-user : Ensure openssh-client is available (including ssh-keygen tool)] ****************************************************************
fatal: [7f69d128e31b]: FAILED! => {"changed": false, "cmd": "apt-get update", "failed": true, "msg": "W: GPG error: http://ppa.launchpad.net/ansible/ansible/ubuntu artful InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 93C4A3FD7BB9C367\nE: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu artful InRelease' is not signed.", "rc": 100, "stderr": "W: GPG error: http://ppa.launchpad.net/ansible/ansible/ubuntu artful InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 93C4A3FD7BB9C367\nE: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu artful InRelease' is not signed.\n", "stderr_lines": ["W: GPG error: http://ppa.launchpad.net/ansible/ansible/ubuntu artful InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 93C4A3FD7BB9C367", "E: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu artful InRelease' is not signed."], "stdout": "Hit:2 http://deb.debian.org/debian testing InRelease\nHit:3 http://cdn-fastly.deb.debian.org/debian sid InRelease\nGet:1 http://ppa.launchpad.net/ansible/ansible/ubuntu artful InRelease [15.9 kB]\nErr:1 http://ppa.launchpad.net/ansible/ansible/ubuntu artful InRelease\n  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 93C4A3FD7BB9C367\nReading package lists...\n", "stdout_lines": ["Hit:2 http://deb.debian.org/debian testing InRelease", "Hit:3 http://cdn-fastly.deb.debian.org/debian sid InRelease", "Get:1 http://ppa.launchpad.net/ansible/ansible/ubuntu artful InRelease [15.9 kB]", "Err:1 http://ppa.launchpad.net/ansible/ansible/ubuntu artful InRelease", "  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 93C4A3FD7BB9C367", "Reading package lists..."]}

**Comment by jonpugh** [comment]
Classic ppa/internet hiccup. Please try stain, should be fine.
