### ISSUE TITLE
Better documentation and user experience for setting up "subdirectory" domains

### ISSUE THREAD

**Issue by rogical** [opendevshop/devshop#249]
for example:

www.example.com/site1/
www.example.com/site2/
www.example.com/site3/

**Comment by rogical** [comment]
mapping in sites.php

**Comment by jonpugh** [comment]
This is a good feature of Aegir, but it is poorly documented.

We should improve the user experience of setting this up.

**Comment by jonpugh** [comment]
This could be easier when we have multiple vhosts per site ....
