### ISSUE TITLE
install.sh linuxmint os not known

### ISSUE THREAD

**Issue by Tdnshah** [opendevshop/devshop#251]
I am using linuxmint OS and want to try locally to setup devshop so i tired running the install.sh using sudo bash install.sh and i get an error saying that

 "OS (linuxmint) is not known, or an install action was not understood.  Please post an issue with this message at http://github.com/opendevshop/devshop/issues/new"

Also When I am trying to run the bash install.sh script as a root user a
```
Hostname: localhost
MySQL Root Password: 6Hg2GhDhbYJX0X1K-8tUTMOBHlBkZs8M
Cloning into '/usr/share/devshop'...
fatal: http://github.com/opendevshop/devshop.git/info/refs not valid: is this a git repository?
Downloads/install.sh: line 250: cd: /usr/share/devshop: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git
---------------------------------------------
 Playbook: /usr/share/devshop/playbook.yml 
 Makefile: /usr/share/devshop/build-devmaster.make 
---------------------------------------------
Downloads/install.sh: line 266: cd: /usr/share/devshop: No such file or directory
Created inventory file.
 Installing ansible roles...
ERROR! Unable to open /usr/share/devshop/roles.yml: [Errno 2] No such file or directory: u'/usr/share/devshop/roles.yml'
```
I get this error and the scripts fails and exit.

**Comment by jonpugh** [comment]
The install.sh script is only designed for ubuntu or centOS/fedora.

While it's possible to install on your laptop, I highly recommend using a VM or docker container instead.

Try this:

1. Install Docker and docker-compose.
2. Install Robo CLI: http://robo.li
3. Clone this repo.
4. Run `robo up`.

Good luck!

**Comment by Tdnshah** [comment]
@jonpugh Actually LInux mint is also a ubuntu based linux distribution.
As u suggested i tried installing opendevshop using ubuntu by using install.sh file and found that the same above error message comes as posted in this issues, I guess the issue is related to this
```
Cloning into '/usr/share/devshop'...
fatal: http://github.com/opendevshop/devshop.git/info/refs not valid: is this a git repository?
Downloads/install.sh: line 250: cd: /usr/share/devshop: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git
```
and also would like to say that is this script specifically made for ubuntu 14.04.
