### ISSUE TITLE
Error while installing libapache2-mod-php5 

### ISSUE THREAD

**Issue by Tdnshah** [opendevshop/devshop#253]
I tried Installing it on our AWS EC2 Dev Ubuntu 16.04 linux server, the server was already running LAMP and few drupal instances.
While Installing i was stuck at two places but could resolve it  as below:- 
1. When  script tries creating an aegir user and assign it a GID of 1000 if the server is already having a GID 1000 then it use to throw the error saying GID already exist, I resolved it by editing the Script and changing the assign ID from 1000 to some random no that dosent exists in our server. 
2. When the script tries to clone the devshop repo at `usr/share/dev` the git repo url in the script is `http://github.com/opendevshop/devshop.git` as this link is not using `https://` I used to get a error sayin fatal no get repo found. I resolved it by editing adding https:// in the git repo url.
3.The third Issue I couldn't resolve is i am getting an error when the script is trying to install apache2 module `libapache2-mod-php5` 
Error:- 
```
TASK [opendevshop.aegir-apache : Include OS-specific variables.] *******************************************************************************************************
ok: [ip-10-10-10-177]

TASK [opendevshop.aegir-apache : Include OS-specific tasks.] ***********************************************************************************************************
included: /home/shah/.ansible/roles/opendevshop.aegir-apache/tasks/Debian.yml for ip-10-10-10-177

TASK [opendevshop.aegir-apache : Install Apache2 PHP Mod.] *************************************************************************************************************
fatal: [ip-10-10-10-177]: FAILED! => {"changed": false, "msg": "No package matching 'libapache2-mod-php5' is available"}
	to retry, use: --limit @/usr/share/devshop/playbook.retry

PLAY RECAP *************************************************************************************************************************************************************
ip-10-10-10-177            : ok=27   changed=0    unreachable=0    failed=1   

M8
-su: devshop: command not found
The command 'devshop status' had an error. Check the logs and try again.

```
I tried changing the name of the php package in `.ansible/roles/opendevshop.aegir-apache/tasks/Debian.yml ` to take `libapache2-mod-php` but this change is not taking any effect and every time i get the same error. Please help me resolve this issue.

**Comment by jonpugh** [comment]
Hi, @Tdnshah ,

I've revived the PR #120 for Ubuntu 16.04 support.

Final tests are running now. You can use the install.sh from the `ubuntu16` branch right now to test, if you'd like

**Comment by jonpugh** [comment]
Running install.sh on ubuntu16 works now!

@Tdnshah can you give it a test? 1.x branch install.sh works great.

Thanks!
