### ISSUE TITLE
Improve docs focusing on how to launch devshop as quickly as possible, locally or in the cloud.

### ISSUE THREAD

**Issue by Pls** [opendevshop/devshop#258]
Hello,

Thanks for your work, firstly, it really looks promising and great tool! I am just discovering OpenDevShop and all its features, basically newbie. But I am familiar with Aegir and BOA, so not completely beginner.

What I'm struggling is the steps to install opendevshop locally. Should I use vagrant like Trellis uses or Docker? If Docker is the recommended option, what would be the workflow setting it up locally with all the environments and sites and then pushing all the it to cloud opendevshop?

What would help to understand all the concepts is updated video tutorial from start to end on how to setup OpenDevShop locally, create local server, environments, sites and just basic everyday usage like how GIT would integrate inside ODS, how deploys work. It can be two part - one for all the local stuff, other for setting it all up on DigitalOcean droplet and pushing changes from local to cloud droplet.

I think this type of video tutorial (older videos are somewhat obselete I believe with all the changes) could bring more people into OpenDevShop and spark more action and interest from Drupal people. As people tend to skip things that are hard to install or figure out. One good documentation example would be this one: Trellis for Wordpress complete guide on settings things up locally and server - https://code.lengstorf.com/learn-trellis-wordpress-roots/

Cheers!

**Comment by jonpugh** [comment]
Thank you, we totally agree!

I'll work with @kthull to remedy this soon. I was just about to train him on this very topic. 

Perhaps we could record it and have a little fun knowing we are taking to an audience.

Thanks for the push, and apologies for the delay. 

We will make things better!
