### ISSUE TITLE
Drupal 8.4 requires Drush 8.1.12 or higher

### ISSUE THREAD

**Issue by MarioBaron** [opendevshop/devshop#260]
all Drupal applications 8.4+ must be built using a composer.json. Code updates using Drush will no longer be available as the `pm-update*` functionality is now deprecated in Drush

**Comment by jonpugh** [comment]
If you are talking about the "download modules" feature I am going to be adding composer support soon.

Other than that, what is the issue exactly?

Drush is now the responsibility of the codebase, and we are working on fixing provision support for codevases with drush9 support.

If you can clarify the specific issue you are having, please reopen the issue.
