### ISSUE TITLE
If a git repo has 2 webhooks on the same server, it will creates 2 deployments, 2 run test tasks, etc.

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#269]
If we check the pull request against existing PR payloads we can prevent the double post.

**Comment by Pls** [comment]
@jonpugh Is this the same problem in this issue, let me describe it below.

We have Dev, Live, Stage and push from local to git (master branch, which refers to Live Environment). If all environments have auto deploy enabled, it triggers deploy on all of them, but it should'nt happen I believe. Is it possible to trigger deploy task only to Environment that has branch associated with that push?

I think there is no need to do Deploy and Verify tasks on all Environments, when only one of them actually has new commit. Does it makes sense? And is this separate issue from this one?

**Comment by jonpugh** [comment]
Related #217
