### ISSUE TITLE
vagrant up failure with installers/ansible/playbook.yml file inventory is marked as executable

### ISSUE THREAD

**Issue by Topplestack** [opendevshop/devshop#27]
==> devmaster: ERROR: The file inventory is marked as executable, but failed to execute corr                           ectly. If this is not supposed to be an executable script, correct this with `chmod -x inven                           tory`.
==> devmaster:  Ansible syntax check failed! Check installers/ansible/playbook.yml and try a                           gain.

On Win7 running Cygwin and/or Git Bash

**Comment by jonpugh** [comment]
Not sure why you are seeing the file `installers/ansible/playbook.yml `.  That was moved ages ago.

Please use the latest code from the 0.x branch.

**Comment by Topplestack** [comment]
This is on the 0.x branch. Error only occurs on Windows machines. I know that's a pain, but work won't switch me to a Mac and I'm a front-end dev, so Linux is a bit Adobe challenged. 

Here is more detail about when things begin to unravel:

==> devmaster: Processing triggers for python-support (1.0.15) ...
==> devmaster: ---------------------------------------------
==> devmaster:  Generating new MySQL root password... ld3jZ_STtewl216vxADgD6r-C2                  65tQ9F
==> devmaster: ---------------------------------------------
==> devmaster:  Hostname: devshop.site
==> devmaster:  MySQL Root Password: ld3jZ_STtewl216vxADgD6r-C265tQ9F
==> devmaster: ---------------------------------------------
==> devmaster: ERROR: The file inventory is marked as executable, but failed to
execute correctly. If this is not supposed to be an executable script, correct t                  his with `chmod -x inventory`.
==> devmaster:  Ansible syntax check failed! Check installers/ansible/playbook.y                  ml and try again.
