### ISSUE TITLE
Fresh install of 1.1.2 with nginx on Ubuntu 16.04 results in invalid nginx.conf

### ISSUE THREAD

**Issue by ryantan** [opendevshop/devshop#277]
On a fresh install my nginx.conf has these few lines in the http block:

```
                       '$status $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for"';
```

The http block itself looks like:

```
http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;


    client_max_body_size 64m;

                       '$status $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for"';


    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
```

The installation went through with only 1 error near the end, which is unable to reload nginx, due to this error in the config.

Otherwise, the installation continued to the point where it gave me a login url.

**Comment by Pls** [comment]
Bug confirmed. Removing these lines manually in /etc/nginx/nginx.conf and doing 'service nginx reload' fixes the bug.

Pretty simple bugfix I think, as this code is just looking to remove lines and probably fails that these lines don't match after changes were made to that Ansible role. Will look at it if have some time. Don't have any expierence with Ansible, but looks easy to code.

**Comment by jonpugh** [comment]
See #348
