### ISSUE TITLE
Interactive runs of install.sh, after devmaster install asks for aegir sudo password.

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#279]
If you install manually, by wgetting the install.sh script, you will complete the Devmaster Install Command ansible task, but then it will ask for 

```
[sudo] password for aegir:
```

There is and never shall be an aegir password.

If you CTRL+c out, install.sh continues and `devshop status` runs without fail.

You can can run install.sh again, and it will pass just fine, and it will finish the final steps.

**Comment by jonpugh** [comment]
I think somehow, the sudo config is not being reloaded before the devmaster install happens.

**Comment by Pls** [comment]
Yep, bug confirmed.

**Comment by jonpugh** [comment]
MY GOD.
I'M A FOOL. 

https://github.com/opendevshop/ansible-role-aegir-user/commit/ff0ffcc809b18a1bfa51e185f6b028eaed5af545

:rocket: :guitar: :speak_no_evil:

**Comment by jonpugh** [comment]
Again, a little louder for the people in the back: 

```
tail -f auth.log 
```
