### ISSUE TITLE
Initial environment for a new project doesn't use specified domain

### ISSUE THREAD

**Issue by grantdobbe** [opendevshop/devshop#28]
If I create a new project and specify a domain different from the Devshop server (like for a remote server), the domain I specify is not adopted by the first environment. It is adopted by any other environments I create.

Steps to reproduce, assuming the Devshop domain is production.example.com:
1. Create a new project.
2. Specify a different root domain (e.g. development.example.com) and complete setting up the project.
3. Specify a new subdomain for the initial environment (e.g., bugfixes.development.example.com). The form should list development.example.com as the root domain.
4. Complete the process of setting up the project and environment.
5. In the project dashboard, the complete domain for the initial environment will be bugfixes.production.example.com. 
6. If you set up another environment (e.g., qa.development.example.com) following steps 3 and 4, the complete domain will be what you expect (qa.development.example.com).

**Comment by jonpugh** [comment]
Yep, this is still an issue. I started migrating the field to  "domain name pattern" instead of "base URL" but never fully finished.

The Project Create wizard, Step 3: Environments does not respect project specific domain name pattern.

**Comment by jonpugh** [comment]
Hey look at that, there was a @TODO .  

All fixed in `makefiles` branch. Should be merged this week.

Thanks @grantdobbe!
