### ISSUE TITLE
Unable to set HTTP Basic Auth

### ISSUE THREAD

**Issue by shreddedbacon** [opendevshop/devshop#286]
Running Devshop `v1.1.2`
Using `https_nginx`

When I try to configure an environment with a username and password, nothing happens.
A verify task runs, but I can't see anywhere that it creates a htpasswd file or any configuration for http basic auth.
Once verify completes, the username and password fields remain empty, and no http basic auth is present on the environment.

**Comment by shreddedbacon** [comment]
I'm looking at the following: `devmaster/modules/aegir/hosting_tasks_extra/http_basic_auth/drush/http_basic_auth.drush.inc`
I can see that there is a hook for injecting into nginx, but I don't know how this is used, or if its being called at all.

**Comment by shreddedbacon** [comment]
Just to update, when I click save on adding username and password, I can see the values appear in the `hosting_http_basic_auth` table in the database.
Once the verify task completes, they disappear from the table.
I cannot see any files created in `nginx/passwords.d`

**Comment by shreddedbacon** [comment]
In the environments drush file the following is set, even after saving the username/password and message in the environment
```
  'http_basic_auth_username' => NULL,
  'http_basic_auth_password' => NULL,
  'http_basic_auth_message' => NULL,
  'http_basic_auth_whitelist' => NULL,
```
I modified the code for `hosting_tasks_extra/http_basic_auth/drush/http_basic_auth.drush.inc`
```
function http_basic_auth_provision_nginx_vhost_config($uri, $data) {
  drush_log(dt('http_basic_auth_run'), 'ok');
  drush_log('http_basic_auth_data ' . d()->http_basic_auth_username . 'pass ' . d()->http_basic_auth_password. '.', 'ok');
  $lines = array();
  $user = d()->http_basic_auth_username;
  $pass = d()->http_basic_auth_password;
  drush_log('http_basic_auth_user ' . $user . ' password ' . $pass . '.', 'ok');
```
I can see these logs in the verify task, but no user or pass are populated...
```
http_basic_auth_run | - | ok
http_basic_auth_data pass . | - | ok
http_basic_auth_user password . | - | ok
```

**Comment by jonpugh** [comment]
Thank you so much for this detailed reporting.

I thought it might have been caused by our form alter but since you are seeing the values in the table, it might be a bug in the module itself.

This is definitely critical.

**Comment by jonpugh** [comment]
> Once the verify task completes, they disappear from the table.

The "hosting context import" hook is run at this point. It's possible a bug in the module is not importing the provision context data, or might not be passing it to the provision context at all.

@shreddedbacon we will look into this today, it's related to aegir innards

**Comment by shreddedbacon** [comment]
Let me know if you want me to test anything.

**Comment by shreddedbacon** [comment]
Have you figured out if there is a way to patch this in the interim?

**Comment by jonpugh** [comment]
I'm not sure... I guess you could try dropping some manual Apache config file in there.

@jacintocapote is working on this bug.

Any updates, @jacintocapote ?

**Comment by jacintocapote** [comment]
This was fixed https://www.drupal.org/project/hosting_tasks_extra/issues/2982704 was a problem with node_load function. @shreddedbacon let me know if you have another problem with this or isn't working for you.

**Comment by shreddedbacon** [comment]
Thanks! This patch works for me.
When will this make it into the module properly?

**Comment by jonpugh** [comment]
Great to hear. If you have a drupal.org account, please comment there. I
will apply the patch and release a point release tomorrow.

**Comment by shreddedbacon** [comment]
Done :)
