### ISSUE TITLE
Fresh install of 1.3.4 failing on mac

### ISSUE THREAD

**Issue by StephanieF** [opendevshop/devshop#287]
I'm trying to set up a fresh install of devshop from the install script on a brand new mac.
The script is not recognizing my OS information and cannot complete installation.

shell output:
install.sh                             100%[==========================================================================>]  12.39K  --.-KB/s    in 0.04s   

2018-06-19 10:01:29 (284 KB/s) - ‘install.sh’ saved [12685/12685]

Stephanies-MacBook-Pro:sites stephaniefuda$ bash install.sh
=============================================
 Welcome to the DevShop Standalone Installer 
                   v 1.3.4        
=============================================
 This script must be run as root.  Try 'sudo bash install.sh'.
Stephanies-MacBook-Pro:sites stephaniefuda$ sudo bash install.sh
Password:
=============================================
 Welcome to the DevShop Standalone Installer 
                   v 1.3.4        
=============================================
 OS: 
 Version: 
 Hostname: 
 Web Server: apache
---------------------------------------------
 Installing Ansible...
install.sh: line 187: [: ==: unary operator expected
install.sh: line 187: [: ==: unary operator expected
install.sh: line 208: [: ==: unary operator expected
install.sh: line 208: [: ==: unary operator expected
install.sh: line 208: [: ==: unary operator expected
install.sh: line 208: [: ==: unary operator expected
OS () is not known, or an install action was not understood.  Please post an issue with this message at http://github.com/opendevshop/devshop/issues/new
Stephanies-MacBook-Pro:sites stephaniefuda$

**Comment by jonpugh** [comment]
Install.sh is for Linux only.

Clone the repo, enable docker for Mac, and use `bin/robo up` to get it going on a Mac.
