### ISSUE TITLE
Platform verification throws warning

### ISSUE THREAD

**Issue by caldenjacobs** [opendevshop/devshop#288]
I'm seeing the following error on platform verify:
`trim() expects parameter 1 to be string, array given provision_git.drush.inc:458`

This appears to be an issue with hosting_git. See https://www.drupal.org/project/hosting_git/issues/2971666

**Comment by jacintocapote** [comment]
@jonpugh this was fixed here https://www.drupal.org/project/hosting_git/issues/2971666 as @caldenjacobs  commented. Should we wait for a new version of hosting_git or add the patch to the makefile? What do you think?
