### ISSUE TITLE
How to install a drupal distribution?

### ISSUE THREAD

**Issue by mecmartini** [opendevshop/devshop#29]
I'm trying to install a Drupal distro (Cartaro 7.x-1.9) directly from it's repository without success. Is it possible? How?
I attach the log screen of devhsop.

I'm using devshop 0.5.3

![cartarotest_1](https://cloud.githubusercontent.com/assets/2794938/10993032/faed050e-846b-11e5-959e-92d887d3b285.png)
![cartarotest_2](https://cloud.githubusercontent.com/assets/2794938/10993034/ff2cd306-846b-11e5-86b6-6c68198f569a.png)

**Comment by jonpugh** [comment]
At the moment, devshop requires a git repo with the full Drupal stack in it.

A drupal profile repo won't work.

Download the distribution tar.gz file you want from Drupal.org, extract it, and add it to a different git repository, then add that second git repository as a project.

We will have easier distribution support in the future.

Thanks,
Jon
