### ISSUE TITLE
New servers in cluster have database denied

### ISSUE THREAD

**Issue by shreddedbacon** [opendevshop/devshop#295]
When initially deploying a site with a web cluster of 3 servers, then adding 2 more to the cluster after the site is deployed, the 2 new servers get database access denied because their IP is not recognised by the database server as a valid host.

Is this something that should be handled by a task after adding servers, or verifying a site or platform?

**Comment by jonpugh** [comment]
There is a setting for the database server context you can set, I think setting this to 1 will work:

  'db_grant_all_hosts' => '1',

Look for that in your server_DATABASE.alias.drushrc.php file.

Let me know if it works @shreddedbacon !

This is an Aegir issue... we should submit an issue in Hosting.module.

**Comment by jonpugh** [comment]
@shreddedbacon Did you figure this out? 

Thanks!

**Comment by shreddedbacon** [comment]
I added a work around into the way I was deploying the additional hosts to update the grants to include the new hosts. I haven't spent any time on this since April 2018 though, as this is when I stopped working on my custom deployment of DevShop
