### ISSUE TITLE
Installing v1.3.4 on CentOS 7 fails with PHP fatal error

### ISSUE THREAD

**Issue by JohnConnell** [opendevshop/devshop#299]
`PHP Fatal error:  Can't use method return value in write context in /usr/share/devshop/src/DevShop/Command/DevmasterTest.php on line 61`

`The command 'devshop status' had an error. Check the logs and try again.`

**Comment by philoSurfer** [comment]
@JohnConnell   try with 1.x
That worked for me today in Ubuntu 16 :)

**Comment by philoSurfer** [comment]
forgot to write.. that 1.3.4 was giving me issues.  Pinged Jon about it and he will update the docs I believe to use 1.x instead of an explicit version number.

**Comment by jonpugh** [comment]
That wasn't a CentOS error, specifically, looks more like a PHP version incompatibility.

No longer an issue.

thanks!

**Comment by jonpugh** [comment]
See #347
