### ISSUE TITLE
Install Error with vagrant

### ISSUE THREAD

**Issue by ibakayoko** [opendevshop/devshop#3]
Hello, 

I followed the install process at this https://github.com/opendevshop/devshop/blob/0.x/README.vagrant.md

After running : vagrant up i get the errors below.

I was able to ssh into the box.
L-C0000893:devshop ixb$ vagrant ssh
Welcome to Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Welcome to your Vagrant-built virtual machine.
Last login: Fri Sep 14 06:23:18 2012 from 10.0.2.2
vagrant@devshop:~$ sudo su - aegir

aegir@devshop:~$ drush @hostmaster uli

The drush command '@hostmaster uli' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new          [error]
extensions.
A Drupal installation directory could not be found                                                                                                       [error]

aegir@devshop:~$ drush site-alias
none
platform_hostmaster
server_localhost
server_master

When i browse to http://devshop.local/ i get 
"It works!

This is the default web page for this server.

The web server software is running but no content has been added, yet."

What should be the expected behavior?

Errors from vagrant up

==> default: require_once(./profiles/devmaster/devmaster.profile): failed to open   [warning]
==> default: stream: No such file or directory install_6.inc:183
==> default: Drush command terminated abnormally due to an unrecoverable error.       [error]
==> default: Error: require_once(): Failed opening required
==> default: './profiles/devmaster/devmaster.profile'
==> default: (include_path='.:/usr/share/php:/usr/share/pear') in
==> default: /var/aegir/.drush/commands/provision/platform/drupal/install_6.inc,
==> default: line 183
==> default: The external command could not be executed due to an application         [error]
==> default: error.
==> default: Drush was not able to start (bootstrap) the Drupal database.             [error]
....
==> default: The drush command '@hostmaster provision-verify' could not be found.     [error]
==> default: Run `drush cache-clear drush` to clear the commandfile cache if you
==> default: have installed new extensions.
==> default: A Drupal installation directory could not be found                       [error]
==> default: stdout: Aegir 6.x-1.x automated install script
.....
==> default: Do you really want to proceed with the install (y/n): y
==> default: PHP Fatal error:  require_once(): Failed opening required './profiles/devmaster/devmaster.profile' (include_path='.:/usr/share/php:/usr/share/pear') in /var/aegir/.drush/commands/provision/platform/drupal/install_6.inc on line 183
==> default: 
==> default: Fatal error: require_once(): Failed opening required './profiles/devmaster/devmaster.profile' (include_path='.:/usr/share/php:/usr/share/pear') in /var/aegir/.drush/commands/provision/platform/drupal/install_6.inc on line 183
==> default: 
==> default: FATAL: all hosts have already failed -- aborting
==> default: 
==> default: PLAY RECAP ******************************************************************** 
==> default:            to retry, use: --limit @/root/playbook.retry
==> default: 
==> default: devshop.local              : ok=38   changed=30   unreachable=0    failed=1   
==> default: ╔══════════════════════════════════════════════════════════════╗
==> default: ║ It appears something failed during installation.                                                                ║
==> default: ║ There is no '/var/aegir/.drush/hostmaster.alias.drushrc.php' file.                                     ║
==> default: ╚══════════════════════════════════════════════════════════════╝
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by jonpugh** [comment]
Something likely went wrong during the drush make process.  Look for [error] in the logs further up.  

However, I think  this is probably fixed at this point.  

Please try again with the latest code.

Thanks!
Jon
