### ISSUE TITLE
0.5.4 / Ubuntu 12.04 version of git doesn't support push.default: simple

### ISSUE THREAD

**Issue by laroucheyouth** [opendevshop/devshop#31]
Did a fresh install of 0.5.4 on Ubuntu 12.04. Went to add a new project, and got an error. Looked at the logs and saw this:

Shell Output: error: Malformed value for push.default: simple error: Must be one of nothing, matching, tracking or current. fatal: bad config file line 6 in /var/aegir/.gitconfig Cloning into '/var/aegir/projects/live/test'...

After examining the issue, changing the push.default to upstream was the best option.

Made the change, and the repository cloned properly.

**Comment by jonpugh** [comment]
Thanks for the note. We're supporting 14.04 in the long term.
