### ISSUE TITLE
Platform verification fails if drush is installed via composer at project level

### ISSUE THREAD

**Issue by ericmaster** [opendevshop/devshop#313]
When drush is installed locally as part of the project, platform verification fails because the corresponding alias cannot be found. The command executed is:

```
/var/aegir/projects/[projectname]/dev/web/../vendor/bin//drush --backend=2 @platform_[project]_dev provision-verify 2>&1
```

```
The command could not be executed successfully (returned: [preflight] The alias @platform_[project]_dev could not be found. , code: 0)
```

I had to remove locally installed drush for it to pass, but I use locally installed drush in my local environment. Any ideas or workaround?

**Comment by jonpugh** [comment]
Hi Eric,
Aegir & Provision are explicitly not compatible with Drush 9 when included in the core `composer.json` file.

See https://www.drupal.org/project/provision/issues/2953349

Your options are:

1. Downgrade to drush 8.x in composer.json.
2. Move drush to require-dev, and use `--dev` when running composer install locally. Currently provision does composer install without `--dev`

**Comment by philoSurfer** [comment]
@jonpugh running into this same problem.  Can we control how composer is executed when webhooks are fired off?

**Comment by philoSurfer** [comment]
actually working through this a bit has created a Paradox.

1. we need to explicitly manage Drush version in our composer for our development teams.
2. moving drush to require-dev does nothing as @ericmaster stated, devshop is using composer install  (not composer install --no-dev) which would be bad... because it would not include our behat dependencies 

So i think the real solution is to get have the Aegir user explicitly call the Drush executable path it needs until Drush 9 is supported.   (this is what we did at Acquia when we ran into all kinds of crazy problems with  Drush 4, 5, 6, 7, 8.  :)

**Comment by jonpugh** [comment]
My plan is to make composer_install_coomand a true context property so that each platform can store it's own.

I'll be up in a few hours and will show you what I mean.

**Comment by jienckebd** [comment]
I'm sure there are better solutions, but I added a hook to my composer build that swaps in a different symlink for `vendor/bin/drush` to point to an alternative executable in my code base that either calls global Drush or project Drush.

So added this to composer.json to set up the hooks:

```
"scripts": {
        "post-install-cmd": [
            "Acquia\\Blt\\Custom\\Composer\\Plugin::scaffold"
        ],
        "post-update-cmd": [
            "Acquia\\Blt\\Custom\\Composer\\Plugin::scaffold"
        ]
    },
```

Content of that hook:

```
<?php

namespace Acquia\Blt\Custom\Composer;

/**
 * Composer plugin for handling drupal scaffold.
 */
class Plugin {

  /**
   * Runs when packages installed or updated.
   *
   * @param mixed $event
   *   The event.
   */
  public static function scaffold($event) {

    $platform_root = dirname(dirname(dirname(__DIR__)));

    $project_drush_path = "{$platform_root}/sys/bin/drush";
    $vendor_drush_path = "{$platform_root}/vendor/bin/drush";

    if (file_exists($vendor_drush_path)) {
      unlink($vendor_drush_path);
    }

    symlink($project_drush_path, $vendor_drush_path);
  }

}
```

And then ./sys/bin/drush does this:

```
#!/usr/bin/env bash

current_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -f /usr/local/bin/drush ]; then
  /usr/local/bin/drush "$@"
else
  "${current_path}/../../vendor/bin/drush" "$@"
fi
```

It's ugly, but I didn't want to remove Drush 9 / BLT from my project.

**Comment by caldenjacobs** [comment]
@jienckebd Your approach seems like it should work, but I'm receiving `bash: warning: shell level (1000) too high, resetting to 1` and the drush call is hanging. Any ideas?

**Comment by jonpugh** [comment]
This is an awesome quick fix... just triaging at the moment, I'll organize this into an epic soon.

**Comment by jonpugh** [comment]
Hmm... For "Global Drush" we are now using drush8 required via composer in the devshop CLI.

The `/usr/share/devshop/bin` path contains drush and is set to be in the path.

The fix above would have to change `/usr/local/bin/drush` to `/usr/share/devshop/bin/drush`.

**Comment by SuperSandro2000** [comment]
Bump

**Comment by SuperSandro2000** [comment]
Bump

**Comment by jonpugh** [comment]
Thanks for keeping this open @SuperSandro2000 .

It will be addressed eventually.

The 1.7.x releases have been a major overhaul of the libraries like provision and hosting, to move them into composer. 


The only reason "Aegir" or "DevShop" requires drush 8 is that the Hosting.module drush commands (that run from the hostmaster site) are in drush8 and the "provision" drush commands are in drush8. 

If provision was moved from core devshop composer into the composer-based front-end, those provision commands would become "site local" drush commands, which in theory means DevShop/Aegir can keep it's drush8 commands a little bit longer if we can isolate them inside the hostmaster site.

Then, we can switch to drush 9 or 10 as the global default, and it would actually pass off to drush8 when running as a hostmaster command automatically. 

I think? Time to try it.

**Comment by jonpugh** [comment]
Whoah there, github, thanks.

**Comment by SuperSandro2000** [comment]
Bump

**Comment by jonpugh** [comment]
Fixed!
