### ISSUE TITLE
0.5.4 - https and ssl not working

### ISSUE THREAD

**Issue by laroucheyouth** [opendevshop/devshop#32]
Tried a 0.5.4 installation with Ubuntu 12.04 and 14.04. 

Follow the directions here https://devshop.readthedocs.org/en/latest/ssl/

Chrome throws an SSL Protocol Error. 

Checked the firewalls a million times, both on the VM itself, and through my cloud service provider (google compute engine.)

Checked the logs, configuration, certs, etc. I can't seem to find any more leads. Note: I didn't even try commercial SSL yet, just trying to make things work with a self signed cert.

**Comment by jonpugh** [comment]
We don't do anything special with SSL, it is all handled by Aegir. There will be a new release of devshop this week, please get the latest version when that happens.

Please see the Aegir docs and the Aegir support channels, #aegir on IRC.

Thanks.
