### ISSUE TITLE
Problem with docker-compose

### ISSUE THREAD

**Issue by metalbote** [opendevshop/devshop#329]
When I try to start devshop with docker-compose i got following error:

ERROR: for devshop  Cannot start service devshop: OCI runtime create failed: sysctl "kernel.domainname" is not in a separate kernel namespace: unknown

Domainname is set in /etc/defaultdomain.
Any ideas to procede?

My compose.yml:

`version: "3.4"
services:

  devshop:
    env_file: .env
    image: devshop/server:latest
    container_name: "devstack_devshop"
    domainname: ${DOMAINNAME}
    hostname: "devshop"
    # privileged: true
    restart: always
    stop_grace_period: 30s
    ports:
    - 1022:22/tcp
    networks:
      private:
        aliases:
        - devshop.${DOMAINNAME}
      public:
        aliases:
        - devshop.${DOMAINNAME}
    environment:
      AEGIR_CLIENT_EMAIL: "${AEGIR_CLIENT_EMAIL}"
      AEGIR_UID: "${PUID}"
      AEGIR_GID: "${PGID}"
      AEGIR_DATABASE_SERVER: "localhost"
      AEGIR_HOST: "devshop.${DOMAINNAME}"
      VIRTUAL_HOST: "devshop.${DOMAINNAME}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PHP_SENDMAIL_PATH: "/usr/sbin/sendmail -t -i -S mailhog:1025"
    volumes:
    - "${VOLUMEDIR}/devshop/aegir:/var/aegir"
    - "${VOLUMEDIR}/devshop/mysql:/var/lib/mysql"
    - "${VOLUMEDIR}/shared:/var/lib/shared"
    labels:
      traefik.enable: "true"
      traefik.backend: "devstack_devshop"
      traefik.docker.network: "public"
      traefik.port: "80"
      traefik.frontend.rule: "Host: devshop.${DOMAINNAME}"

networks:
  public:
    driver: bridge
  private:`

**Comment by jonpugh** [comment]
Sorry, not sure how to help. This is out of scope for this project.
