### ISSUE TITLE
Unable to set mysql root password on devshop/server docker install

### ISSUE THREAD

**Issue by metalbote** [opendevshop/devshop#335]
Docker setup (image devshop/server) stops on  

```
devshop    |             [0] => SQLSTATE[HY000] [1045] Access denied for user
devshop    | 'root'@'localhost' (using password: YES)

```

if trying to set a custom mysql root password with .my.cnf

**Comment by janadam** [comment]
This is maybe related to https://github.com/opendevshop/devshop/pull/344

**Comment by jonpugh** [comment]
Needs investigating. :point_up:

**Comment by jonpugh** [comment]
A lot has changed in devshop/server in the last year.

Let's review this to see if it is still an issue.
