### ISSUE TITLE
Documentation link on d.o. project page broken

### ISSUE THREAD

**Issue by aangelinsf** [opendevshop/devshop#336]
It currently points to:
http://docs.devshop.support

But it should point to:
https://docs.opendevshop.com

**Comment by caldenjacobs** [comment]
@jonpugh

**Comment by jonpugh** [comment]
Thanks yall, @daggerhart is on it!

**Comment by daggerhart** [comment]
Fixed

**Comment by jonpugh** [comment]
Thank you @daggerhart and @aangelinsf !
