### ISSUE TITLE
Cannot use playbook option for install script anymore

### ISSUE THREAD

**Issue by metalbote** [opendevshop/devshop#337]
The option --playbook to define a custom playbook seems to be removed from 1.4.0-> 1.5.x.

Either add it again or update docs.

**Comment by jonpugh** [comment]
Related: #344

Commit where it was removed: https://github.com/opendevshop/devshop/commit/e305886f965a94818f9136c8a490d53307411a11

**Comment by jonpugh** [comment]
@metalbote Are you all using this feature?

**Comment by metalbote** [comment]
Jup, i use a custom playbook to add additional testing software. Maybe it will be obsolete if it is possible to move everything to docker, but for now i rely on it.

**Comment by jonpugh** [comment]
@metalbote what kind of testing software? Would love to hear a case study!
