### ISSUE TITLE
Create a great MOTD

### ISSUE THREAD

**Issue by daggerhart** [opendevshop/devshop#346]
**From d.o**: https://www.drupal.org/project/devshop/issues/2418175

---

We need a great message of the day for all users when they login.

It needs to be perfectly clear that they need to switch to the "aegir" user.

> We added a MOTD but it doesn't seem to take. There is a lot of variance between OS's that makes this a bit difficult.
> Still, we should try to finalize this for 1.0.0.

**Comment by philoSurfer** [comment]
This should be pretty feasible with just a custom entity block (include revisions). 
Visibility permissions should be considered in addition to editorial permissions.
