### ISSUE TITLE
Recruit Git Host integration maintainers for BitBucket, GitLab, and GitHub

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#350]
It's difficult to support all the features we want for all git providers APIs.

Let's see if there are some people out there willing to help maintain the different API integrations for:

- GitHub | @jonpugh 
- BitBucket | ? | ?
- GitLab | #137 | @chrisfromredfin

**Comment by philoSurfer** [comment]
Raises hand for Bitbucket.

**Comment by jonpugh** [comment]
Everything is blocked by the monorepo effort in #405 

Let's push that over the line, then work on any devmaster code is easy.
