### ISSUE TITLE
Show environment's "README" in the user interface

### ISSUE THREAD

**Issue by liberatr** [opendevshop/devshop#364]
Create a new environment task that will show the README.md, README.txt or README file from the project root. Similar to the functionality in many popular git tools (perhaps we can also get a list of potential names for the readme files from some open-source git tool).

**Comment by jonpugh** [comment]
This is a great idea. Probably a better fit in the Environment Info modal.

**Comment by jonpugh** [comment]
@liberatr This wouldn't be very hard to do. Would you want to take this feature on yourself? I can guide you through the whole way.
