### ISSUE TITLE
Support for other projects like WordPress and GravCMS 

### ISSUE THREAD

**Issue by gusaus** [opendevshop/devshop#365]
I believe support for both these platforms is on the roadmap. WordPress support is/was a goal on https://opencollective.com/devshop/ but it's hard to tell due to issues on the Open Collective side https://github.com/opencollective/opencollective/issues/1434#issuecomment-483890448

Assuming both are on the roadmap, are there issues set up that detail the scope and contributions needed to complete?

**Comment by liberatr** [comment]
Not sure how helpful this is but there is an old "Hosting Wordpress" module on d.o https://www.drupal.org/project/hosting_wordpress

**Comment by gusaus** [comment]
Based on [twitter discussions](https://twitter.com/jonpugh/status/1121481948843663360), it sounds like @jonpugh already has a plan. The blocker is coming up with funds to implement. 

That said, it would be good to have the project scope laid out so collaborators and contributors can reference.

**Comment by gusaus** [comment]
Is WordPress support still on the roadmap?

**Comment by nasl** [comment]
I would like to downvote WP support... WP is most popular CMS, which has huge support  everywhere  else (and is a huge CMS by itself with lots of weirdly build plugins). If we are talking about big projects then almost everything can be done with Drupal, another thing is small one page and brochure sites - Drupal is an overkill, but WP is also, so my vote would be choose 1-2 popular lightweight flatfile CMS, like GravCMS or any other, possibly even lighter.

No offence.
My 2 cents.

**Comment by liberatr** [comment]
@nasl my case for wordpress is that because it's so popular, it would greatly increase the potential user base for the project. Getting it in more hands means more resources, more refinement, a better UX and... more.

I'd also like to see flat-file projects supported. This issue is about WP.

**Comment by gusaus** [comment]
Aside from issues with some Drupal 8 distributions, Drupal is already supported. https://github.com/opendevshop/devshop/issues/338

GravCMS and WordPress are referenced in this issue. Would be great to hear more from @jonpugh regarding resources needed to support all of the above.

Then possibly we can help direct resources to the project.

**Comment by nasl** [comment]
Well if we are talking about the user base with **money**, then probably Magento and Prestashop are the candidates, besides - there are not many tools for them like ODS

**Comment by liberatr** [comment]
I'll take Magento support, because getting from 1 to 2 in this case will introduce all the abstraction we would need to add other non-drupal systems.

**Comment by gusaus** [comment]
We're currently looking to launch at least one SaaS on WordPress. There are most likely a lot of orgs who would value or fund this type of setup for projects related to Covid-19.

There are many ways to fund whatever development resources are needed. It's not clear what resources are needed or where to direct them.
