### ISSUE TITLE
Chat doesn't work at first

### ISSUE THREAD

**Issue by Greg-Boggs** [opendevshop/devshop#366]
"User not active" is the error message I see in the top right after clicking the CAS button for chat. This might be specific to https://devshop.support

Opening the chat link disables the back button. So, the user loses the link back to the dashboard. Perhaps use target="_blank" on chat as a work around?

**Comment by jonpugh** [comment]
Ah, yes, looks like I have to click "Activate". You should be in there now.

I'll add to our internal list.

Thanks!
