### ISSUE TITLE
Ansible playbooks change existing user's UID/GID, when it should not.

### ISSUE THREAD

**Issue by landrypm** [opendevshop/devshop#379]
When running install.sh, the aegir user is created as a local user on the machine where install.sh runs. If a local aegir user already exist, the UID number for the existing user is changed. Likewise for the aegir group.

It would be preferable to search to see if an existing aegir user/group exists and, if so, use that user/group.

**Comment by jonpugh** [comment]
This should be handled in the Ansible playbook if we want to enforce this behavior.

`setfact` can be used to change `aegir_user_uid` variable as the playbook runs, but it won't change the inventory. Aso the user

If the `aegir_user_uid` does not match the `aegir_user_name`'s UID we should show a warning at least.

**Comment by jonpugh** [comment]
This can be done in the "opendevshop.users" playbook tasks file: https://github.com/opendevshop/devshop/blob/1.x/roles/opendevshop.users/tasks/main.yml#L46
