### ISSUE TITLE
CentOS Linux release 7.6.1810 (Core) 

### ISSUE THREAD

**Issue by emad-ramlawi** [opendevshop/devshop#380]
Hello,

Ansbile script wont proceed in Digital Ocean Centos
CentOS Linux release 7.6.1810 (Core)
while it worked fine in ubuntu image:

I just see this
```
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at d56ba09... New release v2.3.0.0-1
[root@kku devshop-1.5.0-rc7]# 
```

Steps:

sudo su -
wget https://raw.githubusercontent.com/opendevshop/devshop/1.5.0-rc7/install.sh
bash install.sh

tried older versions same thing

**Comment by jonpugh** [comment]
Hello,
Thanks for the detailed bug report.

The easiest solution might be to install the default version of ansible, before running the install script.

The install script skips the building of ansible from source if the executable is there.

I want to add this to automated testing. 

Thanks!

**Comment by emad-ramlawi** [comment]
Many thanks, that worked.

Best,
Emad R.
________________________________
