### ISSUE TITLE
DevShop won't work right until composer install in the site is run.

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#386]
Under some conditions, the `robo up` or devshop install will result in a half-broken install because the `composer install` for devmaster won't work.

- Homepage works.
- Task logs break: logs won't show.
- "Create Project" page breaks.

Hard to debug because task logs cannot be viewed.

@elijahLynn and I were coworking on this and discovered it failed because his container could not reach the internet.

We must mitigate this situation in a few ways:

- Composer install immediately after hostmaster-install? right now it runs in the first "hostmaster verify" task so it can take a while until it's done.
- ?

Right now, this doesn't happen until the first @hostmaster verify task runs. It would be nice if this could run right at the end of the install.sh script or entrypoint script.

**Comment by philoSurfer** [comment]
Possible Solution: check that the internet is available? :)  `composer diag` does the trick.

**Comment by jonpugh** [comment]
This is all so janky. It will be much easier to solve with the monorepo, since we will have total control over roles and dockerrfiles.
