### ISSUE TITLE
"git show" killing performance when dealing with big commits 

### ISSUE THREAD

**Issue by josebc** [opendevshop/devshop#395]
Hello 
This is a fancy thing to have in the deploy script (being able to see the code changes) however in some cases it can cause deployment to fail (ie. deploying a commit with a new drupal installation or anything else with huge code changes).
Could not make the deploy work till commenting lines 
https://github.com/opendevshop/devmaster/blob/7.x-1.x/modules/devshop/devshop_projects/drush/deploy.devshop.provision.inc#L42
https://github.com/opendevshop/devmaster/blob/7.x-1.x/modules/devshop/devshop_projects/drush/deploy.devshop.provision.inc#L57

**Comment by jonpugh** [comment]
Totally agree.

In the spirit of growing our contributor base, would you be willing to submit a PR removing it?

I'd merge it really quickly!


UPDATE: Actually, what would be really cool is if we printed the link to the commit in GitHub or wherever instead.

**Comment by jonpugh** [comment]
In fact, most of the git info stuff needs to go. It does not do well when there are a large number of projects either.

I've known for a while we should build a little API URL for git status that other parts of the UI could use.

**Comment by josebc** [comment]
its included in this one https://github.com/opendevshop/devmaster/pull/158 which was for a syntax error in the same file
sorry im still a github newbie

**Comment by jonpugh** [comment]
We've removed the git show in the deploy logs. Still need to improve it in the environment info panel.

**Comment by philoSurfer** [comment]
This just bit me in the ass in the deployment log..   It truncates the `git show` task and outputs `error malformed packet`.

We might want to make this some type of option to ignore the `git show` for large commits.   @jonpugh where would be a good place we could put this?  

I am thinking on the log page with a checkbox next to the retry button, with a brief explanation of why you would want to not run `git show`. eg.  [x] Ignore git show task for larger commits

**Comment by jonpugh** [comment]
I believe this was merged way back when. 

Leaving in needs triage to confirm.
