### ISSUE TITLE
Error on verify project when DevShop GitHub is disabled 

### ISSUE THREAD

**Issue by josebc** [opendevshop/devshop#396]
Verify project will result with the following error if the github module is disabled
WD php: Error: Call to undefined function convert_to_object() in devshop_environment_normalize() (line 313 of /var/aegir/devmaster-1.x/profiles/devmaster/modules/devshop/devshop_projects/inc/nodes.inc).

Proposed solution:
Move the function convert_to_object from devshop_github.module to devshop_projects.module since devshop_projects is already a dependency for devshop_github

**Comment by jonpugh** [comment]
This is terrible coding on my part, I apologize.  :)

I'm moving fast and furious. Yes, it should be included in a globally enabled module, for sure.

Even better, would be to start a basic Environment class and put this on it.

Small changes first, though.

**Comment by jonpugh** [comment]
Would you mind another PR, @josebc ?  

Thanks so much!

**Comment by josebc** [comment]
Thanx for the great project man, d7 makes it harder to keep things clean 
I think I’ve done something dumb, I committed the other changes to my 7.x-1.x and now that i created a new branch the PR includes the older diff
I think it would have been better to create branches and create PR against the original repo then pull back once merged 
https://github.com/opendevshop/devmaster/pull/159

**Comment by jonpugh** [comment]
Don't worry about it, all of this will get merged today.

It happens. 
Separate stuff in the future, though.  :)

**Comment by jonpugh** [comment]
Hah, I was going to say...

Don't worry about it until it breaks :)

**Comment by josebc** [comment]
Yeah I guess
Thanx a lot
