### ISSUE TITLE
Aegir 3? 

### ISSUE THREAD

**Issue by niccolox** [opendevshop/devshop#4]
gday Jon

this is a tremendous project and its reach some serious maturity

so, how about doing it ALL OVER AGAIN and porting to Aegir 3 ? Drupal 7?

great if you could do that by next week

cheers

-N

https://www.drupal.org/node/2218539

**Comment by jonpugh** [comment]
Hah!

That is something I am not looking forward to at all.  Would absolutely love it if someone were to come along and help move this process forward, however there is almost nothing to gain from upgrading devshop to work with aegir 3 other than having a front-end in drupal 7 and being able to retire "provision" modules.

I am very much tempted to skip aegir 3 completely at this point, and go straight into devshop 2 using [director](http://github.com/jonpugh/director) as the backend and drupal 8 as a front-end.

Focusing on cleaning up the last remaining rough edges in devshop 0.x is the primary mission.  

Thanks!
Jon

**Comment by niccolox** [comment]
Interesting

There is also Drupal Console (unsure if that's relevant) not having looked
at Director

Drupal 8 has a lot of useful external libraries etc for sure

**Comment by jonpugh** [comment]
@niccolox I just wanted to let you know that the 1.x branch of devshop works pretty well at this point, hosting drupal8 on Aegir 3.

If you are feeling inspired and want to try it out, just get the 1.x version of the install.sh script and run it on a fresh ubuntu 14.04.

Let me know how it goes!
Jon

**Comment by niccolox** [comment]
Cool. Will test in next week or so

**Comment by niccolox** [comment]
got it work on Trusty vm on vmware workstation on Xenial host

couldnt get the Vagrant to work, but, I am not using it at present and I
didnt debug

also, just for giggles, tried to install on Xenial as a VmWare vm on my
Xenial host and it failed... on the common packages section, same, no
debugging

I am developing an Aegir site factory at present and working on a complex
hub site and I want to be able to branching etc so am actually going to
give this Devshop thing of yours a serious test drive

cheers for that !

On Sun, Feb 21, 2016 at 12:23 PM, Nicholas Roberts <
niccolo.roberts@gmail.com> wrote:

> Cool. Will test in next week or so
> On Feb 21, 2016 7:39 AM, "Jon Pugh" <notifications@github.com> wrote:
>
>> Reopened #4 <https://github.com/opendevshop/devshop/issues/4>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/opendevshop/devshop/issues/4#event-558437260>.
>>
>


-- 

-- 
Nicholas Roberts
www.niccolox.org

**Comment by jonpugh** [comment]
Stay in close touch, @niccolox, if you hit some wall, let us know and we will do what we can to hack it to fit your use case.

Good luck!

**Comment by niccolox** [comment]
🌋

On Mon, Feb 29, 2016 at 6:38 PM, Jon Pugh <notifications@github.com> wrote:

> Stay in close touch, @niccolox <https://github.com/niccolox>, if you hit
> some wall, let us know and we will do what we can to hack it to fit your
> use case.
>
> Good luck!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opendevshop/devshop/issues/4#issuecomment-190504621>.
>



-- 

-- 
Nicholas Roberts
www.niccolox.org

**Comment by jonpugh** [comment]
Closing! Been on Aegir 3 since 1.0.0-alpha1 release
