### ISSUE TITLE
How to start branch to OpenBSD

### ISSUE THREAD

**Issue by programacion-web** [opendevshop/devshop#40]
hello,

Before starting a new branch for openbsd, I would like to know
What requirements do I need?

Currently I have OpenBSD 5.7
Web Server is NGINX
MySQL Server is MariaDB
php is: php-fpm
I have installed: Drush

some sites have installed in Drupal 7 and other in Drupal 8

Any advice before I start?

Thanks

**Comment by jonpugh** [comment]
Hi!
I am not sure what it would take to get this working on OpenBSD... but here's a page that has a few links on it about getting Aegir working on OpenBSD.

Only the 1.x branch supports Drupal 8 sites, but it's not ready for use yet.

If you do start working on this, please create a separate install script and playbook.yml file for OpenBSD. I don't want to fill the current scripts with logic for OpenBSD but I'd be happy to ship a separate script.

I'm going to close this issue. Feel free to reopen if you have more questions.

Thanks!
