### ISSUE TITLE
Bitbucket integration - "Delete Pull Request environments" not working. 

### ISSUE THREAD

**Issue by philoSurfer** [opendevshop/devshop#421]
This checkbox is checked in the environment settings. 
PR's are creating environments just fine.  Merge events are not deleting the environments. 

Triggers in bitbucket repo settings are the following:
Triggers: pullrequest:rejected, pullrequest:created, pullrequest:fulfilled

Checking **devshop_bitbucket.module**  line: 690   I am seeing the condition for rejected or fulfilled to then begin the delete process... but this never gets fired. 

#Stumped.

**Comment by jonpugh** [comment]
@philoSurfer I recommend enabling XDEBUG for these kind of things.

Also, compare to devshop_github ...

Did you say earlier you would maintain the BitBucket integration? :)

We need a MAINTAINERS.md :D

**Comment by philoSurfer** [comment]
Yeah I am willing to maintain the Bitbucket module.   I will dig in and start creating PR's  :)

**Comment by philoSurfer** [comment]
Quick note for Bitbucket users trying to whitelist IPs

Requires jQ to be installed in the CLI run the following command to get a filtered list of IPs needed to whitelist for webhooks:

`curl -sS https://ip-ranges.atlassian.com | jq -r '.items[] .cidr'`
