### ISSUE TITLE
Fresh installation fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by r115** [opendevshop/devshop#422]
This is what I get when running the installation script on a new machine.

<img width="949" alt="devshopcrash" src="https://user-images.githubusercontent.com/2851039/69142921-e3d7b600-0ad8-11ea-8eb4-38cd5dc9220a.png">

What could I be doing wrong?

**Comment by jonpugh** [comment]
Ahh... this step was recently added to automatically set the GitHub token. I neglected to test it without the token, so the "drush vset" is failing with the empty value.

The Ansible step should skip if the "devshop_github_token" is missing.

Stand by for PR

**Comment by jonpugh** [comment]
Oh, weird, so I guess I did try to use `when`:
```

- name: DevShop | Save GitHub Token
  become: true
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"
  command: "{{ drush_bin_path }} @hostmaster vset devshop_github_token {{ devshop_github_token }}"
  when: devshop_github_token != ""
```

I wonder what the right way to check for an empty string variable in ansible is...

**Comment by jonpugh** [comment]
@r115 You can git pull in `/usr/share/devshop` to get the latest 1.x now. 

The role has been updated to ignore errors in this ansible step.

**Comment by r115** [comment]
It works. Thank you
