### ISSUE TITLE
Install fails on fresh ubuntu 16.04 and 18.04

### ISSUE THREAD

**Issue by janadam-hbf** [opendevshop/devshop#454]
I have tried to run `bash install.sh` as root on recent ubuntu and there is this error:
```
TASK [geerlingguy.supervisor : Ensure Supervisor is installed (latest version).] ***************************************************************
fatal: [devshopdomain.com]: FAILED! => changed=false 
  msg: Unable to find any of pip2, pip to use.  pip needs to be installed.
```

**Comment by jonpugh** [comment]
Thanks for the heads up. The testing system has slightly different containers, so this wasn't caught by the automated testing.

You can fix this by adding an ansible variable or config item for:

```
    ansible_python_interpreter: python3
```
There are many options to set this variable...

- playbook.yml
- /etc/ansible/host_vars 
- /etc/ansible/ansible.cfg

I'm still not sure of the exact best way to handle this, to be honest!

**Comment by jonpugh** [comment]
Actually... Perhaps we should just add what we run in the Dockerfile to the install.sh script?

See the new Dockerfile at https://github.com/opendevshop/devshop/blob/1.x/Dockerfile

You can avoid changing any devshop code or config by setting default python interpreter in the same way the Dockerfile does it:

```
RUN apt-get update \
    && apt-get remove -y \
       python-setuptools \
       python-pip \
    && apt-get install -y --no-install-recommends \
       python3-setuptools \
       python3-pip

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
```

We should include this in the install.sh file. It would be nice to standardize on python3.

**Comment by janadam-hbf** [comment]
I have tried to add this to install.sh
```
        apt-get install python3-setuptools python3-pip python3-mysqldb -y -qq
        update-alternatives --install /usr/bin/python python /usr/bin/python3 10
        update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
```
but getting
```
TASK [opendevshop.devmaster : Wait for MySQL Server to be ready.] *************************************************************************************************************************
fatal: [dev1.war.sk]: FAILED! => changed=false 
  cmd: mysql-wait
  msg: '[Errno 2] No such file or directory: b''mysql-wait'': b''mysql-wait'''
  rc: 2
```
Not sure what am I missing.

**Comment by jonpugh** [comment]
Hmm, `mysql-wait` should be in your $PATH, it must have something to do with how you are manually installing.

I will update that ansible step to use the absolute path to avoid this edge case.

**Comment by nasl** [comment]
I do have the same problem. Ubuntu 18.04
Not sure it this is the reason, but ODS does not seem to work after install. `devshop` command is not recognized, and when accessing hostname I am getting default Apache on Ubuntu page.
Tried almost every solution on this thread - no luck :(

**Comment by cvining** [comment]
As this issue is still open I'm reporting seeing the same error on a fresh install of Ubuntu 18.04.3 LTS in a Virtualbox guest with 2G memory. 

I ran these

```
RUN apt-get update \
    && apt-get remove -y \
       python-setuptools \
       python-pip \
    && apt-get install -y --no-install-recommends \
       python3-setuptools \
       python3-pip \
       python3-mysqldb      

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
```
then "bash install.sh" which ran to completion and I have a working devmaster, which is way cool and I have much to learn before I dare run a live site with it.

I'm also seeing the composer/php memory issue in #488 , which I haven't resolved just yet.

In any case, thanks for all the hard work!

**Comment by nasl** [comment]
It finally worked for me! Got it running.
BEFORE (second) installing just run `apt-get install python3-setuptools python3-pip python3-mysqldb`

I repeated install.sh script 2 times... but at least I got ODS running somehow.
Thanx for hard work!!!
