### ISSUE TITLE
Drush 9 support for Composer-based projects

### ISSUE THREAD

**Issue by Gogowitsch** [opendevshop/devshop#466]
Allow Composer-based projects such as [opendevshop/example-devshop-drupal-project](https://github.com/opendevshop/example-devshop-drupal-project) to ``require`` Drush 9 or Drush 10.

This issue is likely the same as https://www.drupal.org/project/provision/issues/2953349, so let's continue the discussion there.

**Comment by jonpugh** [comment]
@ElijahLynn and I are mapping out the steps needed to finally finish this.

Stand by for more info over the next few weeks.

**Comment by jonpugh** [comment]
See origin issue: https://github.com/opendevshop/devshop/issues/313

**Comment by jonpugh** [comment]
Finally completed. What a trip.
