### ISSUE TITLE
PHP CLI Memory Limit Update

### ISSUE THREAD

**Issue by FatGuyLaughing** [opendevshop/devshop#488]
The `/etc/php/7.2/cli/php.ini` is starting out with `256M`. Since this is the CLI it would be nice for it to be set to `-1` for unlimited.

I run into memory errors with this being set so low. According to Composers docs
```
Note: Composer internally increases the memory_limit to 1.5G.
```
The composer.json file I have uses a little over 1.6G. So moving this `memory_limit` to `-1` has worked for me.

**Comment by FatGuyLaughing** [comment]
Based on conversations with Jon Pugh in slack, this is something that would be coming from the geerlingguy php role. However there is a statement on [composers trouble shooting memory section](https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors).

Composer will recognize an environment variable `COMPOSER_MEMORY_LIMIT`. This may be another option.

**Comment by jonpugh** [comment]
I always set PHP CLI memory limit to -1 manually, it sucks.

We should maintain our own default Ansible variable for this.
