### ISSUE TITLE
Environment LOG IN link misleading

### ISSUE THREAD

**Issue by FatGuyLaughing** [opendevshop/devshop#489]
![Screen Shot 2020-01-16 at 11 13 25 AM](https://user-images.githubusercontent.com/405995/72546914-3ae7d600-3851-11ea-8583-14ce5b430713.png)
The `LOG IN` link in the upper right hand corner is a bit misleading. I would expect this to take me to the `/user` page, so I can log in to the site. Instead it is `resetting the password` then `generates one time log in link`. This reset link is provided in the modal to click for `logging in` to the site.

What about changing that to have a dropdown like the `</> CODE` section. In the dropdown would be option to `LOG IN` or `RESET PW`. The `LOG IN` would be the default option. This way you can click it without having to select the dropdown. Then if you need to reset you can select the dropdown and pick that option?

I'm not sure this is a best solution, but I can see people getting confused and resetting the password a lot.

**Comment by jonpugh** [comment]
Great feedback, thanks. Keeping this in the queue.
