### ISSUE TITLE
Searchable Projects

### ISSUE THREAD

**Issue by FatGuyLaughing** [opendevshop/devshop#490]
![Screen Shot 2020-01-16 at 11 52 47 AM](https://user-images.githubusercontent.com/405995/72549660-b9934200-3856-11ea-9fb7-a692feb89c4d.png)
I have 100+ projects on our Aegir system. One thing that is nice, is the leverage of views for displaying all of the sites. This allows for me to easily add exposed filters so I can quickly find what I am looking for.

It would be nice for OpenDevShop to have some fields to help with the Projects listing page. Maybe at the very least we could have fields for the Name and Profile of the Project.

**Comment by jonpugh** [comment]
100% yes.

This is actually a great beginner task, this page should have been converted to use Views ages ago.

Then we would get search, paging, sorting, etc.

Anyone up to the task?
