### ISSUE TITLE
Install fails on fresh Ubuntu 18 install

### ISSUE THREAD

**Issue by Ghostcode75** [opendevshop/devshop#492]
it looks like the https://galaxy.ansible.com/geerlingguy/php playbook calls for 
php_packages_state: present
 However "installed" is returned

 https://github.com/geerlingguy/ansible-role-php/blob/master/defaults/main.yml

msg: value of state must be one of: absent, build-dep, fixed, latest, present, got: installed

**Comment by jonpugh** [comment]
Sounds like you are probably using an old version.

Use 1.x branch until there's a new release.

**Comment by Ghostcode75** [comment]
Ubuntu Server 18.04.3 LTS

sudo su -
wget https://raw.githubusercontent.com/opendevshop/devshop/1.5.0-rc7/install.sh
bash install.sh

not sure what I could be doing incorrectly. I also tried with
 copying this script and running it with the same results:

https://github.com/opendevshop/devshop/blob/1.x/install.sh

I also tried this on and AWS instance of Ubuntu Server 18.0.4.3 LTS with the same results.

**Comment by Ghostcode75** [comment]
![Screen Shot 2020-01-17 at 7 40 42 PM](https://user-images.githubusercontent.com/44623651/72658131-8be6ef80-3961-11ea-9dba-e790de46c5ce.png)

**Comment by philoSurfer** [comment]
I am personally running devshop on Ubuntu 19.04 for the OOB support for Php 7.2

**Comment by philoSurfer** [comment]
I had this command listed in my Ubuntu 18.04 provision notes:

```
# Once new instance has been created.  Run the following commands before devshop install.
sudo apt install php7.2-bcmath;
```

**Comment by philoSurfer** [comment]
Also.. this is what I am using to install the latest:

`wget https://raw.githubusercontent.com/opendevshop/devshop/1.x/install.sh;
bash install.sh --hostname=devshop.MYDOMAIN.COM`

**Comment by jonpugh** [comment]
> I am personally running devshop on Ubuntu 19.04 for the OOB support for Php 7.2

@philoSurfer Can you test out setting `php_version` ansible variable? I almost had GitHub actions passing tests in 18.04 for 7.2 and 7.3

**Comment by mazzarito** [comment]
I'm also unable to install on 18.04 - but I'm getting: 

```
^[[0;31m    DRUPAL_INSTALL_FAILED                                                                    [31;40m[1m[error][0m^[[0m
^[[0;31m    Site installation caused an exception: SQLSTATE[23000]: Integrity constraint violation:  [31;40m[1m[error][0m^[[0m
^[[0;31m    1048 Column 'module' cannot be null^[[0m
```
```
^[[0;31m    2770^[[0m
^[[0;31m    Generated config in write(): Drupal sites.php file                                       [1;32;40m[1m[success][0m^[[0m
^[[0;31m    (/var/aegir/devmaster-1.x/sites/sites.php)^[[0m
^[[0;31m    Changed permissions of /var/aegir/devmaster-1.x/sites/sites.php to 644                   [1;32;40m[1m[success][0m^[[0m
^[[0;31m    Invalid argument supplied for foreach() common.inc:7300                                  [1;33;40m[1m[warning][0m^[[0m
^[[0;31m    array_keys() expects parameter 1 to be array, null given common.inc:7320                 [1;33;40m[1m[warning][0m^[[0m
^[[0;31m    array_keys() expects parameter 1 to be array, null given common.inc:7320                 [1;33;40m[1m[warning][0m^[[0m
^[[0;31m    Login url:                                                                               [1;32;40m[1m[success][0m^[[0m
^[[0;31m    http://devctl.blankstyle.com/user/reset/1/1584989644/Kg1petyWtOuD1ftq-7cFfBnDfsJsJB-dAWGnU94fFgk/login^[[0m
^[[0;31m  ^[[0m
```
