### ISSUE TITLE
Tasks from deleted environments appear sometimes

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#493]
When a new environment is created with the same name as one that was previously deleted, the old tasks can sometimes reappear.

![image](https://user-images.githubusercontent.com/106420/72643747-5fb97780-393d-11ea-8696-fd9be6745b1c.png)

**Comment by jonpugh** [comment]
https://github.com/opendevshop/devshop/issues/493

**Comment by jonpugh** [comment]
Did you happen to see this side effect from deleting and creating a new env with the same name @matthandus ?

**Comment by matthandus** [comment]
Not before. Seeing it now.
