### ISSUE TITLE
Cannot install on Centos 7,8, Ubuntu 16.04, 18.04

### ISSUE THREAD

**Issue by nasl** [opendevshop/devshop#514]
Cannot install on any of these images, Ubuntu mentioned already in another issue. Using Hetzner cloud vps, everything standard, following every procedure copy+paste to the letter.

Centos 7

```
[root@sub ~]# bash install.sh --hostname=sub.domain.com
install.sh: line 91: drush: command not found
install.sh: line 91: devshop: command not found
```
I havent tried to install drush manually (before instal script), but after the script the vps is messed up and then drush install does not help

Centos 8

```
Extra Packages for Enterprise Linux 8 - x86_64  7.1 MB/s | 5.9 MB     00:00
Last metadata expiration check: 0:00:02 ago on Thu 20 Feb 2020 01:52:59 PM CET.
Package which-2.21-10.el8.x86_64 is already installed.
Package make-1:4.2.1-9.el8.x86_64 is already installed.
Package git-2.18.2-1.el8_1.x86_64 is already installed.
No match for argument: python-setuptools
No match for argument: PyYAML
No match for argument: python-httplib2
No match for argument: python-jinja2
No match for argument: python-keyczar
No match for argument: python-paramiko
No match for argument: python-six
Error: Unable to find a match
```

I am giving up... :(

**Comment by jonpugh** [comment]
I am almost 100% certain the source of this is missing default Python.

The automated testing we use has ansible and python pre-installed, and @geerlingguy recently shifted to use Python3 since python2 was deprecated.

I attached that PR, once the roles are updated and the tests are passing this issue should be resolved.
