### ISSUE TITLE
Docs / Projects / How to create new DevShop & Drupal project codebase?

### ISSUE THREAD

**Issue by nasl** [opendevshop/devshop#515]
Advice needed. For example, there are some projects, even on github which are not ready for deploying on ODS out of the box, such as:

https://github.com/drupalcommerce/demo-project
https://github.com/AcroMedia/commerce-demo

In this case more likelly those are pretty much abandoned.
What is the best way to "transfer" them to ODS? 

Thanx!

**Comment by jonpugh** [comment]
Hi, @nasl.

You can't use a Drupal install profile git repo directly as a DevShop project.

You should create a new git repo for your project, and then add those projects to it.

You can use composer or just download raw drupal stack and the extra modules and profiles you want and add directly to the git repo.

I'm marking this issue as Needs Docs, as we don't have enough documentation on how to prepare a git repo for DevShop.
