### ISSUE TITLE
Change the Pull Request Clone process to a clone + deploy.

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#55]
We have had a lot of problems with PR clone environments.

The problem is we create the new platform with the code on the new branch. This could be bad code.

Then we clone from the primary environment to this new platform. It could fail because of that bad code.

Not only that, but the "clone" task doesn't run the "Deploy" hooks that users are expecting.

I've been thinking this for a while and just never got around to it:

When a PR request comes in, and the setting is to "clone live environment", we should create a platform that is on the same git ref as live first, do the clone, THEN trigger a deployment to the new branch or git ref.

This will simulate a real deployment, as clones to the same codebase always succeed in Aegir, unless you run out of space or something drastic like that.

**Comment by llwp** [comment]
I was describing the PR clone process to someone *today* and literally
thought about the same exact thing.  Your steps description is a good start
to head the right way with this.

Yes yes yes.

Adam John
(914) 623-8433

**Comment by jonpugh** [comment]
I think we solved this one!

https://github.com/opendevshop/devmaster/pull/9

**Comment by jonpugh** [comment]
Done! I fixed this today in the update-features branch: https://github.com/opendevshop/devmaster/pull/27
