### ISSUE TITLE
Broken link in About Devshop section of the documentation

### ISSUE THREAD

**Issue by hsaada** [opendevshop/devshop#613]
In the **About Devshop** section of the documentation, the devmaster link is broken https://github.com/devshop/devmaster looks like it should be https://github.com/opendevshop/devmaster  (see screenshot)
![Screen Shot 2020-10-08 at 11 22 24 AM](https://user-images.githubusercontent.com/1623894/95480136-8b601000-0959-11eb-96e9-2f2424703733.png)

**Comment by jonpugh** [comment]
Thanks for the heads up! That link was fixed on the main readme but remains in the [./docs/README.md](./docs/README.md) file.

If you wouldn't mind, could you visit the [Edit link](https://github.com/opendevshop/devshop/edit/1.x/docs/README.md) and making the change yourself in a pull request? That way you'll get commit credit!

Thanks!

**Comment by jonpugh** [comment]
Thanks for the PR @hsaada ! I've merged it.

#614
