### ISSUE TITLE
install by docker failed

### ISSUE THREAD

**Issue by terryzwt** [opendevshop/devshop#635]
Steps to reproduce:
1. copy the docker-compose.yml from https://getdevshop.com/
2. docker-compose up -d
3. docker-compose logs -f docker-compose logs -f hostmaster, Errors screenshot in below:
![image](https://user-images.githubusercontent.com/1829399/100564305-a157d480-32fb-11eb-9b3b-35a89f272f1d.png)
![image](https://user-images.githubusercontent.com/1829399/100564327-b6ccfe80-32fb-11eb-944d-9fa05a258c61.png)
![image](https://user-images.githubusercontent.com/1829399/100564342-bdf40c80-32fb-11eb-9e7f-b6f34ec8be19.png)

**Comment by ys2n** [comment]
Hi.   Is there a workaround for this issue?  Or other way to address it?  Dropping back to a different revision?

**Comment by codemay-dev** [comment]
I'm currently running into the same issue as @terryzwt with the latest repo. Anyone have any additional information on how to resolve or workaround this issue?

**Comment by jonpugh** [comment]
Try the docker-compose.yml file in the project itself: https://github.com/opendevshop/devshop/blob/1.x/docker-compose.yml

The info on that page is old.

**Comment by codemay-dev** [comment]
@jonpugh Thanks for the reply. I've tried running it directly from the project itself as well and get the following error:

![Screen Shot 2021-09-10 at 6 58 17 AM](https://user-images.githubusercontent.com/68574549/132865042-b55fd973-5057-4b9b-b812-3a647df84e74.png)
