### ISSUE TITLE
Best way to add existing drupal sites to dev shop?

### ISSUE THREAD

**Issue by aaronbauman** [opendevshop/devshop#65]
I'm working on moving from managed-by-hand sites workflow to devshop-based workflow.
What's the best way for me to get my existing dev sites into devshop?

**Comment by jonpugh** [comment]
Hi @aaronbauman ...

DevShop is basically just a LAMP stack with a front-end.  

For each project, you'll need a git repo with the full drupal codebase.  Be sure all of your code is in sites/all/modules or themes, not the site specific folder.

Then just add your repo as a new project, and create an initial environment.  DevShop gives you SSH access as the `aegir` user. You can add your SSH keys under "My Account" > "SSH Keys", and it will automatically be added to /var/aegir/.ssh/authorized_keys

Once you have SSH access, you can get your Drush aliases by pressing the "drush" button on a project dashboard. You can either use drush locally to pipe a SQL dump into devshop directly, or you can SSH in and use drush on the server to pull in data.

Does this answer your question?

**Comment by aaronbauman** [comment]
I got as far as the install task (which i don't need, since the site already exists) which keeps failing, complaining that it can't bootstrap.

To make things extra-interesting, i'm trying to set this up for remote filesystem and remote database.
I'll pick this up again tomorrow with a clearer head.

**Comment by jonpugh** [comment]
> I got as far as the install task (which i don't need, since the site already exists).

Every environment has to be created via an install or a clone of an existing environment. This is an aegir limitation. It won't finalize the setup of the site unless it can successfully install or clone one.

We hope to fix this in the future.

I'm not sure what happened to your task, if you can post a screenshot or copy paste of more details i'd be happy to help.

Please join us in the gitter chat room when you start up again tomorrow, we'll be happy to help in realtime there:  https://gitter.im/opendevshop/devshop

Thanks!
Jon

**Comment by llwp** [comment]
I believe this item be resolved.  IF not, feel free to re-open.  I think we've had a chance to chat with @aaronbauman in the gitter chat room... and it has been a delight. ;) Thanks, all!
