### ISSUE TITLE
Add Support for Intl PHP Extension

### ISSUE THREAD

**Issue by matthandus** [opendevshop/devshop#654]
Many Composer packages suggest using the Intl PHP Extension. Some big projects like CiviCRM require Intl PHP Extension.

It looks like the best place to add it is in the opendevshop.apache role. Add the Intl extension list of packages set by the variable 'php_packages_extra'.

File:
roles/opendevshop.apache/vars/Debian.yml

Line 12:
```
php_packages_extra:
  - libapache2-mod-php7.1
  - libapache2-mod-php7.2
  - libapache2-mod-php7.3
  - libapache2-mod-php7.4
```
Suggested new line:
`- php{{ php_version }}-intl`

**Comment by jonpugh** [comment]
That list was added as a quick fix early on in the ansible playbook development.

It's a misuse of `php_packages_extra`.  

The purpose of having that list is for `opendevshop.apache` to be support all versions of php, but that is for another PR.

I would support simply adding that item to the list, but with a comment above it noting why, and a TODO explaining the need to move to our own dedicated variable so users can override `php_packages_extra` in their own systems.
