### ISSUE TITLE
"Allow deploying data from drush aliases" still requires patch?

### ISSUE THREAD

**Issue by aaronbauman** [opendevshop/devshop#66]
The [issue linked from the UI](https://www.drupal.org/node/2407309) has been closed as a duplicate, and the original has been [closed fixed](https://www.drupal.org/node/2585379).

Is the patch still necessary for this setting?

**Comment by jonpugh** [comment]
I have to check if they have made a new release yet or not.

I'll try to confirm this tomorrow.

Thanks!

**Comment by jonpugh** [comment]
No longer needs the patch.  Thanks!
