### ISSUE TITLE
MySQL Start Fails

### ISSUE THREAD

**Issue by benhosmer** [opendevshop/devshop#673]
I'm using the `install.sh` that is mentioned here: https://github.com/opendevshop/documentation/blob/component/docs/install-and-upgrade/installing-devshop.md
But, I seem to get a few failures:

```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
```

```
TASK [opendevshop.users : User ID Change: Stop supervisord] **************************************************************
fatal: [localhost]: FAILED! => changed=false 
  msg: 'Could not find the requested service supervisord: host'
...ignoring
```

```
fatal: [localhost]: FAILED! => changed=true 
  cmd:
  - service
  - mysql
  - start
  delta: '0:00:00.777830'
  end: '2021-04-24 00:29:51.002634'
  msg: non-zero return code
  rc: 5
  start: '2021-04-24 00:29:50.224804'
  stderr: 'Failed to start mysql.service: Unit mysql.service not found.'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

```
fatal: [localhost]: FAILED! => changed=false 
  msg: 'Malformed output discovered from systemd list-unit-files: accounts-daemon.service                enabled         enabled      '

PLAY RECAP ***************************************************************************************************************
localhost                  : ok=23   changed=2    unreachable=0    failed=1    skipped=8    rescued=0    ignored=2   
```
It doesn't seem like mysql ever got installed.

**Comment by liberatr** [comment]
When you get to [line 48 of this task](https://github.com/opendevshop/ansible-role-users/blob/f94f01c343a284bec5e1c9939bb8b485ff7a2ae9/tasks/prepare-user.yml#L48), it does something called "Service Facts" but that doesn't appear to work in 20.04 under the apt-get ansible versions.

[Found on the Ansible issue queue](https://github.com/DataDog/ansible-datadog/issues/274#issuecomment-718071899): 
"Just to update, this looks like it's fixed when you install ansible via pip (pip3 install ansible) instead of apt."

Next failure is at "Run Install DevShop Control Install Command", will report back later.

**Comment by liberatr** [comment]
I'd like to change the name of this issue to "Ubuntu 20.04: Installation" or something.

Here is the log of when the above fails: https://gist.github.com/liberatr/2b3a0ff02eb299864d04bbac50892ecb

No I'm not installing "localhost" but don't want to give out the URL of a half-configured server either.

**Comment by liberatr** [comment]
If I try to break out the `devmaster:install` comand by itself, one error I see is:

> Unable to grant privileges to database users.

**Comment by liberatr** [comment]
Looks like this was fixed in Provision last year sometime: https://www.drupal.org/project/provision/issues/3145881#comment-13750463 I have attempted to make a Pull Request for this on D.o -https://www.drupal.org/project/provision/issues/3217025

**Comment by jonpugh** [comment]
@liberatr @benhosmer I have started a PR to add the test structures to allow Ubuntu 20.

See https://github.com/opendevshop/devshop/pull/677

I will comment on specific issues separately.

**Comment by jonpugh** [comment]
```
> TASK [opendevshop.users : User ID Change: Stop supervisord] **************************************************************
```

I am not happy about this part of the playbook. Using ansible to detect and change a UID was super hacky.

However, I have just merged a quick fix for this specific step in #676 .

I would like to change this behavior to:

 1. If `aegir_user_name`'s actual UID does not match `aegir_user_uid`, throw a warning and tell the user how to fix it.
 2. Update the `devshop-chuid` shell script and use that only when really needed, ie. in the docker container.

**Comment by jonpugh** [comment]
Unstale.

I have no idea why this keeps happening.

I'm working on an entirely new Ansible Collection, tested with Molecule, that seems to work great.

I'll update this issue when it's ready for testing.

**Comment by christianaldenjacobs** [comment]
Thanks Jon! I'll test the new collection when ready.

I can confirm the MYSQL start fail issue is happening for me on both Ubuntu 18 and 20 LTS installations
