### ISSUE TITLE
Docker Install - Could not find the alias @hostmaster

### ISSUE THREAD

**Issue by codemay-dev** [opendevshop/devshop#682]
I'm attempting to run locally using the docker-compose.yml file in the current repo and running into an issue with Devmaster.

$ devshop status returns:

![Screen Shot 2021-09-13 at 10 21 32 AM](https://user-images.githubusercontent.com/68574549/133128857-1c93f14c-f60a-4911-9ffd-fe28d87bc44a.png)

Any insight on correcting this would be greatly appreciated. Thanks!

**Comment by codemay-dev** [comment]
Additional documentation of the issue here:

![Screen Shot 2021-09-16 at 1 56 47 PM](https://user-images.githubusercontent.com/68574549/133684544-060e5d8f-6b55-4f93-bed3-431b89f7d523.png)

**Comment by jonpugh** [comment]
The container wasn't building properly.

It should start up for you now.

Will leave this open for testing.
