### ISSUE TITLE
Running `devshop upgrade` results in PHP Fatal Error (undefined method callGit)

### ISSUE THREAD

**Issue by chadamas** [opendevshop/devshop#686]
Hello, Jon! We attempted a `sudo devshop upgrade` today, and encountered an error that I wanted to bring up here. This was mostly just a test run, since there isn't actually a DevShop update available for our installation, but I would have expected it to confirm this and then exit gracefully. Instead, what we're seeing is

```
PHP Fatal error:  Uncaught Error: Call to undefined method DevShop\Command\SelfUpdate::callGit() 
in /usr/share/devshop/src/DevShop/Command/SelfUpdate.php:120
```
I do see that this method _is_ defined in DevShop's GitRepository class, which extends TQ\Git\Repository, but possibly the SelfUpdate script may not be using this class?

If you have any insight, it would be much appreciated! Thank you.

**Comment by jonpugh** [comment]
Hey @chadamas sorry for the delay but thanks for the tip!

However I wouldn't run that command anymore. It's so old it uses the makefiles and creates a new "platform" etc...  We have to update it.

Latest DevShop `1.x` uses a composer-based Drupal 7 install inside the main repo at `/usr/share/devshop/src/DevShop/Control`.

I don't have an automatic upgrade path for older versions. I'll be updating a couple old servers soon, so I'll do what I can to document and automate the process.

The PR I opened can be used for getting this working again.

**Comment by jonpugh** [comment]
If you started on 1.7.x you have a composer-based front-end, it's easy to upgrade manually with git and composer.

1.7.x used a separate git repo for that, which isn't great. In `1.x` everything is in the same repo.

There's no automatic upgrade path from 1.6.x or 1.7.x yet, but once 1.x is closer to be ready to be 1.8.0 we can work on an upgrade path.

**Comment by jonpugh** [comment]
@chadamas the `devshop upgrade` is now unsupported with the latest 1.x. It won't work for you because you are using a version of devshop built on makefiles.

I wrote up a docs page on how to upgrade manually: https://github.com/opendevshop/devshop/blob/1.x/docs/upgrade-from-1.7.md
