### ISSUE TITLE
Does this support Nginx server on Ubuntu?

### ISSUE THREAD

**Issue by socialnicheguru** [opendevshop/devshop#712]
I am trying to determine if this support Apache2 only, NGINX, or both.

**Comment by ColdSunERA** [comment]
Apache2 only.

**Comment by jonpugh** [comment]
Technically, it's just aegir, so nginx should work, if you really want it.

However, I don't recommend it. The nginx configs that aegir lays down are heavily customized for BOA, Omega8.

Every time I've tried to use them, I've had unexpected consequences, like unintended caching.

At the end of the day, I find that nginx just brings more complexity than it's worth.

**Comment by jonpugh** [comment]
I decided to officially not support nginx, at least not until we have better server config system.

It should be removed from the install script.
