### ISSUE TITLE
What versions of Drupal can I deploy?

### ISSUE THREAD

**Issue by socialnicheguru** [opendevshop/devshop#714]
Can Drupal 6,7,8,9, and 10 be deployed using OpenDevShop?

Which Drupal versions can?

**Comment by jonpugh** [comment]
Automated tests currently run on 7, 8, & 9.

It probably works for 6.x.

10.x had a problem that's probably small.

Note: only `1.x` branch works with sites that include drush, until the next release.

**Comment by socialnicheguru** [comment]
Will Drupal 10 be supported soon?
