### ISSUE TITLE
Clone task for live environment fails when creating env from pull request when there is more than one webhook!

### ISSUE THREAD

**Issue by a-fro** [opendevshop/devshop#72]
We're on a fresh install of 0.8.1. After creating a PR on github (which worked a couple of days ago), the process is no longer working. The error is `There are no valid install profiles on the target platform to migrate to`, which comes just after `Undefined property: stdClass::$hosting_name hosting.module:919`.

In gitter, you mentioned that "Each site gets a unique "hosting_name"... That message can happen if two site nodes get created with the same node title (which is their full domain)
So I bet that somehow, a duplicate site node was created". 

If you mean the node table, then I actually see a number of duplicates:
![screen shot 2016-02-25 at 9 42 12 am](https://cloud.githubusercontent.com/assets/1293063/13322781/18232d8a-dba4-11e5-9528-819774785503.png)

Please advise how to continue troubleshooting. Thanks!

**Comment by jonpugh** [comment]
Great bug report...  The table info is very useful.

The PR/clone system is a bit tricky.  Aegir has to go through multiple steps to make this possible.

Obviously, there shouldn't be those duplicates there.

There must be a problem with how devshop_github.module determines if creating a platform is needed.

**Comment by a-fro** [comment]
@jonpugh one possibly related bit of background is that this is our 2nd time using devshop. We installed it last June, and we were in the middle of two pull requests when we moved to a fresh install of 0.8.1. I wondered if it would be possible to get the two "in-process" environments to install if I closed and re-opened the pull request, which failed. Unfortunately, I can't remember if that was before or after I had created an environment for that branch on github manually (using the "Create New Environment" workflow). At any rate, I hadn't done any of that for the auto delete branch, for example. Please let me know how I can help troubleshoot the devshop_github.module, if that's the likely culprit.

**Comment by jonpugh** [comment]
@a-fro Could you dig through your github webhook payload reports for those failed clones and paste results here?  Look for the "pull request: action" == "opened"

**Comment by a-fro** [comment]
@jonpugh I think you nailed it! It turns out, there were two webhooks, which was causing the duplicates. The devshop version we started using last summer created a webhook, as did 0.8.1. I was able to confirm which was which using the log, given that the history for one goes back to last June. Should I delete that? Or just untick the "Active" box for now and update the webhook?

**Comment by jonpugh** [comment]
Ah!!

**Comment by jonpugh** [comment]
Yes, you can delete the extra webhook... just make sure the one that remains has the right perms, (or just give it all)

**Comment by a-fro** [comment]
Done. Should I also remove the duplicate platform nodes listed in the screenshot above? Or what steps should I take to get devshop happy again?

**Comment by jonpugh** [comment]
Delete the platforms that are missing the  `hosting_name` property. You can tell by the URL alias. If the hosting name is missing, so is the path alias (hosting/c/HOSTING_NAME is the standard URL pattern for aegir). No hosting_name? Path is node/123.

I believe the "Delete" task will fail on those platforms, because the hosting_name is also used for the drush aliases. 

You can do a hard node delete on these platforms, which should also delete the record from the devshop environments table.

**Comment by jonpugh** [comment]
Closing this as out of date, @a-fro ... Let me know if you still have problems!
