### ISSUE TITLE
: Call to undefined function hosting_platform_form_publish_path_validate

### ISSUE THREAD

**Issue by socialnicheguru** [opendevshop/devshop#737]
|https://mysite/node/add/platform|1||Error: Call to undefined function hosting_platform_form_publish_path_validate() in _form_validate() (line 1477 of /usr/share/devshop/src/DevShop/Control/web/includes/form.inc).

i goto add a platfrom on node/add/platform, I get a WSOD and the above in my logs

**Comment by jonpugh** [comment]
Update to latest 1.x branch.

DevShop doesn't use platforms. Create a project then create sites.
