### ISSUE TITLE
Install documentation is confusing

### ISSUE THREAD

**Issue by a-fro** [opendevshop/devshop#74]
In the process of re-installing devshop a half-dozen times last week, I noticed that there are many different places to find installation instructions, and many are different, such as: 
- http://getdevshop.com/ (seems to be the go-to place)
- https://github.com/opendevshop/devshop/blob/0.x/docs/install.md (currently lists 0.7.3)
- https://devshop.readthedocs.org/en/latest/install/ (I assume this is actually install.md above)
- the install.sh script itself, which starts with installation instructions that are different from all the above
- the Drupal.org project page, which points to the readthedocs version

Furthermore, none of the suggestions actually worked for me on a fresh AWS instance running Ubuntu 14.04. If I take the getdevshop.com instructions at face value, `bash install` returns with `/usr/bin/install: /usr/bin/install: cannot execute binary file`. So maybe then I try `sh install.sh`, which ends up exiting with `install.sh: 282: install.sh: Bad substitution`. Hm. Maybe I should follow what's at the top of the install script, and try `sudo ./install.sh`. That returns `sudo: ./install.sh: command not found`. However, if I make the file executable with `chmod +x install.sh`, the installer runs!

Then wait, what is all this `Hostname: ip-172-31-36-172.ec2.internal`? Ah. The "readthedocs" version mentioned that I "must change the hostname manually" if I'm hosting on Amazon Web Services. Ugh! So I start over. I then notice that document says I should be running these as root. 

As you can imagine, at this point I'm either really frustrated, or enjoying the challenge. I love what the devshop team is doing, but I highly recommend simplifying the documentation for new users, while also making host-specific documentation readily accessible. On the devshop Drupal.org project page, for example, I see that documentation is on readthedocs, development is on github and issues are on D.O. Then I notice this chat icon, which leads me to gitter, and I find out that issues are now in github.

I hope this doesn't sound like complaining; again, I _love_ what you're doing (and would love to get involved). I'm just offering some insights from an outsider looking in and getting easily confused. 

Other gotchas for AWS on Ubuntu include the fact that the user you log into with by default is ubuntu. After getting devshop installed, I ran into additional issues with drush because Amazon's documentation has me ssh in as ubuntu, which isn't in the aegir or www-data groups. Drush commands therefore fail, both on the server and if I have aliases set up from my local box. So I can add ubuntu to those groups, or I can add my ec2 pem file (key) to the aegir "authorized_keys" file and then ssh as aegir (both of these methods worked, by the way), but it still feels like a puzzle.

**Comment by jonpugh** [comment]
First, thank you for putting up with all of this!

For a long time I was the only contributor to the code and the documentation, and since code is king, I've spent more of my time there.  

I'm so glad you've done this analysis, because now we know exactly what to fix.  I've made some effort to clean up this stuff, but obviously, not enough.

Let me respond to each item individually, and then we can parse all of this and put together one clean documentation page.

**Comment by jonpugh** [comment]
# Go To Place

- http://GetDevShop.com is the go to place for now.  We hope to keep this page simple and clean, easy to parse for marketing purposes, and easy to navigate from there to the other pages, like the documentation, source code, chat rooms, etc.
- http://docs.devshop.support. This should be the canonical URL for the documentation.  This URL works now, it's just that we have the old URL still hanging around (I've updated drupal.org with this new URL).  These pages are generated from the source code of the project itself. You are correct in your assumption about the install.md page.
- the Drupal.org project page... I would love to retire this completely except as a placeholder. An image and a link to the other places is all we should have there.

**Comment by jonpugh** [comment]
# bash install  != bash install.sh

Ug, how embarrassing. I've fixed this on getdevshop.com.  The command you want is `bash install.sh`

**Comment by jonpugh** [comment]
# Hostname

We just recently fixed this by adding "hostname" as an option in the install.sh script.  I am updating the documentation to reflect this right now.

**Comment by jonpugh** [comment]
# install.sh docs

I've cleaned up the comments at the top of install.sh to match the rest of the documentation.

**Comment by jonpugh** [comment]
> Other gotchas for AWS on Ubuntu include the fact that the user you log into with by default is ubuntu. After getting devshop installed, I ran into additional issues with drush because Amazon's documentation has me ssh in as ubuntu, which isn't in the aegir or www-data groups. Drush commands therefore fail, both on the server and if I have aliases set up from my local box. So I can add ubuntu to those groups, or I can add my ec2 pem file (key) to the aegir "authorized_keys" file and then ssh as aegir (both of these methods worked, by the way), but it still feels like a puzzle.

This is just a part of learning how to operate devshop and aegir.  We should add some more information to the end of the `install.sh` script so users are reminded.  I already added a mention about switching to the aegir user for everything to the install docs page: https://devshop.readthedocs.org/en/latest/install/#

**Comment by a-fro** [comment]
@jonpugh that's **_great_**. The Installing Devshop docs page, in particular, is now much clearer and I think would have been all I needed to feel right at home with my tinkering. D.O. is better too, and it seems like it will be easier to maintain these different channels over time.  

The only final two points I'd make are 1) I still think it would be nice to have a link to the install page from the getdevshop.com installation section and 2) do you have a process in place to make sure that the newest release version gets changed in that Installation section? I ended up first installing 0.8.0 last week, then finding out there was a hotfix after running into issues. The fewer places that need to get updated, the better!

Thanks so much for your feedback and attention.

**Comment by jonpugh** [comment]
> 1) I still think it would be nice to have a link to the install page from the getdevshop.com installation section

Totally agree!  That page is simply the `gh-pages` branch.  If you want, would you visit the "edit" page and add a link for me?  I love pull requests ;)  https://github.com/opendevshop/devshop/edit/gh-pages/index.html

>  2) do you have a process in place to make sure that the newest release version gets changed in that Installation section?

I have it listed in my "release process" instructions, but it is not yet automated.  I want to improve this... I think adding placeholders everywhere it mentions a version, and a search/replace in the `release.sh` helper scripts would be a good thing.

We are working hard to push out a 1.0.0-beta1 today thanks to D6 EOL, and I still have to submit my Drupalcon session applications, and I have to attend DrupalCamp NYC tomorrow, AND I am presenting at the DrupalNYC meetup on wednesday, so that's probably going to have to wait until next week!

**Comment by jonpugh** [comment]
Docs improved. We will be more diligent about changing the latest version on release, and will eventually add it to a robo release command.
