### ISSUE TITLE
When a project has no environments, the projects dashboard goes haywire

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#79]
![screenshot from 2016-03-01 11 14 41](https://cloud.githubusercontent.com/assets/106420/13433209/dac9bc0c-df9e-11e5-8cba-7ad0493de164.png)

**Comment by madalinignisca** [comment]
Happens as well for me.

![screen shot 2016-06-06 at 17 06 10](https://cloud.githubusercontent.com/assets/619561/15828921/3e2ed136-2c09-11e6-8538-066bc7b21ce2.png)

**Comment by madalinignisca** [comment]
Also, if I go to that project directly, if I edit the project, the Delete action just returns to the Project's Dashboard. The Delete action never triggers.

**Comment by madalinignisca** [comment]
I don't know if is 100% because of this, but once you're in this situation, Projects won't delete.

From the Logs:

![screen shot 2016-06-07 at 08 08 05](https://cloud.githubusercontent.com/assets/619561/15848901/73ce95fa-2c87-11e6-9f2d-8564b998187b.png)

I'll try to check more.

**Comment by jonpugh** [comment]
Fixed in e5b7ab6d0571862a64ea5ffc96fdb0beb2efacf0

**Comment by jonpugh** [comment]
Thanks for the bug reports, @madalinignisca . Keep them coming!

**Comment by madalinignisca** [comment]
After I finish my job transition (moving to a medium Drupal Studio) I’ll be back with code.
PS. Is there any discussion on next major version?
